In [1]:
# Parameters
frequency = "1d"
window_pred = 1

In [2]:
import numpy as np
import pandas as pd
from pylab import plt
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score
import os
import talib as ta
import optuna
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.utils.class_weight import compute_sample_weight

# Frecuencia obtenida desde el main
try:
    print(f"Frecuencia recibida desde papermill: {frequency}")
except NameError:
    print(f"No se recibió 'frequency'.")


# Cargar los datos para esta frecuencia de un archivo creado por el main
file_name = f"processed_data_{frequency}_charac.csv"
data = pd.read_csv(file_name, index_col='timestamp')
data

C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Frecuencia recibida desde papermill: 1d

,BTCUSDT_1d,ETHUSDT_1d,XRPUSDT_1d,BNBUSDT_1d,SOLUSDT_1d,ADAUSDT_1d,TRXUSDT_1d,LINKUSDT_1d,AVAXUSDT_1d
timestamp,,,,,,,,,
2020-09-22,10529.61,344.21,0.23302,24.0468,2.9082,0.08146,0.02499,8.7401,5.3193
2020-09-23,10241.46,320.72,0.22164,22.8331,2.8548,0.07663,0.02486,7.6364,3.5350
2020-09-24,10736.32,348.97,0.23276,24.5745,3.1433,0.08254,0.02625,9.8700,4.6411
2020-09-25,10686.67,351.92,0.24154,24.6924,3.1937,0.09693,0.02714,10.7279,4.7134
2020-09-26,10728.60,353.92,0.24153,26.1998,3.1287,0.09547,0.02718,10.3169,4.5200
...,...,...,...,...,...,...,...,...,...
2024-12-28,95300.00,3404.00,2.18430,722.1300,195.5000,0.88950,0.25840,21.9900,37.7400
2024-12-29,93738.20,3356.48,2.09420,694.7100,189.9400,0.85900,0.25780,20.9600,35.8400
2024-12-30,92792.05,3361.84,2.05870,705.3600,191.3800,0.86150,0.25340,20.5800,35.9700
2024-12-31,93576.00,3337.78,2.08360,702.3000,189.3100,0.84510,0.25480,20.0100,35.7100
2025-01-01,94591.79,3360.38,2.33280,707.8400,194.2800,0.92220,0.25590,21.7300,37.7800

Función para guardar los datos. Hace un archivo por cada frecuencia. Guarda en cada línea el modelo que se ha empleado, el activo, accuracy e in/out-sample.

In [ ]:
def save_results(model, ric, acc, sample, frequency=frequency):
    # Verificar si el archivo ya existe
    file_name = f'results_{frequency}_charac.csv'

    # Si el archivo existe, leer los datos previos, si no, crear un nuevo DataFrame vacío
    if os.path.exists(file_name):
        df_results = pd.read_csv(file_name)
    else:
        df_results = pd.DataFrame(columns=['Model', 'Asset', 'Value', 'What'])

    # Agregar la nueva fila con los resultados
    new_row = pd.DataFrame([[model, ric, acc, sample]], columns=['Model', 'Asset', 'Value', 'What'])
    df_results = pd.concat([df_results, new_row], ignore_index=True)

    # Guardar los resultados acumulados
    df_results.to_csv(file_name, index=False)

Creamos las características que usaremos para hacer el aprendizaje ahora y las retardamos.

In [4]:
def charact_lags(data, ric, lags, window_pred, window=30):
    cols = []
    df = pd.DataFrame(data[ric])
    df['r'] = np.log(df / df.shift()) #retornos
    df['sma'] = df[ric].rolling(window).mean()  #media movil de la ventana
    df['min'] = df[ric].rolling(window).min() #mínimo de la ventana
    df['max'] = df[ric].rolling(window).max() #máximo de la ventana
    df['mom'] = df[ric].pct_change(window) #momentum de la ventana pct_change(12)
    df['vol'] = df['r'].rolling(window).std() #volatilidad de la ventana
    df['rsi'] = ta.RSI(df[ric], timeperiod=window) #rsi de la ventana
    df['atr'] = ta.ATR(df[ric], df[ric], df[ric], timeperiod=window) #atr de la ventana
    df = df.iloc[:-window_pred]
    df['d'] = np.where(df[ric].shift(-window_pred) > df[ric], 1, 0) # columna binaria, 0 si los precios bajarán, 1 si subirán
    features = [ric, 'r', 'sma', 'min', 'max', 'mom', 'vol', 'rsi', 'atr']
    for f in features:
        for lag in range(1, lags + 1):
            col = f'{f}_lag_{lag}'
            df[col] = df[f].shift(lag)
            cols.append(col)
    return df, cols

lags = 5

dfs = {}
results = []
for ric in data:
    df, cols = charact_lags(data, ric, lags, window_pred)
    dfs[ric] = df, cols
    p = df['d'].value_counts(normalize=True) 
    results.append({
        'ric': ric,
        '0': p[0],
        '1': p[1]}
        )
results_df = pd.DataFrame(results)
results_df

           ric         0         1
0   BTCUSDT_1d  0.494238  0.505762
1   ETHUSDT_1d  0.478873  0.521127
2   XRPUSDT_1d  0.492318  0.507682
3   BNBUSDT_1d  0.476312  0.523688
4   SOLUSDT_1d  0.498720  0.501280
5   ADAUSDT_1d  0.501280  0.498720
6   TRXUSDT_1d  0.460948  0.539052
7  LINKUSDT_1d  0.483355  0.516645
8  AVAXUSDT_1d  0.503201  0.496799

In [5]:
def normalize_with_close(X, close_col):
    """
    Normaliza columnas ratio en función del precio de cierre.
    """
    ratio_cols = [col for col in X.columns if any(x in col for x in ['sma','atr','min','max'])]
    for col in ratio_cols:
        X[col] = X[col] / close_col
    return X

# ---------------------------------------------------
def prepare_features(df):
    """
    One-hot encoding de la columna 'crypto'.
    """
    crypto_dummies = pd.get_dummies(df['crypto'], prefix='crypto')
    X = pd.concat([df.drop(columns=['crypto']), crypto_dummies], axis=1)
    return X, crypto_dummies.columns

# ---------------------------------------------------

In [ ]:
def walk_forward_fit_test(model_class, freq, model_params={}, n_trials=5, search_space=None, data=data):
    if freq == '1h':
        period = pd.Timedelta(days=14)
    elif freq == '4h':
        period = pd.Timedelta(days=30)
    else:
        period = pd.Timedelta(days=180)
    final_test_period = pd.Timedelta(days=365)

    def suggest_params(trial):
        trial_params = {}
        for param_name, param_info in search_space.items():
            if param_info['type'] == 'int':
                trial_params[param_name] = trial.suggest_int(param_name, *param_info['bounds'])
            elif param_info['type'] == 'float':
                trial_params[param_name] = trial.suggest_float(param_name, *param_info['bounds'], log=param_info.get('log', False))
            elif param_info['type'] == 'categorical':
                trial_params[param_name] = trial.suggest_categorical(param_name, param_info['choices'])
        trial_params.update(model_params)
        return trial_params

    ric_best_params = {}
    desb_graf = []
    df_res = None

    for ric in data:
        df, cols = data[ric]
        df = df[cols + ['d']].copy()
        df.dropna(inplace=True)
        df['timestamp'] = pd.to_datetime(df.index)
        max_time = df['timestamp'].max()
        cutoff = max_time - final_test_period
        df_trainval = df[df['timestamp'] < cutoff].copy()

        # Generar fechas de split
        min_time = df_trainval['timestamp'].min()
        split_dates = []
        current_time = min_time + period
        while current_time < cutoff:
            split_dates.append(current_time)
            current_time += period
        split_dates = split_dates[-5:]

        def objective(trial):
            trial_params = suggest_params(trial)
            resul_acc = []
            resul_f1 = []

            for split_date in split_dates:
                train = df_trainval[df_trainval['timestamp'] < (split_date - pd.Timedelta(days=window_pred))]
                test = df_trainval[(df_trainval['timestamp'] >= split_date) & (df_trainval['timestamp'] < split_date + period)]
                if len(test) == 0:
                    continue

                X_train, y_train = train.drop(columns=['d', 'timestamp']), train['d']
                X_test, y_test = test.drop(columns=['d', 'timestamp']), test['d']
                X_train = normalize_with_close(X_train.copy(), train[f'{ric}_lag_1'])
                X_test = normalize_with_close(X_test.copy(), test[f'{ric}_lag_1'])

                model = model_class(**trial_params)
                if model_class.__name__ == 'MLPClassifier':
                    X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
                    X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
                    model.fit(X_train, y_train)
                else:
                    weights = compute_sample_weight(class_weight='balanced', y=y_train)
                    X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
                    X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
                    model.fit(X_train, y_train, sample_weight=weights)

                pred = np.where(model.predict(X_test) > 0.5, 1, 0)
                f1 = f1_score(y_test, pred, average='macro')
                acc = accuracy_score(y_test, pred)
                resul_acc.append(acc)
                resul_f1.append(f1)

            avg_f1 = np.mean(resul_f1)
            avg_acc = np.mean(resul_acc)
            dist_true = y_test.value_counts(normalize=True).to_dict()
            dist_pred = pd.Series(pred).value_counts(normalize=True).to_dict()
            print(f'VALIDATION |  {ric:7s} | avg_acc={avg_acc:.4f} | avg_f1={avg_f1:.4f}')
            save_results(model_class.__name__, ric, avg_f1, 'F1 VALIDATION', frequency=freq)
            print(f"    Desbalanceo reales (val)      : {dist_true}")
            print(f"    Desbalanceo predicciones (val): {dist_pred}")
            save_results(model_class.__name__, ric, dist_true, 'DESBALANCEO REAL VAL', frequency=freq)
            save_results(model_class.__name__, ric, dist_pred, 'DESBALANCEO PREDICCIÓN VAL', frequency=freq)
            return avg_f1

        study = optuna.create_study(direction="maximize")
        study.optimize(objective, n_trials=n_trials, n_jobs=1)

        best_params = study.best_params
        ric_best_params[ric] = best_params
        print(f"Mejores parámetros para {ric}: {best_params}")

        # Test final con los mejores parámetros
        df_test = df[df['timestamp'] >= cutoff].copy()
        train = df[df['timestamp'] < (cutoff - pd.Timedelta(days=window_pred))]
        test = df_test

        if len(test) == 0:
            continue

        X_train, y_train = train.drop(columns=['d', 'timestamp']), train['d']
        X_test, y_test = test.drop(columns=['d', 'timestamp']), test['d']

        X_train = normalize_with_close(X_train.copy(), train[f'{ric}_lag_1'])
        X_test = normalize_with_close(X_test.copy(), test[f'{ric}_lag_1'])

        model = model_class(**best_params)
        if model_class.__name__ == 'MLPClassifier':
            X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
            X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
            model.fit(X_train, y_train)
        else:
            weights = compute_sample_weight(class_weight='balanced', y=y_train)
            X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
            X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
            model.fit(X_train, y_train, sample_weight=weights)

        pred = np.where(model.predict(X_test) > 0.5, 1, 0)
        df_res = pd.DataFrame({'true': y_test, 'pred': pred})
        acc = accuracy_score(y_test, pred)
        f1 = f1_score(y_test, pred, average='macro')
        dist_true = y_test.value_counts(normalize=True).to_dict()
        dist_pred = pd.Series(pred).value_counts(normalize=True).to_dict()
        real_0 = dist_true.get(0, 0)
        real_1 = dist_true.get(1, 0)
        pred_0 = dist_pred.get(0, 0)
        pred_1 = dist_pred.get(1, 0)

        desb_graf.append({
            "cripto": ric,
            "acc": acc,
            "f1": f1,
            "real_0": real_0,
            "real_1": real_1,
            "pred_0": pred_0,
            "pred_1": pred_1
        })
        print(f'FINAL TEST | {ric:7s} | acc={acc:.4f} | f1={f1:.4f}')
        print(f"    Desbalanceo reales      : {dist_true}")
        print(f"    Desbalanceo predicciones: {dist_pred}")
        save_results(model_class.__name__, ric, acc, 'FINAL TEST', frequency=freq)
        save_results(model_class.__name__, ric, f1, 'F1 FINAL TEST', frequency=freq)
        save_results(model_class.__name__, ric, dist_true, 'DESBALANCEO REAL', frequency=freq)
        save_results(model_class.__name__, ric, dist_pred, 'DESBALANCEO PREDICCIÓN', frequency=freq)

        if model_class.__name__ != 'MLPClassifier':
            df_weights = pd.DataFrame({'y': y_train, 'weight': weights})
            avg_weights = df_weights.groupby('y')['weight'].mean().to_dict()
            print(f"    Pesos promedio entrenamiento: {avg_weights}")

    return ric_best_params, desb_graf, df_res

In [7]:
# === Definición del espacio de búsqueda para cada modelo ===

search_spaces = {
    "MLPClassifier": {
        "hidden_layer_sizes": {"type": "int",   "bounds": (32, 1024), "step": 32},
        "alpha":              {"type": "float", "bounds": (1e-6, 1e-1), "log": True},
        "learning_rate_init": {"type": "float", "bounds": (1e-5, 1e-1), "log": True},
    },
    "RandomForestClassifier": {
        "n_estimators":      {"type": "int",         "bounds": (100, 1000), "step": 100},
        "max_depth":         {"type": "int",         "bounds": (3,   30)},
        "min_samples_split": {"type": "int",         "bounds": (2,   10)},
        "min_samples_leaf":  {"type": "int",         "bounds": (1,   10)},
        "max_features":      {"type": "categorical", "choices": ["sqrt", "log2", None]},
        "bootstrap":         {"type": "categorical", "choices": [True, False]},
    },
    "GradientBoostingClassifier": {
        "n_estimators":      {"type": "int",   "bounds": (50, 500),  "step": 50},
        "learning_rate":     {"type": "float", "bounds": (1e-3, 0.3), "log": True},
        "max_depth":         {"type": "int",   "bounds": (3,   15)},
        "min_samples_split": {"type": "int",   "bounds": (2,   20)},
        "min_samples_leaf":  {"type": "int",   "bounds": (1,   20)},
    },
}

# === Parámetros fijos para cada modelo ===

model_fixed_params = {
    "MLPClassifier": {
        "max_iter": 1000,
        "early_stopping": True,
        "validation_fraction": 0.15,
        "shuffle": False,
        "random_state": 100,
    },
    "RandomForestClassifier": {
        "random_state": 100,
        "n_jobs": -1
    },
    "GradientBoostingClassifier": {
        "random_state": 100
    }
}

# === Diccionario de clases de modelos ===

model_classes = {
    "MLPClassifier": MLPClassifier,
    "RandomForestClassifier": RandomForestClassifier,
    "GradientBoostingClassifier": GradientBoostingClassifier
}

# === Entrenamiento en bucle ===

best_params_dict = {}
desb_graf_dict = {}
data_graf_dict = {}

for model_name, model_cls in model_classes.items():
    print(f"\n\n=== Entrenando modelo: {model_name} ===\n")
    
    best_params, desb_graf, df_res = walk_forward_fit_test(
        model_class=model_cls,
        freq=frequency,
        search_space=search_spaces[model_name],
        model_params=model_fixed_params.get(model_name, {}),
        n_trials=10,
        data=dfs  
    )

    best_params_dict[model_name] = best_params
    desb_graf_dict[model_name] = desb_graf
    data_graf_dict[model_name] = df_res

print("\n\n=== Mejores hiperparámetros por modelo ===")
for model_name, params in best_params_dict.items():
    print(f"{model_name}: {params}")

=== Entrenando modelo: MLPClassifier ===

[I 2025-06-19 16:29:55,471] A new study created in memory with name: no-name-42c2ae42-6452-4733-8d84-31da989ec3b0

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18464\1186695331.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_results = pd.concat([df_results, new_row], ignore_index=True)
[I 2025-06-19 16:29:56,189] Trial 0 finished with value: 0.4220292254601231 and parameters: {'hidden_layer_sizes': 356, 'alpha': 0.05758236937517237, 'learning_rate_init': 0.0005801080958914165}. Best is trial 0 with value: 0.4220292254601231.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4881 | avg_f1=0.4220
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8641975308641975, 1: 0.13580246913580246}

[I 2025-06-19 16:29:56,708] Trial 1 finished with value: 0.4876514346831562 and parameters: {'hidden_layer_sizes': 215, 'alpha': 1.81873725132976e-06, 'learning_rate_init': 0.0010127639720296793}. Best is trial 1 with value: 0.4876514346831562.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5119 | avg_f1=0.4877
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.8395061728395061, 0: 0.16049382716049382}

[I 2025-06-19 16:29:57,449] Trial 2 finished with value: 0.4908103628864575 and parameters: {'hidden_layer_sizes': 644, 'alpha': 1.685101766461613e-05, 'learning_rate_init': 0.0006947816061138453}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5175 | avg_f1=0.4908
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5185185185185185, 0: 0.48148148148148145}

[I 2025-06-19 16:29:57,816] Trial 3 finished with value: 0.34991088532625725 and parameters: {'hidden_layer_sizes': 217, 'alpha': 0.000275332311027488, 'learning_rate_init': 4.283179636877096e-05}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4901 | avg_f1=0.3499
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:29:58,101] Trial 4 finished with value: 0.3297392626030686 and parameters: {'hidden_layer_sizes': 81, 'alpha': 0.0035474724701661992, 'learning_rate_init': 1.8758243604786644e-05}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4943 | avg_f1=0.3297
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:29:58,804] Trial 5 finished with value: 0.33276052276718976 and parameters: {'hidden_layer_sizes': 936, 'alpha': 8.832147556528856e-06, 'learning_rate_init': 0.011499354526543564}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5012 | avg_f1=0.3328
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:29:59,266] Trial 6 finished with value: 0.41379098973225004 and parameters: {'hidden_layer_sizes': 224, 'alpha': 1.259223939131009e-05, 'learning_rate_init': 3.218079664568447e-05}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4879 | avg_f1=0.4138
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8271604938271605, 1: 0.1728395061728395}

[I 2025-06-19 16:29:59,863] Trial 7 finished with value: 0.39350359455405515 and parameters: {'hidden_layer_sizes': 578, 'alpha': 0.000564879667780308, 'learning_rate_init': 0.023781881765266917}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4790 | avg_f1=0.3935
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:00,927] Trial 8 finished with value: 0.42174644273261863 and parameters: {'hidden_layer_sizes': 753, 'alpha': 0.006313204613404261, 'learning_rate_init': 8.494871933041683e-05}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4968 | avg_f1=0.4217
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6790123456790124, 0: 0.32098765432098764}

[I 2025-06-19 16:30:01,894] Trial 9 finished with value: 0.3598417073819894 and parameters: {'hidden_layer_sizes': 1020, 'alpha': 4.274131010563287e-06, 'learning_rate_init': 0.022520239265453296}. Best is trial 2 with value: 0.4908103628864575.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5064 | avg_f1=0.3598
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8148148148148148, 1: 0.18518518518518517}
Mejores parámetros para BTCUSDT_1d: {'hidden_layer_sizes': 644, 'alpha': 1.685101766461613e-05, 'learning_rate_init': 0.0006947816061138453}

[I 2025-06-19 16:30:02,382] A new study created in memory with name: no-name-69daddec-e3fe-4959-b229-634f4567d027

FINAL TEST | BTCUSDT_1d | acc=0.4809 | f1=0.4645
    Desbalanceo reales      : {1: 0.5218579234972678, 0: 0.4781420765027322}
    Desbalanceo predicciones: {0: 0.6967213114754098, 1: 0.30327868852459017}

[I 2025-06-19 16:30:02,987] Trial 0 finished with value: 0.4061933135323095 and parameters: {'hidden_layer_sizes': 378, 'alpha': 0.0014393658358359937, 'learning_rate_init': 0.001210656109440103}. Best is trial 0 with value: 0.4061933135323095.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5032 | avg_f1=0.4062
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 0.9629629629629629, 0: 0.037037037037037035}

[I 2025-06-19 16:30:03,587] Trial 1 finished with value: 0.40547464221537466 and parameters: {'hidden_layer_sizes': 202, 'alpha': 1.654683322952107e-05, 'learning_rate_init': 9.478636970913142e-05}. Best is trial 0 with value: 0.4061933135323095.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4825 | avg_f1=0.4055
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 0.5802469135802469, 0: 0.41975308641975306}

[I 2025-06-19 16:30:04,324] Trial 2 finished with value: 0.4436912810122098 and parameters: {'hidden_layer_sizes': 443, 'alpha': 0.03380907883949562, 'learning_rate_init': 0.009102295028086254}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4894 | avg_f1=0.4437
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 16:30:05,325] Trial 3 finished with value: 0.3793638792937845 and parameters: {'hidden_layer_sizes': 807, 'alpha': 0.0007310546677903149, 'learning_rate_init': 0.00036132394658326726}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5032 | avg_f1=0.3794
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 0.9382716049382716, 0: 0.06172839506172839}

[I 2025-06-19 16:30:05,655] Trial 4 finished with value: 0.3323672606674336 and parameters: {'hidden_layer_sizes': 170, 'alpha': 1.8652969435037553e-06, 'learning_rate_init': 0.05065785896368508}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5012 | avg_f1=0.3324
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:06,201] Trial 5 finished with value: 0.3323672606674336 and parameters: {'hidden_layer_sizes': 635, 'alpha': 0.008072594152127431, 'learning_rate_init': 0.015095440515323234}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5012 | avg_f1=0.3324
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:06,538] Trial 6 finished with value: 0.4032081272641701 and parameters: {'hidden_layer_sizes': 116, 'alpha': 3.6008211541109247e-05, 'learning_rate_init': 0.00043080460025056195}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5323 | avg_f1=0.4032
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:07,386] Trial 7 finished with value: 0.3323672606674336 and parameters: {'hidden_layer_sizes': 990, 'alpha': 0.0005429171503293809, 'learning_rate_init': 0.08372234819426161}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5012 | avg_f1=0.3324
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:08,247] Trial 8 finished with value: 0.41679819738193247 and parameters: {'hidden_layer_sizes': 787, 'alpha': 9.704715584790988e-06, 'learning_rate_init': 0.00032907114418806644}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5235 | avg_f1=0.4168
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:08,532] Trial 9 finished with value: 0.33364267903551525 and parameters: {'hidden_layer_sizes': 72, 'alpha': 0.002692391679575776, 'learning_rate_init': 0.057610677027900785}. Best is trial 2 with value: 0.4436912810122098.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4968 | avg_f1=0.3336
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para ETHUSDT_1d: {'hidden_layer_sizes': 443, 'alpha': 0.03380907883949562, 'learning_rate_init': 0.009102295028086254}

[I 2025-06-19 16:30:08,832] A new study created in memory with name: no-name-af30a2d8-389e-455d-b34e-33c820cd40a2

FINAL TEST | ETHUSDT_1d | acc=0.5328 | f1=0.4711
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {1: 0.8224043715846995, 0: 0.17759562841530055}

[I 2025-06-19 16:30:09,143] Trial 0 finished with value: 0.33431147956094287 and parameters: {'hidden_layer_sizes': 210, 'alpha': 3.734679240443768e-05, 'learning_rate_init': 0.07661489534149002}. Best is trial 0 with value: 0.33431147956094287.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5054 | avg_f1=0.3343
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:09,519] Trial 1 finished with value: 0.4966889566950936 and parameters: {'hidden_layer_sizes': 143, 'alpha': 0.0027108312001652697, 'learning_rate_init': 0.0002674842907544906}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5657 | avg_f1=0.4967
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9382716049382716, 0: 0.06172839506172839}

[I 2025-06-19 16:30:10,042] Trial 2 finished with value: 0.33431147956094287 and parameters: {'hidden_layer_sizes': 651, 'alpha': 2.5887928750530693e-06, 'learning_rate_init': 0.03969316763302847}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5054 | avg_f1=0.3343
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:10,518] Trial 3 finished with value: 0.3387142138906845 and parameters: {'hidden_layer_sizes': 361, 'alpha': 0.00015042276113880359, 'learning_rate_init': 0.0063931099935757305}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4943 | avg_f1=0.3387
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:11,331] Trial 4 finished with value: 0.40974228480933306 and parameters: {'hidden_layer_sizes': 598, 'alpha': 1.26504020023842e-05, 'learning_rate_init': 0.00033943012147593364}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4852 | avg_f1=0.4097
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.8395061728395061, 0: 0.16049382716049382}

[I 2025-06-19 16:30:12,120] Trial 5 finished with value: 0.43842729475439757 and parameters: {'hidden_layer_sizes': 834, 'alpha': 8.552932227442234e-06, 'learning_rate_init': 0.00018221134305234165}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4842 | avg_f1=0.4384
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.7160493827160493, 0: 0.2839506172839506}

[I 2025-06-19 16:30:12,703] Trial 6 finished with value: 0.46911220533586134 and parameters: {'hidden_layer_sizes': 430, 'alpha': 0.00010828079767512834, 'learning_rate_init': 0.0009497976869514152}. Best is trial 1 with value: 0.4966889566950936.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5205 | avg_f1=0.4691
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.654320987654321, 0: 0.345679012345679}

[I 2025-06-19 16:30:14,030] Trial 7 finished with value: 0.5069312536143267 and parameters: {'hidden_layer_sizes': 931, 'alpha': 0.0008199579046277004, 'learning_rate_init': 9.355649550156621e-05}. Best is trial 7 with value: 0.5069312536143267.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5363 | avg_f1=0.5069
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6666666666666666, 0: 0.3333333333333333}

[I 2025-06-19 16:30:14,574] Trial 8 finished with value: 0.3827435110796338 and parameters: {'hidden_layer_sizes': 299, 'alpha': 0.008683410063563823, 'learning_rate_init': 0.010717804378943988}. Best is trial 7 with value: 0.5069312536143267.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4728 | avg_f1=0.3827
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8271604938271605, 1: 0.1728395061728395}

[I 2025-06-19 16:30:15,424] Trial 9 finished with value: 0.3523479168079064 and parameters: {'hidden_layer_sizes': 804, 'alpha': 1.0500062779569256e-06, 'learning_rate_init': 0.0014090908524171978}. Best is trial 7 with value: 0.5069312536143267.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4956 | avg_f1=0.3523
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.8024691358024691, 0: 0.19753086419753085}
Mejores parámetros para XRPUSDT_1d: {'hidden_layer_sizes': 931, 'alpha': 0.0008199579046277004, 'learning_rate_init': 9.355649550156621e-05}

[I 2025-06-19 16:30:16,007] A new study created in memory with name: no-name-ad19db2b-2faa-4693-9d83-ffb46a313c0d

FINAL TEST | XRPUSDT_1d | acc=0.5273 | f1=0.5265
    Desbalanceo reales      : {1: 0.5081967213114754, 0: 0.4918032786885246}
    Desbalanceo predicciones: {0: 0.5491803278688525, 1: 0.45081967213114754}

[I 2025-06-19 16:30:17,202] Trial 0 finished with value: 0.36774297597195055 and parameters: {'hidden_layer_sizes': 947, 'alpha': 0.05168737899137721, 'learning_rate_init': 9.148822886383672e-05}. Best is trial 0 with value: 0.36774297597195055.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5119 | avg_f1=0.3677
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9135802469135802, 0: 0.08641975308641975}

[I 2025-06-19 16:30:17,929] Trial 1 finished with value: 0.42438018909139374 and parameters: {'hidden_layer_sizes': 535, 'alpha': 8.264775336234937e-05, 'learning_rate_init': 0.0001770951891251041}. Best is trial 1 with value: 0.42438018909139374.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4891 | avg_f1=0.4244
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.8148148148148148, 0: 0.18518518518518517}

[I 2025-06-19 16:30:18,461] Trial 2 finished with value: 0.5075624039365078 and parameters: {'hidden_layer_sizes': 288, 'alpha': 2.8766619570539803e-05, 'learning_rate_init': 2.012427401383467e-05}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5333 | avg_f1=0.5076
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}

[I 2025-06-19 16:30:19,273] Trial 3 finished with value: 0.34134978588312 and parameters: {'hidden_layer_sizes': 907, 'alpha': 0.0001940439857560596, 'learning_rate_init': 0.02322332822636206}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5114 | avg_f1=0.3413
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9629629629629629, 0: 0.037037037037037035}

[I 2025-06-19 16:30:19,925] Trial 4 finished with value: 0.47123841221848084 and parameters: {'hidden_layer_sizes': 209, 'alpha': 0.003862957697889696, 'learning_rate_init': 7.576135554916464e-05}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5202 | avg_f1=0.4712
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.7654320987654321, 0: 0.2345679012345679}

[I 2025-06-19 16:30:20,789] Trial 5 finished with value: 0.40098087007017486 and parameters: {'hidden_layer_sizes': 548, 'alpha': 6.361869624345192e-05, 'learning_rate_init': 4.5295878372432175e-05}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4667 | avg_f1=0.4010
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7530864197530864, 1: 0.24691358024691357}

[I 2025-06-19 16:30:21,211] Trial 6 finished with value: 0.3929904015056583 and parameters: {'hidden_layer_sizes': 413, 'alpha': 3.608887473874085e-06, 'learning_rate_init': 0.03162730521660553}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4891 | avg_f1=0.3930
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8888888888888888, 1: 0.1111111111111111}

[I 2025-06-19 16:30:22,305] Trial 7 finished with value: 0.4069811293767832 and parameters: {'hidden_layer_sizes': 903, 'alpha': 0.010485156529743545, 'learning_rate_init': 1.8667096336407035e-05}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5264 | avg_f1=0.4070
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.8271604938271605, 0: 0.1728395061728395}

[I 2025-06-19 16:30:23,309] Trial 8 finished with value: 0.3592691757484502 and parameters: {'hidden_layer_sizes': 1007, 'alpha': 1.0904777617580901e-06, 'learning_rate_init': 6.73658405981918e-05}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5111 | avg_f1=0.3593
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9012345679012346, 0: 0.09876543209876543}

[I 2025-06-19 16:30:23,673] Trial 9 finished with value: 0.3954975798106233 and parameters: {'hidden_layer_sizes': 93, 'alpha': 4.452295050903456e-06, 'learning_rate_init': 0.00015588382959941884}. Best is trial 2 with value: 0.5075624039365078.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4916 | avg_f1=0.3955
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5308641975308642, 0: 0.4691358024691358}
Mejores parámetros para BNBUSDT_1d: {'hidden_layer_sizes': 288, 'alpha': 2.8766619570539803e-05, 'learning_rate_init': 2.012427401383467e-05}

[I 2025-06-19 16:30:24,515] A new study created in memory with name: no-name-05326e54-764b-4147-8ac2-cf9acfc7ecfc

FINAL TEST | BNBUSDT_1d | acc=0.5464 | f1=0.5144
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {1: 0.7377049180327869, 0: 0.26229508196721313}

[I 2025-06-19 16:30:24,958] Trial 0 finished with value: 0.3725209638116156 and parameters: {'hidden_layer_sizes': 168, 'alpha': 1.7275481970884783e-06, 'learning_rate_init': 1.7966785127568418e-05}. Best is trial 0 with value: 0.3725209638116156.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5069 | avg_f1=0.3725
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.8888888888888888, 1: 0.1111111111111111}

[I 2025-06-19 16:30:25,556] Trial 1 finished with value: 0.45118543978764547 and parameters: {'hidden_layer_sizes': 466, 'alpha': 6.167802595471715e-06, 'learning_rate_init': 0.000260326096220247}. Best is trial 1 with value: 0.45118543978764547.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4837 | avg_f1=0.4512
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.6419753086419753, 0: 0.35802469135802467}

[I 2025-06-19 16:30:25,985] Trial 2 finished with value: 0.3564790065062796 and parameters: {'hidden_layer_sizes': 117, 'alpha': 1.1196653918306445e-06, 'learning_rate_init': 0.014503118063872352}. Best is trial 1 with value: 0.45118543978764547.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4595 | avg_f1=0.3565
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:27,347] Trial 3 finished with value: 0.3810291263949991 and parameters: {'hidden_layer_sizes': 934, 'alpha': 0.0006223777866946021, 'learning_rate_init': 0.00014835157141635698}. Best is trial 1 with value: 0.45118543978764547.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5151 | avg_f1=0.3810
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:27,654] Trial 4 finished with value: 0.3733313074393637 and parameters: {'hidden_layer_sizes': 45, 'alpha': 0.0003931569429288517, 'learning_rate_init': 0.0007012407053705109}. Best is trial 1 with value: 0.45118543978764547.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4795 | avg_f1=0.3733
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:28,358] Trial 5 finished with value: 0.4831879231880006 and parameters: {'hidden_layer_sizes': 477, 'alpha': 0.00011297916019200704, 'learning_rate_init': 0.0015894267833312479}. Best is trial 5 with value: 0.4831879231880006.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5183 | avg_f1=0.4832
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.9012345679012346, 0: 0.09876543209876543}

[I 2025-06-19 16:30:29,266] Trial 6 finished with value: 0.3624645485601202 and parameters: {'hidden_layer_sizes': 983, 'alpha': 4.593178794088691e-06, 'learning_rate_init': 0.015575122931001023}. Best is trial 5 with value: 0.4831879231880006.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4951 | avg_f1=0.3625
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:29,711] Trial 7 finished with value: 0.3503650106919287 and parameters: {'hidden_layer_sizes': 343, 'alpha': 0.06650947928893884, 'learning_rate_init': 0.029675211952446733}. Best is trial 5 with value: 0.4831879231880006.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5094 | avg_f1=0.3504
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.9259259259259259, 0: 0.07407407407407407}

[I 2025-06-19 16:30:30,168] Trial 8 finished with value: 0.39334996208988143 and parameters: {'hidden_layer_sizes': 447, 'alpha': 3.686563237131876e-05, 'learning_rate_init': 0.0001683179161007157}. Best is trial 5 with value: 0.4831879231880006.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4835 | avg_f1=0.3933
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.8024691358024691, 0: 0.19753086419753085}

[I 2025-06-19 16:30:30,670] Trial 9 finished with value: 0.3247960538981 and parameters: {'hidden_layer_sizes': 632, 'alpha': 0.06452528220730308, 'learning_rate_init': 1.2188544225055174e-05}. Best is trial 5 with value: 0.4831879231880006.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4827 | avg_f1=0.3248
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para SOLUSDT_1d: {'hidden_layer_sizes': 477, 'alpha': 0.00011297916019200704, 'learning_rate_init': 0.0015894267833312479}

[I 2025-06-19 16:30:30,914] A new study created in memory with name: no-name-583db999-7618-48d6-b48e-65a934d26a51

FINAL TEST | SOLUSDT_1d | acc=0.4863 | f1=0.3272
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {0: 1.0}

[I 2025-06-19 16:30:31,874] Trial 0 finished with value: 0.4204355264554948 and parameters: {'hidden_layer_sizes': 777, 'alpha': 0.0014967165557616714, 'learning_rate_init': 1.3492446390938308e-05}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4721 | avg_f1=0.4204
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}

[I 2025-06-19 16:30:32,978] Trial 1 finished with value: 0.4109500665889444 and parameters: {'hidden_layer_sizes': 876, 'alpha': 3.147093315004325e-05, 'learning_rate_init': 0.00022792101214867198}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4580 | avg_f1=0.4110
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:30:33,382] Trial 2 finished with value: 0.32707925005705496 and parameters: {'hidden_layer_sizes': 386, 'alpha': 6.439560712909243e-05, 'learning_rate_init': 0.0038746791554919112}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4881 | avg_f1=0.3271
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:33,761] Trial 3 finished with value: 0.3485195235702565 and parameters: {'hidden_layer_sizes': 145, 'alpha': 0.0003739870312259222, 'learning_rate_init': 0.004872506001509633}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4815 | avg_f1=0.3485
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:34,331] Trial 4 finished with value: 0.382706574199964 and parameters: {'hidden_layer_sizes': 462, 'alpha': 0.0002083170734046181, 'learning_rate_init': 0.0032435454408526886}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4970 | avg_f1=0.3827
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:35,052] Trial 5 finished with value: 0.32752497186473595 and parameters: {'hidden_layer_sizes': 673, 'alpha': 2.2995386870565215e-05, 'learning_rate_init': 0.0013268972785238685}. Best is trial 0 with value: 0.4204355264554948.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4681 | avg_f1=0.3275
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:35,879] Trial 6 finished with value: 0.49481050092510426 and parameters: {'hidden_layer_sizes': 816, 'alpha': 0.00016549718057062938, 'learning_rate_init': 7.870628549615475e-05}. Best is trial 6 with value: 0.49481050092510426.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5479 | avg_f1=0.4948
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 16:30:36,294] Trial 7 finished with value: 0.3317147487647026 and parameters: {'hidden_layer_sizes': 437, 'alpha': 0.0001829017566345564, 'learning_rate_init': 1.2553116799335298e-05}. Best is trial 6 with value: 0.49481050092510426.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4985 | avg_f1=0.3317
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:37,041] Trial 8 finished with value: 0.34171127757339914 and parameters: {'hidden_layer_sizes': 431, 'alpha': 0.006045819275196809, 'learning_rate_init': 0.0019732282272976074}. Best is trial 6 with value: 0.49481050092510426.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4726 | avg_f1=0.3417
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:37,596] Trial 9 finished with value: 0.3251038330245703 and parameters: {'hidden_layer_sizes': 748, 'alpha': 2.943463022307287e-06, 'learning_rate_init': 0.03017677321351503}. Best is trial 6 with value: 0.49481050092510426.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4837 | avg_f1=0.3251
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 1.0}
Mejores parámetros para ADAUSDT_1d: {'hidden_layer_sizes': 816, 'alpha': 0.00016549718057062938, 'learning_rate_init': 7.870628549615475e-05}

[I 2025-06-19 16:30:38,150] A new study created in memory with name: no-name-6d0afe66-5b5c-4187-828a-7bcc6e376269

FINAL TEST | ADAUSDT_1d | acc=0.4918 | f1=0.4868
    Desbalanceo reales      : {0: 0.5081967213114754, 1: 0.4918032786885246}
    Desbalanceo predicciones: {0: 0.5901639344262295, 1: 0.4098360655737705}

[I 2025-06-19 16:30:38,452] Trial 0 finished with value: 0.38459380730308135 and parameters: {'hidden_layer_sizes': 87, 'alpha': 3.535041575419355e-06, 'learning_rate_init': 0.00013290682432497638}. Best is trial 0 with value: 0.38459380730308135.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5593 | avg_f1=0.3846
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 0.8395061728395061, 0: 0.16049382716049382}

[I 2025-06-19 16:30:39,159] Trial 1 finished with value: 0.39070232301223473 and parameters: {'hidden_layer_sizes': 643, 'alpha': 1.5239806623152397e-06, 'learning_rate_init': 0.000999484753076497}. Best is trial 1 with value: 0.39070232301223473.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5188 | avg_f1=0.3907
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 16:30:39,649] Trial 2 finished with value: 0.3592178674534573 and parameters: {'hidden_layer_sizes': 614, 'alpha': 2.6315807965691275e-06, 'learning_rate_init': 0.061682651236059406}. Best is trial 1 with value: 0.39070232301223473.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5617 | avg_f1=0.3592
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:39,947] Trial 3 finished with value: 0.3789825691236857 and parameters: {'hidden_layer_sizes': 52, 'alpha': 0.0034701614010089915, 'learning_rate_init': 0.001669997997893774}. Best is trial 1 with value: 0.39070232301223473.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5684 | avg_f1=0.3790
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:40,286] Trial 4 finished with value: 0.5096900750458457 and parameters: {'hidden_layer_sizes': 67, 'alpha': 7.680797496517063e-05, 'learning_rate_init': 0.0010034371402836049}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5694 | avg_f1=0.5097
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 0.7160493827160493, 0: 0.2839506172839506}

[I 2025-06-19 16:30:40,778] Trial 5 finished with value: 0.472844296910233 and parameters: {'hidden_layer_sizes': 422, 'alpha': 6.95335368326305e-06, 'learning_rate_init': 1.7799592292735684e-05}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5146 | avg_f1=0.4728
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5061728395061729, 1: 0.49382716049382713}

[I 2025-06-19 16:30:41,427] Trial 6 finished with value: 0.3592178674534573 and parameters: {'hidden_layer_sizes': 824, 'alpha': 0.013413328463136327, 'learning_rate_init': 0.024322235582280728}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5617 | avg_f1=0.3592
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:41,755] Trial 7 finished with value: 0.37034816721814623 and parameters: {'hidden_layer_sizes': 104, 'alpha': 2.839859913577929e-05, 'learning_rate_init': 0.0002448694046891768}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5617 | avg_f1=0.3703
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:42,598] Trial 8 finished with value: 0.3592178674534573 and parameters: {'hidden_layer_sizes': 920, 'alpha': 1.3210387176632806e-05, 'learning_rate_init': 0.00504724107052643}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5617 | avg_f1=0.3592
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:43,279] Trial 9 finished with value: 0.3592178674534573 and parameters: {'hidden_layer_sizes': 794, 'alpha': 1.0089539999724304e-05, 'learning_rate_init': 0.025065780307892735}. Best is trial 4 with value: 0.5096900750458457.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5617 | avg_f1=0.3592
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para TRXUSDT_1d: {'hidden_layer_sizes': 67, 'alpha': 7.680797496517063e-05, 'learning_rate_init': 0.0010034371402836049}
FINAL TEST | TRXUSDT_1d | acc=0.5328 | f1=0.3770
    Desbalanceo reales      : {1: 0.5327868852459017, 0: 0.4672131147540984}
    Desbalanceo predicciones: {1: 0.9672131147540983, 0: 0.03278688524590164}

[I 2025-06-19 16:30:43,459] A new study created in memory with name: no-name-c1f697c1-6463-4348-9d81-5463a6d35323

[I 2025-06-19 16:30:43,997] Trial 0 finished with value: 0.41515396623031914 and parameters: {'hidden_layer_sizes': 355, 'alpha': 4.207871819566166e-06, 'learning_rate_init': 0.0003185604245096386}. Best is trial 0 with value: 0.41515396623031914.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5279 | avg_f1=0.4152
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9876543209876543, 0: 0.012345679012345678}

[I 2025-06-19 16:30:44,369] Trial 1 finished with value: 0.4005879265437418 and parameters: {'hidden_layer_sizes': 112, 'alpha': 4.466627486666722e-05, 'learning_rate_init': 0.003034663397433219}. Best is trial 0 with value: 0.41515396623031914.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5183 | avg_f1=0.4006
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.9259259259259259, 0: 0.07407407407407407}

[I 2025-06-19 16:30:44,858] Trial 2 finished with value: 0.41431084248763117 and parameters: {'hidden_layer_sizes': 196, 'alpha': 0.0010514093008600074, 'learning_rate_init': 0.003856310790264146}. Best is trial 0 with value: 0.41515396623031914.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5136 | avg_f1=0.4143
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:30:46,060] Trial 3 finished with value: 0.45675527582052816 and parameters: {'hidden_layer_sizes': 856, 'alpha': 0.00017149636858359093, 'learning_rate_init': 5.623857432268351e-05}. Best is trial 3 with value: 0.45675527582052816.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5042 | avg_f1=0.4568
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}

[I 2025-06-19 16:30:46,697] Trial 4 finished with value: 0.34490560455831687 and parameters: {'hidden_layer_sizes': 833, 'alpha': 0.0008818066098688835, 'learning_rate_init': 0.04903360722447892}. Best is trial 3 with value: 0.45675527582052816.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5277 | avg_f1=0.3449
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:47,245] Trial 5 finished with value: 0.34490560455831687 and parameters: {'hidden_layer_sizes': 616, 'alpha': 0.011028545670660165, 'learning_rate_init': 0.005944597457008925}. Best is trial 3 with value: 0.45675527582052816.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5277 | avg_f1=0.3449
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:47,935] Trial 6 finished with value: 0.39798380995528976 and parameters: {'hidden_layer_sizes': 424, 'alpha': 0.023687712202298216, 'learning_rate_init': 0.002130863332119595}. Best is trial 3 with value: 0.45675527582052816.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5254 | avg_f1=0.3980
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:48,502] Trial 7 finished with value: 0.4848048573600702 and parameters: {'hidden_layer_sizes': 126, 'alpha': 0.016233369781977244, 'learning_rate_init': 0.0002414855010232573}. Best is trial 7 with value: 0.4848048573600702.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4970 | avg_f1=0.4848
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5061728395061729, 1: 0.49382716049382713}

[I 2025-06-19 16:30:49,600] Trial 8 finished with value: 0.39084469858402626 and parameters: {'hidden_layer_sizes': 840, 'alpha': 0.0001604191970144499, 'learning_rate_init': 0.01636073454288567}. Best is trial 7 with value: 0.4848048573600702.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4909 | avg_f1=0.3908
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}

[I 2025-06-19 16:30:49,885] Trial 9 finished with value: 0.3202299540461775 and parameters: {'hidden_layer_sizes': 118, 'alpha': 7.394553992060886e-06, 'learning_rate_init': 9.485380714309869e-05}. Best is trial 7 with value: 0.4848048573600702.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4723 | avg_f1=0.3202
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 1.0}
Mejores parámetros para LINKUSDT_1d: {'hidden_layer_sizes': 126, 'alpha': 0.016233369781977244, 'learning_rate_init': 0.0002414855010232573}

[I 2025-06-19 16:30:50,433] A new study created in memory with name: no-name-8110e5bb-b4f0-4067-8d90-3d5757fce73c

FINAL TEST | LINKUSDT_1d | acc=0.5164 | f1=0.4952
    Desbalanceo reales      : {0: 0.5109289617486339, 1: 0.4890710382513661}
    Desbalanceo predicciones: {1: 0.7158469945355191, 0: 0.28415300546448086}

[I 2025-06-19 16:30:50,782] Trial 0 finished with value: 0.35331058491608536 and parameters: {'hidden_layer_sizes': 121, 'alpha': 0.002776110870076244, 'learning_rate_init': 0.016862804727367547}. Best is trial 0 with value: 0.35331058491608536.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5358 | avg_f1=0.3533
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:51,285] Trial 1 finished with value: 0.33733356954086763 and parameters: {'hidden_layer_sizes': 400, 'alpha': 0.05495944902449312, 'learning_rate_init': 0.0017418254881615169}. Best is trial 0 with value: 0.35331058491608536.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4467 | avg_f1=0.3373
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.9876543209876543, 1: 0.012345679012345678}

[I 2025-06-19 16:30:52,144] Trial 2 finished with value: 0.38116872488175807 and parameters: {'hidden_layer_sizes': 760, 'alpha': 0.0318572237584497, 'learning_rate_init': 0.007727922371067076}. Best is trial 2 with value: 0.38116872488175807.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5269 | avg_f1=0.3812
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.9506172839506173, 0: 0.04938271604938271}

[I 2025-06-19 16:30:53,135] Trial 3 finished with value: 0.3583681374216897 and parameters: {'hidden_layer_sizes': 818, 'alpha': 0.00031694268166299945, 'learning_rate_init': 0.002685375406499375}. Best is trial 2 with value: 0.38116872488175807.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4531 | avg_f1=0.3584
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:53,822] Trial 4 finished with value: 0.4237816200586658 and parameters: {'hidden_layer_sizes': 571, 'alpha': 0.002530343363971692, 'learning_rate_init': 0.00036689257804185707}. Best is trial 4 with value: 0.4237816200586658.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5405 | avg_f1=0.4238
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.9876543209876543, 0: 0.012345679012345678}

[I 2025-06-19 16:30:54,317] Trial 5 finished with value: 0.5049319609208179 and parameters: {'hidden_layer_sizes': 254, 'alpha': 0.007042361546127741, 'learning_rate_init': 0.00019733391461600492}. Best is trial 5 with value: 0.5049319609208179.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5244 | avg_f1=0.5049
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.6296296296296297, 0: 0.37037037037037035}

[I 2025-06-19 16:30:54,704] Trial 6 finished with value: 0.33825862567807957 and parameters: {'hidden_layer_sizes': 356, 'alpha': 0.0038264451370700783, 'learning_rate_init': 3.6313704159069015e-05}. Best is trial 5 with value: 0.5049319609208179.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5158 | avg_f1=0.3383
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-19 16:30:56,138] Trial 7 finished with value: 0.4889529166369361 and parameters: {'hidden_layer_sizes': 916, 'alpha': 2.804620678807946e-06, 'learning_rate_init': 0.0004515335301966147}. Best is trial 5 with value: 0.5049319609208179.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5114 | avg_f1=0.4890
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 16:30:56,614] Trial 8 finished with value: 0.33828231101656214 and parameters: {'hidden_layer_sizes': 383, 'alpha': 0.0025284950961967445, 'learning_rate_init': 3.9187722712840415e-05}. Best is trial 5 with value: 0.5049319609208179.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4686 | avg_f1=0.3383
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-19 16:30:57,237] Trial 9 finished with value: 0.3706506522561527 and parameters: {'hidden_layer_sizes': 595, 'alpha': 7.258248729682154e-05, 'learning_rate_init': 0.03398919121663598}. Best is trial 5 with value: 0.5049319609208179.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5225 | avg_f1=0.3707
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para AVAXUSDT_1d: {'hidden_layer_sizes': 254, 'alpha': 0.007042361546127741, 'learning_rate_init': 0.00019733391461600492}

[I 2025-06-19 16:30:57,622] A new study created in memory with name: no-name-cc404448-ec44-4fdd-a0f1-0a1df820a137

FINAL TEST | AVAXUSDT_1d | acc=0.4809 | f1=0.4803
    Desbalanceo reales      : {0: 0.5382513661202186, 1: 0.46174863387978143}
    Desbalanceo predicciones: {1: 0.505464480874317, 0: 0.49453551912568305}


=== Entrenando modelo: RandomForestClassifier ===

[I 2025-06-19 16:30:58,614] Trial 0 finished with value: 0.428880329608558 and parameters: {'n_estimators': 155, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.428880329608558.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4706 | avg_f1=0.4289
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7530864197530864, 1: 0.24691358024691357}

[I 2025-06-19 16:31:07,221] Trial 1 finished with value: 0.4294922022777957 and parameters: {'n_estimators': 658, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}. Best is trial 1 with value: 0.4294922022777957.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4669 | avg_f1=0.4295
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.9506172839506173, 1: 0.04938271604938271}

[I 2025-06-19 16:31:10,053] Trial 2 finished with value: 0.4061949636057083 and parameters: {'n_estimators': 534, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.4294922022777957.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4565 | avg_f1=0.4062
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}

[I 2025-06-19 16:31:20,728] Trial 3 finished with value: 0.4189471573553396 and parameters: {'n_estimators': 955, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.4294922022777957.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4583 | avg_f1=0.4189
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:31:23,271] Trial 4 finished with value: 0.43278176550492986 and parameters: {'n_estimators': 483, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.43278176550492986.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4822 | avg_f1=0.4328
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}

[I 2025-06-19 16:31:27,490] Trial 5 finished with value: 0.4137124470311253 and parameters: {'n_estimators': 804, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 4 with value: 0.43278176550492986.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4617 | avg_f1=0.4137
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:31:31,709] Trial 6 finished with value: 0.4108106007086067 and parameters: {'n_estimators': 804, 'max_depth': 28, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.43278176550492986.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4506 | avg_f1=0.4108
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 16:31:45,989] Trial 7 finished with value: 0.43735000832822823 and parameters: {'n_estimators': 969, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}. Best is trial 7 with value: 0.43735000832822823.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4610 | avg_f1=0.4374
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:31:48,353] Trial 8 finished with value: 0.43748457362772414 and parameters: {'n_estimators': 440, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 8 with value: 0.43748457362772414.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4798 | avg_f1=0.4375
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7901234567901234, 1: 0.20987654320987653}

[I 2025-06-19 16:31:49,962] Trial 9 finished with value: 0.42682090867241307 and parameters: {'n_estimators': 282, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 8 with value: 0.43748457362772414.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4657 | avg_f1=0.4268
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}
Mejores parámetros para BTCUSDT_1d: {'n_estimators': 440, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}

[I 2025-06-19 16:31:51,696] A new study created in memory with name: no-name-b9703bab-57b0-48de-bd11-4ae053a243d0

FINAL TEST | BTCUSDT_1d | acc=0.5137 | f1=0.5028
    Desbalanceo reales      : {1: 0.5218579234972678, 0: 0.4781420765027322}
    Desbalanceo predicciones: {0: 0.6693989071038251, 1: 0.33060109289617484}
    Pesos promedio entrenamiento: {0: 0.9931506849315068, 1: 1.0069444444444444}

[I 2025-06-19 16:31:53,941] Trial 0 finished with value: 0.436984971552397 and parameters: {'n_estimators': 409, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.436984971552397.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4649 | avg_f1=0.4370
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8518518518518519, 1: 0.14814814814814814}

[I 2025-06-19 16:32:07,687] Trial 1 finished with value: 0.44734724348258614 and parameters: {'n_estimators': 676, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 1 with value: 0.44734724348258614.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4832 | avg_f1=0.4473
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.5185185185185185, 1: 0.48148148148148145}

[I 2025-06-19 16:32:17,054] Trial 2 finished with value: 0.47291894356433845 and parameters: {'n_estimators': 535, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4854 | avg_f1=0.4729
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.5432098765432098, 1: 0.4567901234567901}

[I 2025-06-19 16:32:21,363] Trial 3 finished with value: 0.42701104739007184 and parameters: {'n_estimators': 827, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4607 | avg_f1=0.4270
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8641975308641975, 1: 0.13580246913580246}

[I 2025-06-19 16:32:25,258] Trial 4 finished with value: 0.4444080438754313 and parameters: {'n_estimators': 745, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4780 | avg_f1=0.4444
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8641975308641975, 1: 0.13580246913580246}

[I 2025-06-19 16:32:29,441] Trial 5 finished with value: 0.4305695646988209 and parameters: {'n_estimators': 794, 'max_depth': 27, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4652 | avg_f1=0.4306
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8641975308641975, 1: 0.13580246913580246}

[I 2025-06-19 16:32:32,692] Trial 6 finished with value: 0.43511461572332727 and parameters: {'n_estimators': 705, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4647 | avg_f1=0.4351
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8395061728395061, 1: 0.16049382716049382}

[I 2025-06-19 16:32:35,670] Trial 7 finished with value: 0.44158502329550053 and parameters: {'n_estimators': 516, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4635 | avg_f1=0.4416
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}

[I 2025-06-19 16:32:36,740] Trial 8 finished with value: 0.46266071332073383 and parameters: {'n_estimators': 176, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4849 | avg_f1=0.4627
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:32:38,066] Trial 9 finished with value: 0.4505268989950414 and parameters: {'n_estimators': 217, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 2 with value: 0.47291894356433845.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4751 | avg_f1=0.4505
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}
Mejores parámetros para ETHUSDT_1d: {'n_estimators': 535, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:32:57,920] A new study created in memory with name: no-name-fe8855c9-13ca-47a6-8c26-c76778d3f738

FINAL TEST | ETHUSDT_1d | acc=0.4945 | f1=0.4942
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {1: 0.505464480874317, 0: 0.49453551912568305}
    Pesos promedio entrenamiento: {0: 1.037567084078712, 1: 0.9650582362728786}

[I 2025-06-19 16:33:02,342] Trial 0 finished with value: 0.5222341548088649 and parameters: {'n_estimators': 824, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5338 | avg_f1=0.5222
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6049382716049383, 0: 0.3950617283950617}

[I 2025-06-19 16:33:06,144] Trial 1 finished with value: 0.5009272112244363 and parameters: {'n_estimators': 665, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5099 | avg_f1=0.5009
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5185185185185185, 0: 0.48148148148148145}

[I 2025-06-19 16:33:09,779] Trial 2 finished with value: 0.4937289475471463 and parameters: {'n_estimators': 338, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5059 | avg_f1=0.4937
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}

[I 2025-06-19 16:33:11,404] Trial 3 finished with value: 0.4965249812064007 and parameters: {'n_estimators': 291, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5101 | avg_f1=0.4965
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5308641975308642, 0: 0.4691358024691358}

[I 2025-06-19 16:33:12,357] Trial 4 finished with value: 0.47692831002321034 and parameters: {'n_estimators': 148, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4914 | avg_f1=0.4769
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5555555555555556, 0: 0.4444444444444444}

[I 2025-06-19 16:33:28,418] Trial 5 finished with value: 0.47977843328829434 and parameters: {'n_estimators': 806, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4921 | avg_f1=0.4798
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.691358024691358, 0: 0.30864197530864196}

[I 2025-06-19 16:33:29,233] Trial 6 finished with value: 0.47234605539352187 and parameters: {'n_estimators': 121, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4877 | avg_f1=0.4723
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5925925925925926, 0: 0.4074074074074074}

[I 2025-06-19 16:33:38,107] Trial 7 finished with value: 0.46878995710151716 and parameters: {'n_estimators': 415, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4849 | avg_f1=0.4688
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:33:43,172] Trial 8 finished with value: 0.4936645221396754 and parameters: {'n_estimators': 963, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5096 | avg_f1=0.4937
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6049382716049383, 0: 0.3950617283950617}

[I 2025-06-19 16:33:47,656] Trial 9 finished with value: 0.4851188412180739 and parameters: {'n_estimators': 854, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5222341548088649.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5010 | avg_f1=0.4851
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5925925925925926, 0: 0.4074074074074074}
Mejores parámetros para XRPUSDT_1d: {'n_estimators': 824, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}

[I 2025-06-19 16:33:54,120] A new study created in memory with name: no-name-3c4ec0d7-b3d2-48f8-a49d-c01fb786ad81

FINAL TEST | XRPUSDT_1d | acc=0.5109 | f1=0.5086
    Desbalanceo reales      : {1: 0.5081967213114754, 0: 0.4918032786885246}
    Desbalanceo predicciones: {1: 0.5601092896174863, 0: 0.43989071038251365}
    Pesos promedio entrenamiento: {0: 1.0104529616724738, 1: 0.9897610921501706}

[I 2025-06-19 16:33:56,966] Trial 0 finished with value: 0.4493916338148634 and parameters: {'n_estimators': 532, 'max_depth': 28, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.4493916338148634.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4719 | avg_f1=0.4494
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 16:33:58,806] Trial 1 finished with value: 0.41743545131559384 and parameters: {'n_estimators': 335, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4493916338148634.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4575 | avg_f1=0.4174
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8395061728395061, 1: 0.16049382716049382}

[I 2025-06-19 16:34:02,075] Trial 2 finished with value: 0.4203564391408646 and parameters: {'n_estimators': 618, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4493916338148634.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4691 | avg_f1=0.4204
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 16:34:05,012] Trial 3 finished with value: 0.3901558491420182 and parameters: {'n_estimators': 625, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.4493916338148634.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4435 | avg_f1=0.3902
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8518518518518519, 1: 0.14814814814814814}

[I 2025-06-19 16:34:12,933] Trial 4 finished with value: 0.3969537710847605 and parameters: {'n_estimators': 852, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.4493916338148634.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4244 | avg_f1=0.3970
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:34:24,608] Trial 5 finished with value: 0.4625349166811089 and parameters: {'n_estimators': 708, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 5 with value: 0.4625349166811089.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4694 | avg_f1=0.4625
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 16:34:27,389] Trial 6 finished with value: 0.42515879958151076 and parameters: {'n_estimators': 502, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.4625349166811089.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4536 | avg_f1=0.4252
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:34:32,472] Trial 7 finished with value: 0.4033714258732191 and parameters: {'n_estimators': 989, 'max_depth': 27, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 0.4625349166811089.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4528 | avg_f1=0.4034
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8024691358024691, 1: 0.19753086419753085}

[I 2025-06-19 16:34:37,329] Trial 8 finished with value: 0.42363161595366916 and parameters: {'n_estimators': 971, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 0.4625349166811089.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4595 | avg_f1=0.4236
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8024691358024691, 1: 0.19753086419753085}

[I 2025-06-19 16:34:40,384] Trial 9 finished with value: 0.4255958454106857 and parameters: {'n_estimators': 577, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.4625349166811089.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4620 | avg_f1=0.4256
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8148148148148148, 1: 0.18518518518518517}
Mejores parámetros para BNBUSDT_1d: {'n_estimators': 708, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:35:06,128] A new study created in memory with name: no-name-93e92661-54cc-4a86-a20c-c82e61602b9c

FINAL TEST | BNBUSDT_1d | acc=0.4536 | f1=0.4519
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {1: 0.5355191256830601, 0: 0.4644808743169399}
    Pesos promedio entrenamiento: {0: 1.039426523297491, 1: 0.9634551495016611}

[I 2025-06-19 16:35:10,093] Trial 0 finished with value: 0.4935794463373687 and parameters: {'n_estimators': 838, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.4935794463373687.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5089 | avg_f1=0.4936
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6296296296296297, 1: 0.37037037037037035}

[I 2025-06-19 16:35:19,558] Trial 1 finished with value: 0.4969686228792936 and parameters: {'n_estimators': 578, 'max_depth': 26, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}. Best is trial 1 with value: 0.4969686228792936.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5054 | avg_f1=0.4970
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}

[I 2025-06-19 16:35:21,581] Trial 2 finished with value: 0.47243975358747325 and parameters: {'n_estimators': 364, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.4969686228792936.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4933 | avg_f1=0.4724
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}

[I 2025-06-19 16:35:24,339] Trial 3 finished with value: 0.5015392806518889 and parameters: {'n_estimators': 535, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.5015392806518889.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5274 | avg_f1=0.5015
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}

[I 2025-06-19 16:35:28,599] Trial 4 finished with value: 0.48992749747148334 and parameters: {'n_estimators': 855, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.5015392806518889.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5156 | avg_f1=0.4899
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}

[I 2025-06-19 16:35:31,686] Trial 5 finished with value: 0.4922162854050887 and parameters: {'n_estimators': 164, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': False}. Best is trial 3 with value: 0.5015392806518889.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5143 | avg_f1=0.4922
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.6296296296296297, 0: 0.37037037037037035}

[I 2025-06-19 16:35:32,660] Trial 6 finished with value: 0.4914664873444373 and parameters: {'n_estimators': 173, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 3 with value: 0.5015392806518889.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5091 | avg_f1=0.4915
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}

[I 2025-06-19 16:35:48,664] Trial 7 finished with value: 0.49385849784549424 and parameters: {'n_estimators': 942, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 3 with value: 0.5015392806518889.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5027 | avg_f1=0.4939
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}

[I 2025-06-19 16:35:58,552] Trial 8 finished with value: 0.5117516948135704 and parameters: {'n_estimators': 554, 'max_depth': 29, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 8 with value: 0.5117516948135704.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5240 | avg_f1=0.5118
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.5308641975308642, 0: 0.4691358024691358}

[I 2025-06-19 16:36:15,382] Trial 9 finished with value: 0.5111272758701568 and parameters: {'n_estimators': 832, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 8 with value: 0.5117516948135704.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5202 | avg_f1=0.5111
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}
Mejores parámetros para SOLUSDT_1d: {'n_estimators': 554, 'max_depth': 29, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:36:34,701] A new study created in memory with name: no-name-f22da73d-e4c7-4e55-b4e6-fec5755701e4

FINAL TEST | SOLUSDT_1d | acc=0.5137 | f1=0.5134
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {1: 0.5081967213114754, 0: 0.4918032786885246}
    Pesos promedio entrenamiento: {0: 0.9982788296041308, 1: 1.001727115716753}

[I 2025-06-19 16:36:37,091] Trial 0 finished with value: 0.465919885632501 and parameters: {'n_estimators': 424, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5114 | avg_f1=0.4659
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}

[I 2025-06-19 16:36:37,899] Trial 1 finished with value: 0.4532620391202384 and parameters: {'n_estimators': 134, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5062 | avg_f1=0.4533
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}

[I 2025-06-19 16:36:41,818] Trial 2 finished with value: 0.43672977081557124 and parameters: {'n_estimators': 977, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5131 | avg_f1=0.4367
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.8271604938271605, 0: 0.1728395061728395}

[I 2025-06-19 16:36:44,231] Trial 3 finished with value: 0.4505360967403965 and parameters: {'n_estimators': 556, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5077 | avg_f1=0.4505
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5802469135802469, 0: 0.41975308641975306}

[I 2025-06-19 16:36:50,396] Trial 4 finished with value: 0.4407577001378923 and parameters: {'n_estimators': 601, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4810 | avg_f1=0.4408
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 16:36:53,181] Trial 5 finished with value: 0.4393015866818972 and parameters: {'n_estimators': 537, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.465919885632501.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4916 | avg_f1=0.4393
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}

[I 2025-06-19 16:37:01,133] Trial 6 finished with value: 0.47651621780863207 and parameters: {'n_estimators': 495, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.47651621780863207.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5077 | avg_f1=0.4765
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5925925925925926, 1: 0.4074074074074074}

[I 2025-06-19 16:37:13,895] Trial 7 finished with value: 0.47402273697522707 and parameters: {'n_estimators': 632, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.47651621780863207.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5170 | avg_f1=0.4740
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 16:37:18,364] Trial 8 finished with value: 0.46128515113958013 and parameters: {'n_estimators': 834, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.47651621780863207.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5062 | avg_f1=0.4613
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 16:37:23,187] Trial 9 finished with value: 0.4694445243843427 and parameters: {'n_estimators': 955, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.47651621780863207.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5232 | avg_f1=0.4694
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}
Mejores parámetros para ADAUSDT_1d: {'n_estimators': 495, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:37:43,645] A new study created in memory with name: no-name-19de8cd4-6086-4434-8bdd-052edbf63f66

FINAL TEST | ADAUSDT_1d | acc=0.4863 | f1=0.4856
    Desbalanceo reales      : {0: 0.5081967213114754, 1: 0.4918032786885246}
    Desbalanceo predicciones: {1: 0.546448087431694, 0: 0.453551912568306}
    Pesos promedio entrenamiento: {0: 0.9982788296041308, 1: 1.001727115716753}

[I 2025-06-19 16:37:44,379] Trial 0 finished with value: 0.5051661221613966 and parameters: {'n_estimators': 112, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5051661221613966.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5079 | avg_f1=0.5052
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}

[I 2025-06-19 16:37:45,078] Trial 1 finished with value: 0.48324626235497803 and parameters: {'n_estimators': 103, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5051661221613966.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4931 | avg_f1=0.4832
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7530864197530864, 1: 0.24691358024691357}

[I 2025-06-19 16:37:47,280] Trial 2 finished with value: 0.5013002910488834 and parameters: {'n_estimators': 424, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5051661221613966.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5072 | avg_f1=0.5013
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}

[I 2025-06-19 16:37:48,362] Trial 3 finished with value: 0.5185026803779424 and parameters: {'n_estimators': 224, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 3 with value: 0.5185026803779424.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5279 | avg_f1=0.5185
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}

[I 2025-06-19 16:37:52,544] Trial 4 finished with value: 0.5135258620689654 and parameters: {'n_estimators': 813, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.5185026803779424.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5178 | avg_f1=0.5135
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}

[I 2025-06-19 16:37:54,605] Trial 5 finished with value: 0.5035126015900977 and parameters: {'n_estimators': 402, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 3 with value: 0.5185026803779424.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5094 | avg_f1=0.5035
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 16:37:59,617] Trial 6 finished with value: 0.5196225371896481 and parameters: {'n_estimators': 979, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.5196225371896481.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5227 | avg_f1=0.5196
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 16:38:07,051] Trial 7 finished with value: 0.4616194272251441 and parameters: {'n_estimators': 491, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.5196225371896481.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5323 | avg_f1=0.4616
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {1: 0.7777777777777778, 0: 0.2222222222222222}

[I 2025-06-19 16:38:10,368] Trial 8 finished with value: 0.514082964924867 and parameters: {'n_estimators': 628, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.5196225371896481.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5178 | avg_f1=0.5141
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}

[I 2025-06-19 16:38:11,578] Trial 9 finished with value: 0.521056230411168 and parameters: {'n_estimators': 258, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 9 with value: 0.521056230411168.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5296 | avg_f1=0.5211
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}
Mejores parámetros para TRXUSDT_1d: {'n_estimators': 258, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}

[I 2025-06-19 16:38:12,362] A new study created in memory with name: no-name-a5ddbbe5-9cd9-4885-b8a0-373ddce6942b

FINAL TEST | TRXUSDT_1d | acc=0.4891 | f1=0.4854
    Desbalanceo reales      : {1: 0.5327868852459017, 0: 0.4672131147540984}
    Desbalanceo predicciones: {1: 0.5519125683060109, 0: 0.44808743169398907}
    Pesos promedio entrenamiento: {0: 1.0902255639097744, 1: 0.9235668789808917}

[I 2025-06-19 16:38:27,568] Trial 0 finished with value: 0.5226554160125588 and parameters: {'n_estimators': 626, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5309 | avg_f1=0.5227
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5925925925925926, 1: 0.4074074074074074}

[I 2025-06-19 16:38:34,266] Trial 1 finished with value: 0.4465340138214399 and parameters: {'n_estimators': 966, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4659 | avg_f1=0.4465
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8148148148148148, 1: 0.18518518518518517}

[I 2025-06-19 16:38:35,660] Trial 2 finished with value: 0.42712470536061653 and parameters: {'n_estimators': 253, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4583 | avg_f1=0.4271
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.9382716049382716, 1: 0.06172839506172839}

[I 2025-06-19 16:38:39,339] Trial 3 finished with value: 0.41087404418303286 and parameters: {'n_estimators': 715, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4454 | avg_f1=0.4109
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.9629629629629629, 1: 0.037037037037037035}

[I 2025-06-19 16:38:42,471] Trial 4 finished with value: 0.4628745253708977 and parameters: {'n_estimators': 543, 'max_depth': 26, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4815 | avg_f1=0.4629
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 16:39:04,062] Trial 5 finished with value: 0.5048757462926705 and parameters: {'n_estimators': 968, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5131 | avg_f1=0.5049
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:39:06,209] Trial 6 finished with value: 0.46033474138202746 and parameters: {'n_estimators': 318, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4790 | avg_f1=0.4603
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8271604938271605, 1: 0.1728395061728395}

[I 2025-06-19 16:39:10,263] Trial 7 finished with value: 0.4988311172568082 and parameters: {'n_estimators': 148, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5084 | avg_f1=0.4988
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 16:39:12,010] Trial 8 finished with value: 0.45862247704247583 and parameters: {'n_estimators': 296, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4817 | avg_f1=0.4586
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.8024691358024691, 1: 0.19753086419753085}

[I 2025-06-19 16:39:12,767] Trial 9 finished with value: 0.47819814728701343 and parameters: {'n_estimators': 108, 'max_depth': 21, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.5226554160125588.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4963 | avg_f1=0.4782
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}
Mejores parámetros para LINKUSDT_1d: {'n_estimators': 626, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:39:46,834] A new study created in memory with name: no-name-b2d7c70a-3139-4089-ad19-255764fd5ebf

FINAL TEST | LINKUSDT_1d | acc=0.5328 | f1=0.5302
    Desbalanceo reales      : {0: 0.5109289617486339, 1: 0.4890710382513661}
    Desbalanceo predicciones: {0: 0.5628415300546448, 1: 0.4371584699453552}
    Pesos promedio entrenamiento: {0: 1.0507246376811594, 1: 0.9539473684210527}

[I 2025-06-19 16:39:48,750] Trial 0 finished with value: 0.5037728772673753 and parameters: {'n_estimators': 359, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5037728772673753.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5116 | avg_f1=0.5038
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:39:53,158] Trial 1 finished with value: 0.5022291879582539 and parameters: {'n_estimators': 896, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5037728772673753.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5119 | avg_f1=0.5022
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5555555555555556, 0: 0.4444444444444444}

[I 2025-06-19 16:39:56,543] Trial 2 finished with value: 0.48621432480352356 and parameters: {'n_estimators': 664, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.5037728772673753.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4936 | avg_f1=0.4862
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5308641975308642, 0: 0.4691358024691358}

[I 2025-06-19 16:39:57,658] Trial 3 finished with value: 0.48789888948723464 and parameters: {'n_estimators': 176, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.5037728772673753.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4978 | avg_f1=0.4879
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:40:02,183] Trial 4 finished with value: 0.503999305375021 and parameters: {'n_estimators': 903, 'max_depth': 22, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 4 with value: 0.503999305375021.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5119 | avg_f1=0.5040
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5555555555555556, 0: 0.4444444444444444}

[I 2025-06-19 16:40:10,112] Trial 5 finished with value: 0.523192066139973 and parameters: {'n_estimators': 448, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 5 with value: 0.523192066139973.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5323 | avg_f1=0.5232
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5432098765432098, 1: 0.4567901234567901}

[I 2025-06-19 16:40:14,542] Trial 6 finished with value: 0.48756856189905734 and parameters: {'n_estimators': 856, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 0.523192066139973.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4956 | avg_f1=0.4876
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:40:18,936] Trial 7 finished with value: 0.5071723598645853 and parameters: {'n_estimators': 844, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 0.523192066139973.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5146 | avg_f1=0.5072
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5555555555555556, 0: 0.4444444444444444}

[I 2025-06-19 16:40:22,231] Trial 8 finished with value: 0.5076928011831113 and parameters: {'n_estimators': 627, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 0.523192066139973.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5143 | avg_f1=0.5077
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:40:24,384] Trial 9 finished with value: 0.5084668905500906 and parameters: {'n_estimators': 492, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.523192066139973.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5454 | avg_f1=0.5085
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.8271604938271605, 0: 0.1728395061728395}
Mejores parámetros para AVAXUSDT_1d: {'n_estimators': 448, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}

[I 2025-06-19 16:40:40,623] A new study created in memory with name: no-name-f970c334-38e4-4543-9bc4-bfae96e5c765

FINAL TEST | AVAXUSDT_1d | acc=0.5000 | f1=0.4968
    Desbalanceo reales      : {0: 0.5382513661202186, 1: 0.46174863387978143}
    Desbalanceo predicciones: {0: 0.5409836065573771, 1: 0.45901639344262296}
    Pesos promedio entrenamiento: {0: 1.0193321616871704, 1: 0.9813874788494078}


=== Entrenando modelo: GradientBoostingClassifier ===

[I 2025-06-19 16:40:52,205] Trial 0 finished with value: 0.435557318985765 and parameters: {'n_estimators': 120, 'learning_rate': 0.0012073396227225135, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.435557318985765.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4607 | avg_f1=0.4356
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:41:43,442] Trial 1 finished with value: 0.38064845104425316 and parameters: {'n_estimators': 485, 'learning_rate': 0.003464815280551025, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.435557318985765.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4099 | avg_f1=0.3806
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}

[I 2025-06-19 16:42:57,822] Trial 2 finished with value: 0.4384414566647939 and parameters: {'n_estimators': 483, 'learning_rate': 0.016071543009137993, 'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 11}. Best is trial 2 with value: 0.4384414566647939.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4585 | avg_f1=0.4384
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 16:43:40,356] Trial 3 finished with value: 0.4426928556302894 and parameters: {'n_estimators': 363, 'learning_rate': 0.25694353076008025, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4630 | avg_f1=0.4427
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 16:44:07,620] Trial 4 finished with value: 0.435176921832805 and parameters: {'n_estimators': 202, 'learning_rate': 0.001262128091764405, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4474 | avg_f1=0.4352
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5061728395061729, 1: 0.49382716049382713}

[I 2025-06-19 16:44:22,404] Trial 5 finished with value: 0.4185802482280428 and parameters: {'n_estimators': 338, 'learning_rate': 0.0617825199662274, 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4494 | avg_f1=0.4186
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:44:39,426] Trial 6 finished with value: 0.43157576518123636 and parameters: {'n_estimators': 400, 'learning_rate': 0.01291906007940729, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 20}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4632 | avg_f1=0.4316
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 16:45:38,391] Trial 7 finished with value: 0.4154419493332087 and parameters: {'n_estimators': 456, 'learning_rate': 0.002323830821288693, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4516 | avg_f1=0.4154
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 16:46:06,048] Trial 8 finished with value: 0.40374267136548614 and parameters: {'n_estimators': 191, 'learning_rate': 0.039612582382135615, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4296 | avg_f1=0.4037
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}

[I 2025-06-19 16:47:07,377] Trial 9 finished with value: 0.4128418731384782 and parameters: {'n_estimators': 354, 'learning_rate': 0.031047547823314616, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 3 with value: 0.4426928556302894.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4459 | avg_f1=0.4128
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5185185185185185, 1: 0.48148148148148145}
Mejores parámetros para BTCUSDT_1d: {'n_estimators': 363, 'learning_rate': 0.25694353076008025, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 10}

[I 2025-06-19 16:47:20,627] A new study created in memory with name: no-name-3ae3c5be-36d5-411d-8c36-d41e7341eab5

FINAL TEST | BTCUSDT_1d | acc=0.5410 | f1=0.5387
    Desbalanceo reales      : {1: 0.5218579234972678, 0: 0.4781420765027322}
    Desbalanceo predicciones: {0: 0.592896174863388, 1: 0.40710382513661203}
    Pesos promedio entrenamiento: {0: 0.9931506849315068, 1: 1.0069444444444444}

[I 2025-06-19 16:48:13,669] Trial 0 finished with value: 0.4547308553439652 and parameters: {'n_estimators': 493, 'learning_rate': 0.027784170729252267, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.4547308553439652.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4820 | avg_f1=0.4547
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7777777777777778, 1: 0.2222222222222222}

[I 2025-06-19 16:48:23,572] Trial 1 finished with value: 0.44078611437071463 and parameters: {'n_estimators': 142, 'learning_rate': 0.03397949940229482, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.4547308553439652.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4602 | avg_f1=0.4408
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8148148148148148, 1: 0.18518518518518517}

[I 2025-06-19 16:49:08,767] Trial 2 finished with value: 0.44583973033996205 and parameters: {'n_estimators': 399, 'learning_rate': 0.005059286663586002, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.4547308553439652.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4674 | avg_f1=0.4458
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 16:49:20,683] Trial 3 finished with value: 0.47632726061551545 and parameters: {'n_estimators': 120, 'learning_rate': 0.0017693515622481727, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 11}. Best is trial 3 with value: 0.47632726061551545.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4859 | avg_f1=0.4763
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.5185185185185185, 1: 0.48148148148148145}

[I 2025-06-19 16:49:26,788] Trial 4 finished with value: 0.4602176975553543 and parameters: {'n_estimators': 51, 'learning_rate': 0.004802056466434686, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 3 with value: 0.47632726061551545.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4728 | avg_f1=0.4602
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.5061728395061729, 1: 0.49382716049382713}

[I 2025-06-19 16:49:39,308] Trial 5 finished with value: 0.41453874994544054 and parameters: {'n_estimators': 286, 'learning_rate': 0.015384634058204689, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.47632726061551545.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4410 | avg_f1=0.4145
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.8024691358024691, 1: 0.19753086419753085}

[I 2025-06-19 16:49:56,604] Trial 6 finished with value: 0.4804573136883626 and parameters: {'n_estimators': 150, 'learning_rate': 0.023730573038819983, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 14}. Best is trial 6 with value: 0.4804573136883626.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4948 | avg_f1=0.4805
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.6296296296296297, 1: 0.37037037037037035}

[I 2025-06-19 16:50:27,930] Trial 7 finished with value: 0.4742868824450991 and parameters: {'n_estimators': 475, 'learning_rate': 0.010497033868891458, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 19}. Best is trial 6 with value: 0.4804573136883626.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4911 | avg_f1=0.4743
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}

[I 2025-06-19 16:50:41,638] Trial 8 finished with value: 0.47205257057482986 and parameters: {'n_estimators': 116, 'learning_rate': 0.2822864665065324, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.4804573136883626.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4889 | avg_f1=0.4721
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}

[I 2025-06-19 16:51:09,069] Trial 9 finished with value: 0.44481660175545495 and parameters: {'n_estimators': 330, 'learning_rate': 0.004512877973714019, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.4804573136883626.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4657 | avg_f1=0.4448
    Desbalanceo reales (val)      : {1: 0.6172839506172839, 0: 0.38271604938271603}
    Desbalanceo predicciones (val): {0: 0.7407407407407407, 1: 0.25925925925925924}
Mejores parámetros para ETHUSDT_1d: {'n_estimators': 150, 'learning_rate': 0.023730573038819983, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 14}

[I 2025-06-19 16:51:13,850] A new study created in memory with name: no-name-9c9aeb3f-8098-4513-8b3d-3f2f268a21e8

FINAL TEST | ETHUSDT_1d | acc=0.5027 | f1=0.5018
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {0: 0.5628415300546448, 1: 0.4371584699453552}
    Pesos promedio entrenamiento: {0: 1.037567084078712, 1: 0.9650582362728786}

[I 2025-06-19 16:51:29,540] Trial 0 finished with value: 0.5157978340903935 and parameters: {'n_estimators': 278, 'learning_rate': 0.014148187514186757, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.5157978340903935.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5205 | avg_f1=0.5158
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6049382716049383, 0: 0.3950617283950617}

[I 2025-06-19 16:51:43,601] Trial 1 finished with value: 0.4436341517562619 and parameters: {'n_estimators': 179, 'learning_rate': 0.0010548524722260432, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.5157978340903935.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4464 | avg_f1=0.4436
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5308641975308642, 1: 0.4691358024691358}

[I 2025-06-19 16:51:59,592] Trial 2 finished with value: 0.491010387915163 and parameters: {'n_estimators': 287, 'learning_rate': 0.010318991602588083, 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 13}. Best is trial 0 with value: 0.5157978340903935.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4980 | avg_f1=0.4910
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}

[I 2025-06-19 16:52:31,298] Trial 3 finished with value: 0.4779028722029257 and parameters: {'n_estimators': 264, 'learning_rate': 0.001095539730972589, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 12}. Best is trial 0 with value: 0.5157978340903935.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4830 | avg_f1=0.4779
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}

[I 2025-06-19 16:53:05,935] Trial 4 finished with value: 0.5002910617995775 and parameters: {'n_estimators': 445, 'learning_rate': 0.053607690762385626, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.5157978340903935.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5047 | avg_f1=0.5003
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5679012345679012, 0: 0.43209876543209874}

[I 2025-06-19 16:53:32,743] Trial 5 finished with value: 0.5233536721194623 and parameters: {'n_estimators': 383, 'learning_rate': 0.0972067637641204, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 5 with value: 0.5233536721194623.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5291 | avg_f1=0.5234
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}

[I 2025-06-19 16:53:44,525] Trial 6 finished with value: 0.4873162650095221 and parameters: {'n_estimators': 270, 'learning_rate': 0.0067895795986722815, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 5 with value: 0.5233536721194623.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4909 | avg_f1=0.4873
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 16:53:52,708] Trial 7 finished with value: 0.5226280252340534 and parameters: {'n_estimators': 145, 'learning_rate': 0.20378082565529657, 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 10}. Best is trial 5 with value: 0.5233536721194623.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5291 | avg_f1=0.5226
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6172839506172839, 0: 0.38271604938271603}

[I 2025-06-19 16:54:20,932] Trial 8 finished with value: 0.48857545430460425 and parameters: {'n_estimators': 261, 'learning_rate': 0.13212323258936126, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 14}. Best is trial 5 with value: 0.5233536721194623.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4968 | avg_f1=0.4886
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.6049382716049383, 0: 0.3950617283950617}

[I 2025-06-19 16:55:07,723] Trial 9 finished with value: 0.47732552101778164 and parameters: {'n_estimators': 373, 'learning_rate': 0.005226352753184537, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 14}. Best is trial 5 with value: 0.5233536721194623.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4840 | avg_f1=0.4773
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}
Mejores parámetros para XRPUSDT_1d: {'n_estimators': 383, 'learning_rate': 0.0972067637641204, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5}

[I 2025-06-19 16:55:14,830] A new study created in memory with name: no-name-744d8b42-bdfc-43b7-8bd4-cb80b952618f

FINAL TEST | XRPUSDT_1d | acc=0.5137 | f1=0.5116
    Desbalanceo reales      : {1: 0.5081967213114754, 0: 0.4918032786885246}
    Desbalanceo predicciones: {1: 0.5573770491803278, 0: 0.4426229508196721}
    Pesos promedio entrenamiento: {0: 1.0104529616724738, 1: 0.9897610921501706}

[I 2025-06-19 16:55:31,881] Trial 0 finished with value: 0.43095043834199737 and parameters: {'n_estimators': 257, 'learning_rate': 0.08795291349495157, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 0 with value: 0.43095043834199737.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4509 | avg_f1=0.4310
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 16:56:25,370] Trial 1 finished with value: 0.4471068998767137 and parameters: {'n_estimators': 324, 'learning_rate': 0.012282560970919126, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.4471068998767137.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4669 | avg_f1=0.4471
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:56:49,732] Trial 2 finished with value: 0.43700305991327665 and parameters: {'n_estimators': 323, 'learning_rate': 0.2195699019134159, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 20}. Best is trial 1 with value: 0.4471068998767137.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4546 | avg_f1=0.4370
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 16:56:55,535] Trial 3 finished with value: 0.44991606283575314 and parameters: {'n_estimators': 54, 'learning_rate': 0.0038052600648408024, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 7}. Best is trial 3 with value: 0.44991606283575314.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4694 | avg_f1=0.4499
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}

[I 2025-06-19 16:57:08,589] Trial 4 finished with value: 0.4373550524303639 and parameters: {'n_estimators': 105, 'learning_rate': 0.07278514279596962, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 14}. Best is trial 3 with value: 0.44991606283575314.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4546 | avg_f1=0.4374
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 16:57:18,387] Trial 5 finished with value: 0.43671565883747493 and parameters: {'n_estimators': 115, 'learning_rate': 0.03008499466999458, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 20}. Best is trial 3 with value: 0.44991606283575314.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4521 | avg_f1=0.4367
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6790123456790124, 1: 0.32098765432098764}

[I 2025-06-19 16:57:48,484] Trial 6 finished with value: 0.46986503036671945 and parameters: {'n_estimators': 294, 'learning_rate': 0.002469004274286109, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.46986503036671945.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4899 | avg_f1=0.4699
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}

[I 2025-06-19 16:58:02,275] Trial 7 finished with value: 0.41447419211359804 and parameters: {'n_estimators': 116, 'learning_rate': 0.005759385715816376, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.46986503036671945.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4412 | avg_f1=0.4145
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}

[I 2025-06-19 16:58:22,733] Trial 8 finished with value: 0.46231328201148203 and parameters: {'n_estimators': 268, 'learning_rate': 0.12463461540555931, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 18}. Best is trial 6 with value: 0.46986503036671945.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4783 | avg_f1=0.4623
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 16:58:28,294] Trial 9 finished with value: 0.44046800294858135 and parameters: {'n_estimators': 72, 'learning_rate': 0.12418539518385857, 'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 18}. Best is trial 6 with value: 0.46986503036671945.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4578 | avg_f1=0.4405
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}
Mejores parámetros para BNBUSDT_1d: {'n_estimators': 294, 'learning_rate': 0.002469004274286109, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 5}

[I 2025-06-19 16:58:36,442] A new study created in memory with name: no-name-c56ed14e-243f-492c-8780-b980ac481840

FINAL TEST | BNBUSDT_1d | acc=0.4508 | f1=0.4496
    Desbalanceo reales      : {1: 0.5191256830601093, 0: 0.4808743169398907}
    Desbalanceo predicciones: {1: 0.5273224043715847, 0: 0.4726775956284153}
    Pesos promedio entrenamiento: {0: 1.039426523297491, 1: 0.9634551495016611}

[I 2025-06-19 16:58:45,169] Trial 0 finished with value: 0.49546286399267636 and parameters: {'n_estimators': 69, 'learning_rate': 0.07160285860259007, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.49546286399267636.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5042 | avg_f1=0.4955
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.5925925925925926, 1: 0.4074074074074074}

[I 2025-06-19 16:59:10,854] Trial 1 finished with value: 0.4919523767211203 and parameters: {'n_estimators': 210, 'learning_rate': 0.06406814734057398, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.49546286399267636.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5000 | avg_f1=0.4920
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6296296296296297, 1: 0.37037037037037035}

[I 2025-06-19 16:59:13,629] Trial 2 finished with value: 0.4926296112332039 and parameters: {'n_estimators': 63, 'learning_rate': 0.024167141057505916, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.49546286399267636.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5294 | avg_f1=0.4926
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 16:59:53,170] Trial 3 finished with value: 0.5191964213861615 and parameters: {'n_estimators': 312, 'learning_rate': 0.10127048027469787, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 3}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5272 | avg_f1=0.5192
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 17:00:39,532] Trial 4 finished with value: 0.5087877437454804 and parameters: {'n_estimators': 429, 'learning_rate': 0.002987807014031026, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 20}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5133 | avg_f1=0.5088
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6296296296296297, 1: 0.37037037037037035}

[I 2025-06-19 17:00:49,877] Trial 5 finished with value: 0.46276601653554383 and parameters: {'n_estimators': 237, 'learning_rate': 0.0062999758647974856, 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4975 | avg_f1=0.4628
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 17:01:07,622] Trial 6 finished with value: 0.5090505507800405 and parameters: {'n_estimators': 168, 'learning_rate': 0.0029249541459057337, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 14}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5138 | avg_f1=0.5091
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 17:01:34,542] Trial 7 finished with value: 0.5101490167494542 and parameters: {'n_estimators': 486, 'learning_rate': 0.07176524136704175, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 12}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5163 | avg_f1=0.5101
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 17:02:16,908] Trial 8 finished with value: 0.4899259125689383 and parameters: {'n_estimators': 267, 'learning_rate': 0.01387343814669501, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 8}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5002 | avg_f1=0.4899
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 17:02:53,524] Trial 9 finished with value: 0.47710091219048956 and parameters: {'n_estimators': 242, 'learning_rate': 0.18014064018124964, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.5191964213861615.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4830 | avg_f1=0.4771
    Desbalanceo reales (val)      : {1: 0.5802469135802469, 0: 0.41975308641975306}
    Desbalanceo predicciones (val): {0: 0.6419753086419753, 1: 0.35802469135802467}
Mejores parámetros para SOLUSDT_1d: {'n_estimators': 312, 'learning_rate': 0.10127048027469787, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 3}

[I 2025-06-19 17:03:04,122] A new study created in memory with name: no-name-6fa7e025-efb2-440d-ac6a-073c18d3fae9

FINAL TEST | SOLUSDT_1d | acc=0.4754 | f1=0.4714
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {0: 0.6010928961748634, 1: 0.3989071038251366}
    Pesos promedio entrenamiento: {0: 0.9982788296041308, 1: 1.001727115716753}

[I 2025-06-19 17:03:27,656] Trial 0 finished with value: 0.4809296503954871 and parameters: {'n_estimators': 412, 'learning_rate': 0.002220146094019813, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.4809296503954871.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5264 | avg_f1=0.4809
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 17:04:08,942] Trial 1 finished with value: 0.46316401691158315 and parameters: {'n_estimators': 394, 'learning_rate': 0.012374921441698451, 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.4809296503954871.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4993 | avg_f1=0.4632
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.7530864197530864, 1: 0.24691358024691357}

[I 2025-06-19 17:04:15,685] Trial 2 finished with value: 0.501788430620544 and parameters: {'n_estimators': 70, 'learning_rate': 0.29458579145309055, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5267 | avg_f1=0.5018
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.7160493827160493, 1: 0.2839506172839506}

[I 2025-06-19 17:04:28,740] Trial 3 finished with value: 0.4770999683849981 and parameters: {'n_estimators': 90, 'learning_rate': 0.009657083368758064, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5128 | avg_f1=0.4771
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 17:05:16,452] Trial 4 finished with value: 0.4626317429725278 and parameters: {'n_estimators': 394, 'learning_rate': 0.001965247086227351, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 15}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4983 | avg_f1=0.4626
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 17:05:28,638] Trial 5 finished with value: 0.49038005367503235 and parameters: {'n_estimators': 127, 'learning_rate': 0.2500144705243857, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5175 | avg_f1=0.4904
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 17:06:08,475] Trial 6 finished with value: 0.4725260682481955 and parameters: {'n_estimators': 338, 'learning_rate': 0.005464665953836257, 'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 13}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4980 | avg_f1=0.4725
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 17:06:25,673] Trial 7 finished with value: 0.49047601467070046 and parameters: {'n_estimators': 395, 'learning_rate': 0.030163719743797977, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.501788430620544.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5190 | avg_f1=0.4905
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {0: 0.7901234567901234, 1: 0.20987654320987653}

[I 2025-06-19 17:06:36,441] Trial 8 finished with value: 0.5173879423895242 and parameters: {'n_estimators': 187, 'learning_rate': 0.008141659156973282, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.5173879423895242.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5514 | avg_f1=0.5174
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5555555555555556, 0: 0.4444444444444444}

[I 2025-06-19 17:06:55,492] Trial 9 finished with value: 0.4870812693990879 and parameters: {'n_estimators': 434, 'learning_rate': 0.0037455094904473725, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.5173879423895242.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5274 | avg_f1=0.4871
    Desbalanceo reales (val)      : {1: 0.5925925925925926, 0: 0.4074074074074074}
    Desbalanceo predicciones (val): {1: 0.5061728395061729, 0: 0.49382716049382713}
Mejores parámetros para ADAUSDT_1d: {'n_estimators': 187, 'learning_rate': 0.008141659156973282, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 3}

[I 2025-06-19 17:06:58,369] A new study created in memory with name: no-name-7917adc4-2ac8-4ef9-9d98-a017fdec19fb

FINAL TEST | ADAUSDT_1d | acc=0.4973 | f1=0.4885
    Desbalanceo reales      : {0: 0.5081967213114754, 1: 0.4918032786885246}
    Desbalanceo predicciones: {0: 0.6229508196721312, 1: 0.3770491803278688}
    Pesos promedio entrenamiento: {0: 0.9982788296041308, 1: 1.001727115716753}

[I 2025-06-19 17:07:23,173] Trial 0 finished with value: 0.5342997474879937 and parameters: {'n_estimators': 452, 'learning_rate': 0.009270716509312977, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 17}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5393 | avg_f1=0.5343
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 17:07:54,155] Trial 1 finished with value: 0.513254437718923 and parameters: {'n_estimators': 363, 'learning_rate': 0.08990464924204859, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5170 | avg_f1=0.5133
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 17:08:03,785] Trial 2 finished with value: 0.5258789996180374 and parameters: {'n_estimators': 82, 'learning_rate': 0.00796487317159563, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5306 | avg_f1=0.5259
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 17:08:12,903] Trial 3 finished with value: 0.45503247160092525 and parameters: {'n_estimators': 77, 'learning_rate': 0.0019078406684469688, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4664 | avg_f1=0.4550
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5308641975308642, 1: 0.4691358024691358}

[I 2025-06-19 17:08:23,449] Trial 4 finished with value: 0.5160693837587031 and parameters: {'n_estimators': 90, 'learning_rate': 0.07452423264968, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 13}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5190 | avg_f1=0.5161
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 17:09:28,791] Trial 5 finished with value: 0.4793810303056197 and parameters: {'n_estimators': 443, 'learning_rate': 0.07342974852813162, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4830 | avg_f1=0.4794
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 17:10:34,568] Trial 6 finished with value: 0.53075752251562 and parameters: {'n_estimators': 438, 'learning_rate': 0.00398486040184502, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5398 | avg_f1=0.5308
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5432098765432098, 1: 0.4567901234567901}

[I 2025-06-19 17:11:26,967] Trial 7 finished with value: 0.4927300674945988 and parameters: {'n_estimators': 497, 'learning_rate': 0.05571312277843926, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4983 | avg_f1=0.4927
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5679012345679012, 1: 0.43209876543209874}

[I 2025-06-19 17:11:39,391] Trial 8 finished with value: 0.4897727761109284 and parameters: {'n_estimators': 281, 'learning_rate': 0.001829650866716279, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.5342997474879937.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5015 | avg_f1=0.4898
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 17:11:53,152] Trial 9 finished with value: 0.5349539073087681 and parameters: {'n_estimators': 102, 'learning_rate': 0.0014899372345124316, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 2}. Best is trial 9 with value: 0.5349539073087681.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5472 | avg_f1=0.5350
    Desbalanceo reales (val)      : {1: 0.6419753086419753, 0: 0.35802469135802467}
    Desbalanceo predicciones (val): {0: 0.5185185185185185, 1: 0.48148148148148145}
Mejores parámetros para TRXUSDT_1d: {'n_estimators': 102, 'learning_rate': 0.0014899372345124316, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 2}

[I 2025-06-19 17:11:56,911] A new study created in memory with name: no-name-92b44af4-f052-4de3-a55d-e7f195bae35b

FINAL TEST | TRXUSDT_1d | acc=0.4727 | f1=0.4698
    Desbalanceo reales      : {1: 0.5327868852459017, 0: 0.4672131147540984}
    Desbalanceo predicciones: {1: 0.5409836065573771, 0: 0.45901639344262296}
    Pesos promedio entrenamiento: {0: 1.0902255639097744, 1: 0.9235668789808917}

[I 2025-06-19 17:12:00,340] Trial 0 finished with value: 0.4785838634171967 and parameters: {'n_estimators': 75, 'learning_rate': 0.015180142820393844, 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.4785838634171967.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4953 | avg_f1=0.4786
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.691358024691358, 1: 0.30864197530864196}

[I 2025-06-19 17:12:29,829] Trial 1 finished with value: 0.45861120005173833 and parameters: {'n_estimators': 213, 'learning_rate': 0.01552472485485889, 'max_depth': 15, 'min_samples_split': 13, 'min_samples_leaf': 17}. Best is trial 0 with value: 0.4785838634171967.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4743 | avg_f1=0.4586
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7654320987654321, 1: 0.2345679012345679}

[I 2025-06-19 17:12:37,809] Trial 2 finished with value: 0.4592096629535633 and parameters: {'n_estimators': 185, 'learning_rate': 0.21657274247116118, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.4785838634171967.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4664 | avg_f1=0.4592
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-19 17:12:50,882] Trial 3 finished with value: 0.4729055512232702 and parameters: {'n_estimators': 132, 'learning_rate': 0.0018396026354280995, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 18}. Best is trial 0 with value: 0.4785838634171967.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4862 | avg_f1=0.4729
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6049382716049383, 1: 0.3950617283950617}

[I 2025-06-19 17:13:12,465] Trial 4 finished with value: 0.47389853067701504 and parameters: {'n_estimators': 218, 'learning_rate': 0.004571531297092482, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 11}. Best is trial 0 with value: 0.4785838634171967.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4847 | avg_f1=0.4739
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}

[I 2025-06-19 17:13:47,886] Trial 5 finished with value: 0.48066002673534014 and parameters: {'n_estimators': 267, 'learning_rate': 0.10026043603752051, 'max_depth': 11, 'min_samples_split': 17, 'min_samples_leaf': 7}. Best is trial 5 with value: 0.48066002673534014.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4881 | avg_f1=0.4807
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7037037037037037, 1: 0.2962962962962963}

[I 2025-06-19 17:14:12,581] Trial 6 finished with value: 0.456495628263829 and parameters: {'n_estimators': 167, 'learning_rate': 0.0621856247278622, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 15}. Best is trial 5 with value: 0.48066002673534014.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4640 | avg_f1=0.4565
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.7283950617283951, 1: 0.2716049382716049}

[I 2025-06-19 17:14:22,533] Trial 7 finished with value: 0.5261713053090957 and parameters: {'n_estimators': 170, 'learning_rate': 0.001221424316415307, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.5261713053090957.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5415 | avg_f1=0.5262
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 17:14:57,415] Trial 8 finished with value: 0.48924582653222615 and parameters: {'n_estimators': 246, 'learning_rate': 0.07442239578664298, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.5261713053090957.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4938 | avg_f1=0.4892
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.5802469135802469, 1: 0.41975308641975306}

[I 2025-06-19 17:15:06,082] Trial 9 finished with value: 0.48142641140405484 and parameters: {'n_estimators': 102, 'learning_rate': 0.1451334700329175, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 7 with value: 0.5261713053090957.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4909 | avg_f1=0.4814
    Desbalanceo reales (val)      : {1: 0.6049382716049383, 0: 0.3950617283950617}
    Desbalanceo predicciones (val): {0: 0.6172839506172839, 1: 0.38271604938271603}
Mejores parámetros para LINKUSDT_1d: {'n_estimators': 170, 'learning_rate': 0.001221424316415307, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2}

[I 2025-06-19 17:15:08,727] A new study created in memory with name: no-name-7150e3a2-6bb1-4d64-8ef8-6db639500bc1

FINAL TEST | LINKUSDT_1d | acc=0.5410 | f1=0.5315
    Desbalanceo reales      : {0: 0.5109289617486339, 1: 0.4890710382513661}
    Desbalanceo predicciones: {0: 0.6311475409836066, 1: 0.36885245901639346}
    Pesos promedio entrenamiento: {0: 1.0507246376811594, 1: 0.9539473684210527}

[I 2025-06-19 17:15:15,528] Trial 0 finished with value: 0.49517279078661575 and parameters: {'n_estimators': 67, 'learning_rate': 0.014126214084377137, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.49517279078661575.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5025 | avg_f1=0.4952
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5308641975308642, 0: 0.4691358024691358}

[I 2025-06-19 17:15:29,992] Trial 1 finished with value: 0.4788252880030216 and parameters: {'n_estimators': 96, 'learning_rate': 0.06535764750720442, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.49517279078661575.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5040 | avg_f1=0.4788
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5802469135802469, 0: 0.41975308641975306}

[I 2025-06-19 17:15:52,690] Trial 2 finished with value: 0.5205134514630936 and parameters: {'n_estimators': 415, 'learning_rate': 0.0016009859632752955, 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 17}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5338 | avg_f1=0.5205
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.654320987654321, 1: 0.345679012345679}

[I 2025-06-19 17:16:14,311] Trial 3 finished with value: 0.5018708137896741 and parameters: {'n_estimators': 144, 'learning_rate': 0.04319741516002196, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5089 | avg_f1=0.5019
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}

[I 2025-06-19 17:16:35,557] Trial 4 finished with value: 0.49889500462204206 and parameters: {'n_estimators': 186, 'learning_rate': 0.015762660350826532, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 16}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5126 | avg_f1=0.4989
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5925925925925926, 0: 0.4074074074074074}

[I 2025-06-19 17:17:38,502] Trial 5 finished with value: 0.505473452142558 and parameters: {'n_estimators': 433, 'learning_rate': 0.04798389958255271, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5133 | avg_f1=0.5055
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}

[I 2025-06-19 17:18:06,188] Trial 6 finished with value: 0.4642866174224968 and parameters: {'n_estimators': 180, 'learning_rate': 0.23733357751507014, 'max_depth': 13, 'min_samples_split': 11, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4832 | avg_f1=0.4643
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {1: 0.5432098765432098, 0: 0.4567901234567901}

[I 2025-06-19 17:18:29,310] Trial 7 finished with value: 0.5023121115752742 and parameters: {'n_estimators': 214, 'learning_rate': 0.032041749148780066, 'max_depth': 9, 'min_samples_split': 14, 'min_samples_leaf': 13}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5136 | avg_f1=0.5023
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5185185185185185, 1: 0.48148148148148145}

[I 2025-06-19 17:18:42,092] Trial 8 finished with value: 0.5021498043985873 and parameters: {'n_estimators': 89, 'learning_rate': 0.24370323804113014, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 17}. Best is trial 2 with value: 0.5205134514630936.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5067 | avg_f1=0.5021
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5308641975308642, 1: 0.4691358024691358}

[I 2025-06-19 17:19:01,153] Trial 9 finished with value: 0.5244904503191566 and parameters: {'n_estimators': 448, 'learning_rate': 0.00426249212836864, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 16}. Best is trial 9 with value: 0.5244904503191566.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5351 | avg_f1=0.5245
    Desbalanceo reales (val)      : {1: 0.6790123456790124, 0: 0.32098765432098764}
    Desbalanceo predicciones (val): {0: 0.5555555555555556, 1: 0.4444444444444444}
Mejores parámetros para AVAXUSDT_1d: {'n_estimators': 448, 'learning_rate': 0.00426249212836864, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 16}

FINAL TEST | AVAXUSDT_1d | acc=0.4590 | f1=0.4590
    Desbalanceo reales      : {0: 0.5382513661202186, 1: 0.46174863387978143}
    Desbalanceo predicciones: {1: 0.5273224043715847, 0: 0.4726775956284153}
    Pesos promedio entrenamiento: {0: 1.0193321616871704, 1: 0.9813874788494078}


=== Mejores hiperparámetros por modelo ===
MLPClassifier: {'BTCUSDT_1d': {'hidden_layer_sizes': 644, 'alpha': 1.685101766461613e-05, 'learning_rate_init': 0.0006947816061138453}, 'ETHUSDT_1d': {'hidden_layer_sizes': 443, 'alpha': 0.03380907883949562, 'learning_rate_init': 0.009102295028086254}, 'XRPUSDT_1d': {'hidden_layer_sizes': 931, 'alpha': 0.0008199579046277004, 'learning_rate_init': 9.355649550156621e-05}, 'BNBUSDT_1d': {'hidden_layer_sizes': 288, 'alpha': 2.8766619570539803e-05, 'learning_rate_init': 2.012427401383467e-05}, 'SOLUSDT_1d': {'hidden_layer_sizes': 477, 'alpha': 0.00011297916019200704, 'learning_rate_init': 0.0015894267833312479}, 'ADAUSDT_1d': {'hidden_layer_sizes': 816, 'alpha': 0.00016549718057062938, 'learning_rate_init': 7.870628549615475e-05}, 'TRXUSDT_1d': {'hidden_layer_sizes': 67, 'alpha': 7.680797496517063e-05, 'learning_rate_init': 0.0010034371402836049}, 'LINKUSDT_1d': {'hidden_layer_sizes': 126, 'alpha': 0.016233369781977244, 'learning_rate_init': 0.0002414855010232573}, 'AVAXUSDT_1d': {'hidden_layer_sizes': 254, 'alpha': 0.007042361546127741, 'learning_rate_init': 0.00019733391461600492}}
RandomForestClassifier: {'BTCUSDT_1d': {'n_estimators': 440, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}, 'ETHUSDT_1d': {'n_estimators': 535, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}, 'XRPUSDT_1d': {'n_estimators': 824, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}, 'BNBUSDT_1d': {'n_estimators': 708, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}, 'SOLUSDT_1d': {'n_estimators': 554, 'max_depth': 29, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}, 'ADAUSDT_1d': {'n_estimators': 495, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False}, 'TRXUSDT_1d': {'n_estimators': 258, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}, 'LINKUSDT_1d': {'n_estimators': 626, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}, 'AVAXUSDT_1d': {'n_estimators': 448, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}}
GradientBoostingClassifier: {'BTCUSDT_1d': {'n_estimators': 363, 'learning_rate': 0.25694353076008025, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 10}, 'ETHUSDT_1d': {'n_estimators': 150, 'learning_rate': 0.023730573038819983, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 14}, 'XRPUSDT_1d': {'n_estimators': 383, 'learning_rate': 0.0972067637641204, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5}, 'BNBUSDT_1d': {'n_estimators': 294, 'learning_rate': 0.002469004274286109, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 5}, 'SOLUSDT_1d': {'n_estimators': 312, 'learning_rate': 0.10127048027469787, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 3}, 'ADAUSDT_1d': {'n_estimators': 187, 'learning_rate': 0.008141659156973282, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 3}, 'TRXUSDT_1d': {'n_estimators': 102, 'learning_rate': 0.0014899372345124316, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 2}, 'LINKUSDT_1d': {'n_estimators': 170, 'learning_rate': 0.001221424316415307, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2}, 'AVAXUSDT_1d': {'n_estimators': 448, 'learning_rate': 0.00426249212836864, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 16}}