In [1]:
# Parameters
frequency = "1d"
window_pred = 7

In [2]:
import numpy as np
import pandas as pd
from pylab import plt
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score
import os
import talib as ta
import optuna
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.utils.class_weight import compute_sample_weight

# Frecuencia obtenida desde el main
try:
    print(f"Frecuencia recibida desde papermill: {frequency}")
except NameError:
    print(f"No se recibió 'frequency'.")


# Cargar los datos para esta frecuencia de un archivo creado por el main
file_name = f"processed_data_{frequency}_charac.csv"
data = pd.read_csv(file_name, index_col='timestamp')
data

C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Frecuencia recibida desde papermill: 1d

,BTCUSDT_1d,ETHUSDT_1d,XRPUSDT_1d,BNBUSDT_1d,SOLUSDT_1d,ADAUSDT_1d,TRXUSDT_1d,LINKUSDT_1d,AVAXUSDT_1d
timestamp,,,,,,,,,
2020-09-22,10529.61,344.21,0.23302,24.0468,2.9082,0.08146,0.02499,8.7401,5.3193
2020-09-23,10241.46,320.72,0.22164,22.8331,2.8548,0.07663,0.02486,7.6364,3.5350
2020-09-24,10736.32,348.97,0.23276,24.5745,3.1433,0.08254,0.02625,9.8700,4.6411
2020-09-25,10686.67,351.92,0.24154,24.6924,3.1937,0.09693,0.02714,10.7279,4.7134
2020-09-26,10728.60,353.92,0.24153,26.1998,3.1287,0.09547,0.02718,10.3169,4.5200
...,...,...,...,...,...,...,...,...,...
2024-12-28,95300.00,3404.00,2.18430,722.1300,195.5000,0.88950,0.25840,21.9900,37.7400
2024-12-29,93738.20,3356.48,2.09420,694.7100,189.9400,0.85900,0.25780,20.9600,35.8400
2024-12-30,92792.05,3361.84,2.05870,705.3600,191.3800,0.86150,0.25340,20.5800,35.9700
2024-12-31,93576.00,3337.78,2.08360,702.3000,189.3100,0.84510,0.25480,20.0100,35.7100
2025-01-01,94591.79,3360.38,2.33280,707.8400,194.2800,0.92220,0.25590,21.7300,37.7800

Función para guardar los datos. Hace un archivo por cada frecuencia. Guarda en cada línea el modelo que se ha empleado, el activo, accuracy e in/out-sample.

In [3]:
def save_results(model, ric, acc, sample, frequency=frequency):
    # Verificar si el archivo ya existe
    file_name = f'results_{frequency}_charac.csv'

    # Si el archivo existe, leer los datos previos, si no, crear un nuevo DataFrame vacío
    if os.path.exists(file_name):
        df_results = pd.read_csv(file_name)
    else:
        df_results = pd.DataFrame(columns=['Model', 'Asset', 'Value', 'What'])

    # Agregar la nueva fila con los resultados
    new_row = pd.DataFrame([[model, ric, acc, sample]], columns=['Model', 'Asset', 'Value', 'What'])
    df_results = pd.concat([df_results, new_row], ignore_index=True)

    # Guardar los resultados acumulados
    df_results.to_csv(file_name, index=False)

Creamos las características que usaremos para hacer el aprendizaje ahora y las retardamos.

In [4]:
def charact_lags(data, ric, lags, window_pred, window=30):
    cols = []
    df = pd.DataFrame(data[ric])
    df['r'] = np.log(df / df.shift()) #retornos
    df['sma'] = df[ric].rolling(window).mean()  #media movil de la ventana
    df['min'] = df[ric].rolling(window).min() #mínimo de la ventana
    df['max'] = df[ric].rolling(window).max() #máximo de la ventana
    df['mom'] = df[ric].pct_change(window) #momentum de la ventana pct_change(12)
    df['vol'] = df['r'].rolling(window).std() #volatilidad de la ventana
    df['rsi'] = ta.RSI(df[ric], timeperiod=window) #rsi de la ventana
    df['atr'] = ta.ATR(df[ric], df[ric], df[ric], timeperiod=window) #atr de la ventana
    df = df.iloc[:-window_pred]
    df['d'] = np.where(df[ric].shift(-window_pred) > df[ric], 1, 0) # columna binaria, 0 si los precios bajarán, 1 si subirán
    features = [ric, 'r', 'sma', 'min', 'max', 'mom', 'vol', 'rsi', 'atr']
    for f in features:
        for lag in range(1, lags + 1):
            col = f'{f}_lag_{lag}'
            df[col] = df[f].shift(lag)
            cols.append(col)
    return df, cols

lags = 5

dfs = {}
results = []
for ric in data:
    df, cols = charact_lags(data, ric, lags, window_pred)
    dfs[ric] = df, cols
    p = df['d'].value_counts(normalize=True) 
    results.append({
        'ric': ric,
        '0': p[0],
        '1': p[1]}
        )
results_df = pd.DataFrame(results)
results_df

           ric         0         1
0   BTCUSDT_1d  0.459512  0.540488
1   ETHUSDT_1d  0.470437  0.529563
2   XRPUSDT_1d  0.517995  0.482005
3   BNBUSDT_1d  0.468509  0.531491
4   SOLUSDT_1d  0.493573  0.506427
5   ADAUSDT_1d  0.521851  0.478149
6   TRXUSDT_1d  0.427378  0.572622
7  LINKUSDT_1d  0.487789  0.512211
8  AVAXUSDT_1d  0.514139  0.485861

In [5]:
def normalize_with_close(X, close_col):
    """
    Normaliza columnas ratio en función del precio de cierre.
    """
    ratio_cols = [col for col in X.columns if any(x in col for x in ['sma','atr','min','max'])]
    for col in ratio_cols:
        X[col] = X[col] / close_col
    return X

# ---------------------------------------------------
def prepare_features(df):
    """
    One-hot encoding de la columna 'crypto'.
    """
    crypto_dummies = pd.get_dummies(df['crypto'], prefix='crypto')
    X = pd.concat([df.drop(columns=['crypto']), crypto_dummies], axis=1)
    return X, crypto_dummies.columns

# ---------------------------------------------------

In [6]:
def walk_forward_fit_test(model_class, freq, model_params={}, n_trials=5, search_space=None, data=data):
    if freq == '1h':
        period = pd.Timedelta(days=14)
    elif freq == '4h':
        period = pd.Timedelta(days=30)
    else:
        period = pd.Timedelta(days=180)
    final_test_period = pd.Timedelta(days=365)

    def suggest_params(trial):
        trial_params = {}
        for param_name, param_info in search_space.items():
            if param_info['type'] == 'int':
                trial_params[param_name] = trial.suggest_int(param_name, *param_info['bounds'])
            elif param_info['type'] == 'float':
                trial_params[param_name] = trial.suggest_float(param_name, *param_info['bounds'], log=param_info.get('log', False))
            elif param_info['type'] == 'categorical':
                trial_params[param_name] = trial.suggest_categorical(param_name, param_info['choices'])
        trial_params.update(model_params)
        return trial_params

    ric_best_params = {}
    desb_graf = []
    df_res = None

    for ric in data:
        df, cols = data[ric]
        df = df[cols + ['d']].copy()
        df.dropna(inplace=True)
        df['timestamp'] = pd.to_datetime(df.index)
        max_time = df['timestamp'].max()
        cutoff = max_time - final_test_period
        df_trainval = df[df['timestamp'] < cutoff].copy()

        # Generar fechas de split
        min_time = df_trainval['timestamp'].min()
        split_dates = []
        current_time = min_time + period
        while current_time < cutoff:
            split_dates.append(current_time)
            current_time += period
        split_dates = split_dates[-5:]

        def objective(trial):
            trial_params = suggest_params(trial)
            resul_acc = []
            resul_f1 = []

            for split_date in split_dates:
                train = df_trainval[df_trainval['timestamp'] < (split_date - pd.Timedelta(days=window_pred))]
                test = df_trainval[(df_trainval['timestamp'] >= split_date) & (df_trainval['timestamp'] < split_date + period)]
                if len(test) == 0:
                    continue

                X_train, y_train = train.drop(columns=['d', 'timestamp']), train['d']
                X_test, y_test = test.drop(columns=['d', 'timestamp']), test['d']
                X_train = normalize_with_close(X_train.copy(), train[f'{ric}_lag_1'])
                X_test = normalize_with_close(X_test.copy(), test[f'{ric}_lag_1'])

                model = model_class(**trial_params)
                if model_class.__name__ == 'MLPClassifier':
                    X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
                    X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
                    model.fit(X_train, y_train)
                else:
                    weights = compute_sample_weight(class_weight='balanced', y=y_train)
                    X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
                    X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
                    model.fit(X_train, y_train, sample_weight=weights)

                pred = np.where(model.predict(X_test) > 0.5, 1, 0)
                f1 = f1_score(y_test, pred, average='macro')
                acc = accuracy_score(y_test, pred)
                resul_acc.append(acc)
                resul_f1.append(f1)

            avg_f1 = np.mean(resul_f1)
            avg_acc = np.mean(resul_acc)
            dist_true = y_test.value_counts(normalize=True).to_dict()
            dist_pred = pd.Series(pred).value_counts(normalize=True).to_dict()
            print(f'VALIDATION |  {ric:7s} | avg_acc={avg_acc:.4f} | avg_f1={avg_f1:.4f}')
            save_results(model_class.__name__, ric, avg_f1, 'F1 VALIDATION', frequency=freq)
            print(f"    Desbalanceo reales (val)      : {dist_true}")
            print(f"    Desbalanceo predicciones (val): {dist_pred}")
            save_results(model_class.__name__, ric, dist_true, 'DESBALANCEO REAL VAL', frequency=freq)
            save_results(model_class.__name__, ric, dist_pred, 'DESBALANCEO PREDICCIÓN VAL', frequency=freq)
            return avg_f1

        study = optuna.create_study(direction="maximize")
        study.optimize(objective, n_trials=n_trials, n_jobs=1)

        best_params = study.best_params
        ric_best_params[ric] = best_params
        print(f"Mejores parámetros para {ric}: {best_params}")

        # Test final con los mejores parámetros
        df_test = df[df['timestamp'] >= cutoff].copy()
        train = df[df['timestamp'] < (cutoff - pd.Timedelta(days=window_pred))]
        test = df_test

        if len(test) == 0:
            continue

        X_train, y_train = train.drop(columns=['d', 'timestamp']), train['d']
        X_test, y_test = test.drop(columns=['d', 'timestamp']), test['d']

        X_train = normalize_with_close(X_train.copy(), train[f'{ric}_lag_1'])
        X_test = normalize_with_close(X_test.copy(), test[f'{ric}_lag_1'])

        model = model_class(**best_params)
        if model_class.__name__ == 'MLPClassifier':
            X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
            X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
            model.fit(X_train, y_train)
        else:
            weights = compute_sample_weight(class_weight='balanced', y=y_train)
            X_train = X_train.loc[:, ~X_train.columns.str.contains(ric)]
            X_test = X_test.loc[:, ~X_test.columns.str.contains(ric)]
            model.fit(X_train, y_train, sample_weight=weights)

        pred = np.where(model.predict(X_test) > 0.5, 1, 0)
        df_res = pd.DataFrame({'true': y_test, 'pred': pred})
        acc = accuracy_score(y_test, pred)
        f1 = f1_score(y_test, pred, average='macro')
        dist_true = y_test.value_counts(normalize=True).to_dict()
        dist_pred = pd.Series(pred).value_counts(normalize=True).to_dict()
        real_0 = dist_true.get(0, 0)
        real_1 = dist_true.get(1, 0)
        pred_0 = dist_pred.get(0, 0)
        pred_1 = dist_pred.get(1, 0)

        desb_graf.append({
            "cripto": ric,
            "acc": acc,
            "f1": f1,
            "real_0": real_0,
            "real_1": real_1,
            "pred_0": pred_0,
            "pred_1": pred_1
        })
        print(f'FINAL TEST | {ric:7s} | acc={acc:.4f} | f1={f1:.4f}')
        print(f"    Desbalanceo reales      : {dist_true}")
        print(f"    Desbalanceo predicciones: {dist_pred}")
        save_results(model_class.__name__, ric, acc, 'FINAL TEST', frequency=freq)
        save_results(model_class.__name__, ric, f1, 'F1 FINAL TEST', frequency=freq)
        save_results(model_class.__name__, ric, dist_true, 'DESBALANCEO REAL', frequency=freq)
        save_results(model_class.__name__, ric, dist_pred, 'DESBALANCEO PREDICCIÓN', frequency=freq)

        if model_class.__name__ != 'MLPClassifier':
            df_weights = pd.DataFrame({'y': y_train, 'weight': weights})
            avg_weights = df_weights.groupby('y')['weight'].mean().to_dict()
            print(f"    Pesos promedio entrenamiento: {avg_weights}")

    return ric_best_params, desb_graf, df_res

In [7]:
# === Definición del espacio de búsqueda para cada modelo ===

search_spaces = {
    "MLPClassifier": {
        "hidden_layer_sizes": {"type": "int",   "bounds": (32, 1024), "step": 32},
        "alpha":              {"type": "float", "bounds": (1e-6, 1e-1), "log": True},
        "learning_rate_init": {"type": "float", "bounds": (1e-5, 1e-1), "log": True},
    },
    "RandomForestClassifier": {
        "n_estimators":      {"type": "int",         "bounds": (100, 1000), "step": 100},
        "max_depth":         {"type": "int",         "bounds": (3,   30)},
        "min_samples_split": {"type": "int",         "bounds": (2,   10)},
        "min_samples_leaf":  {"type": "int",         "bounds": (1,   10)},
        "max_features":      {"type": "categorical", "choices": ["sqrt", "log2", None]},
        "bootstrap":         {"type": "categorical", "choices": [True, False]},
    },
    "GradientBoostingClassifier": {
        "n_estimators":      {"type": "int",   "bounds": (50, 500),  "step": 50},
        "learning_rate":     {"type": "float", "bounds": (1e-3, 0.3), "log": True},
        "max_depth":         {"type": "int",   "bounds": (3,   15)},
        "min_samples_split": {"type": "int",   "bounds": (2,   20)},
        "min_samples_leaf":  {"type": "int",   "bounds": (1,   20)},
    },
}

# === Parámetros fijos para cada modelo ===

model_fixed_params = {
    "MLPClassifier": {
        "max_iter": 1000,
        "early_stopping": True,
        "validation_fraction": 0.15,
        "shuffle": False,
        "random_state": 100,
    },
    "RandomForestClassifier": {
        "random_state": 100,
        "n_jobs": -1
    },
    "GradientBoostingClassifier": {
        "random_state": 100
    }
}

# === Diccionario de clases de modelos ===

model_classes = {
    "MLPClassifier": MLPClassifier,
    "RandomForestClassifier": RandomForestClassifier,
    "GradientBoostingClassifier": GradientBoostingClassifier
}

# === Entrenamiento en bucle ===

best_params_dict = {}
desb_graf_dict = {}
data_graf_dict = {}

for model_name, model_cls in model_classes.items():
    print(f"\n\n=== Entrenando modelo: {model_name} ===\n")
    
    best_params, desb_graf, df_res = walk_forward_fit_test(
        model_class=model_cls,
        freq=frequency,
        search_space=search_spaces[model_name],
        model_params=model_fixed_params.get(model_name, {}),
        n_trials=10,
        data=dfs  
    )

    best_params_dict[model_name] = best_params
    desb_graf_dict[model_name] = desb_graf
    data_graf_dict[model_name] = df_res

print("\n\n=== Mejores hiperparámetros por modelo ===")
for model_name, params in best_params_dict.items():
    print(f"{model_name}: {params}")

[I 2025-06-21 23:23:49,502] A new study created in memory with name: no-name-2044e301-d635-4f7a-8374-35828ec43148

=== Entrenando modelo: MLPClassifier ===

C:\Users\Usuario\AppData\Local\Temp\ipykernel_28352\484775197.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_results = pd.concat([df_results, new_row], ignore_index=True)
[I 2025-06-21 23:23:49,958] Trial 0 finished with value: 0.4062979346824682 and parameters: {'hidden_layer_sizes': 256, 'alpha': 1.5228669653384426e-06, 'learning_rate_init': 0.0035443862837449013}. Best is trial 0 with value: 0.4062979346824682.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5216 | avg_f1=0.4063
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.9733333333333334, 0: 0.02666666666666667}

[I 2025-06-21 23:23:50,668] Trial 1 finished with value: 0.4073640338935808 and parameters: {'hidden_layer_sizes': 409, 'alpha': 0.0007962475712136327, 'learning_rate_init': 0.00017874129441204975}. Best is trial 1 with value: 0.4073640338935808.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4691 | avg_f1=0.4074
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.8133333333333334, 0: 0.18666666666666668}

[I 2025-06-21 23:23:51,129] Trial 2 finished with value: 0.35971982991423773 and parameters: {'hidden_layer_sizes': 568, 'alpha': 7.43748358414722e-05, 'learning_rate_init': 2.4936723658650974e-05}. Best is trial 1 with value: 0.4073640338935808.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5213 | avg_f1=0.3597
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:23:51,634] Trial 3 finished with value: 0.3578114150413969 and parameters: {'hidden_layer_sizes': 511, 'alpha': 0.019820349408048738, 'learning_rate_init': 0.002631259776691225}. Best is trial 1 with value: 0.4073640338935808.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4964 | avg_f1=0.3578
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.9866666666666667, 0: 0.013333333333333334}

[I 2025-06-21 23:23:52,267] Trial 4 finished with value: 0.42188160531292934 and parameters: {'hidden_layer_sizes': 630, 'alpha': 0.003734558398606376, 'learning_rate_init': 0.00011310251053281955}. Best is trial 4 with value: 0.42188160531292934.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5096 | avg_f1=0.4219
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.8533333333333334, 0: 0.14666666666666667}

[I 2025-06-21 23:23:53,511] Trial 5 finished with value: 0.37695316792920447 and parameters: {'hidden_layer_sizes': 1006, 'alpha': 9.762502005266996e-05, 'learning_rate_init': 0.0011291940177380624}. Best is trial 4 with value: 0.42188160531292934.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4924 | avg_f1=0.3770
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.9333333333333333, 0: 0.06666666666666667}

[I 2025-06-21 23:23:54,490] Trial 6 finished with value: 0.38505357012754343 and parameters: {'hidden_layer_sizes': 984, 'alpha': 0.0002407127367448175, 'learning_rate_init': 0.004808886967544357}. Best is trial 4 with value: 0.42188160531292934.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5329 | avg_f1=0.3851
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.9466666666666667, 0: 0.05333333333333334}

[I 2025-06-21 23:23:55,291] Trial 7 finished with value: 0.35366366002112837 and parameters: {'hidden_layer_sizes': 686, 'alpha': 3.45722556629648e-06, 'learning_rate_init': 0.005918395713073423}. Best is trial 4 with value: 0.42188160531292934.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4480 | avg_f1=0.3537
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}

[I 2025-06-21 23:23:56,021] Trial 8 finished with value: 0.4924063781228066 and parameters: {'hidden_layer_sizes': 788, 'alpha': 1.0434457704508487e-05, 'learning_rate_init': 4.541446876658177e-05}. Best is trial 8 with value: 0.4924063781228066.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5289 | avg_f1=0.4924
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.6266666666666667, 0: 0.37333333333333335}

[I 2025-06-21 23:23:56,472] Trial 9 finished with value: 0.33529007573135683 and parameters: {'hidden_layer_sizes': 414, 'alpha': 0.00021610643310021802, 'learning_rate_init': 0.003619522032208027}. Best is trial 8 with value: 0.4924063781228066.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4767 | avg_f1=0.3353
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {0: 0.8666666666666667, 1: 0.13333333333333333}
Mejores parámetros para BTCUSDT_1d: {'hidden_layer_sizes': 788, 'alpha': 1.0434457704508487e-05, 'learning_rate_init': 4.541446876658177e-05}

[I 2025-06-21 23:23:58,035] A new study created in memory with name: no-name-dd35475a-5886-4bb5-8516-7f5c92a81f53

FINAL TEST | BTCUSDT_1d | acc=0.5137 | f1=0.4275
    Desbalanceo reales      : {1: 0.5628415300546448, 0: 0.4371584699453552}
    Desbalanceo predicciones: {1: 0.825136612021858, 0: 0.17486338797814208}

[I 2025-06-21 23:23:58,536] Trial 0 finished with value: 0.34003890655492486 and parameters: {'hidden_layer_sizes': 383, 'alpha': 0.07839556470069503, 'learning_rate_init': 2.5047547740791738e-05}. Best is trial 0 with value: 0.34003890655492486.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4622 | avg_f1=0.3400
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.84, 1: 0.16}

[I 2025-06-21 23:23:58,911] Trial 1 finished with value: 0.3352210862923809 and parameters: {'hidden_layer_sizes': 484, 'alpha': 5.4431073115988735e-05, 'learning_rate_init': 1.5190704900088824e-05}. Best is trial 0 with value: 0.34003890655492486.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5140 | avg_f1=0.3352
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:23:59,650] Trial 2 finished with value: 0.36250938948044203 and parameters: {'hidden_layer_sizes': 672, 'alpha': 0.0753575736548526, 'learning_rate_init': 0.004148308981011985}. Best is trial 2 with value: 0.36250938948044203.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5069 | avg_f1=0.3625
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.9866666666666667, 0: 0.013333333333333334}

[I 2025-06-21 23:24:00,061] Trial 3 finished with value: 0.37011237548340115 and parameters: {'hidden_layer_sizes': 162, 'alpha': 2.1247113664119327e-05, 'learning_rate_init': 0.0002963666688042311}. Best is trial 3 with value: 0.37011237548340115.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5282 | avg_f1=0.3701
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}

[I 2025-06-21 23:24:00,821] Trial 4 finished with value: 0.3613312539359013 and parameters: {'hidden_layer_sizes': 804, 'alpha': 0.0001238297774206951, 'learning_rate_init': 0.00014270271374307593}. Best is trial 3 with value: 0.37011237548340115.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4780 | avg_f1=0.3613
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.84, 0: 0.16}

[I 2025-06-21 23:24:01,233] Trial 5 finished with value: 0.3352210862923809 and parameters: {'hidden_layer_sizes': 557, 'alpha': 1.8955150802980337e-05, 'learning_rate_init': 0.003658615230850003}. Best is trial 3 with value: 0.37011237548340115.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5140 | avg_f1=0.3352
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:01,898] Trial 6 finished with value: 0.43744451802474693 and parameters: {'hidden_layer_sizes': 498, 'alpha': 0.061769432132595385, 'learning_rate_init': 0.00012694296322331695}. Best is trial 6 with value: 0.43744451802474693.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5260 | avg_f1=0.4374
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.8, 0: 0.2}

[I 2025-06-21 23:24:02,292] Trial 7 finished with value: 0.3352210862923809 and parameters: {'hidden_layer_sizes': 635, 'alpha': 0.017581776044546898, 'learning_rate_init': 0.0627931833007525}. Best is trial 6 with value: 0.43744451802474693.

VALIDATION |  ETHUSDT_1d | avg_acc=0.5140 | avg_f1=0.3352
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:03,108] Trial 8 finished with value: 0.41164777446802214 and parameters: {'hidden_layer_sizes': 879, 'alpha': 0.004553143551556388, 'learning_rate_init': 5.159609964375971e-05}. Best is trial 6 with value: 0.43744451802474693.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4996 | avg_f1=0.4116
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.7733333333333333, 0: 0.22666666666666666}

[I 2025-06-21 23:24:03,408] Trial 9 finished with value: 0.38772617394295267 and parameters: {'hidden_layer_sizes': 49, 'alpha': 0.022376215696959044, 'learning_rate_init': 0.01914329332306066}. Best is trial 6 with value: 0.43744451802474693.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4980 | avg_f1=0.3877
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {1: 0.7066666666666667, 0: 0.29333333333333333}
Mejores parámetros para ETHUSDT_1d: {'hidden_layer_sizes': 498, 'alpha': 0.061769432132595385, 'learning_rate_init': 0.00012694296322331695}

[I 2025-06-21 23:24:04,121] A new study created in memory with name: no-name-af5c0fad-f8fa-481e-b325-6255fe2e8a5f

FINAL TEST | ETHUSDT_1d | acc=0.5000 | f1=0.4837
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {1: 0.6639344262295082, 0: 0.3360655737704918}

[I 2025-06-21 23:24:04,740] Trial 0 finished with value: 0.4336378184165344 and parameters: {'hidden_layer_sizes': 509, 'alpha': 0.0033488486838905594, 'learning_rate_init': 0.004916143310742104}. Best is trial 0 with value: 0.4336378184165344.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5267 | avg_f1=0.4336
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 0.8933333333333333, 1: 0.10666666666666667}

[I 2025-06-21 23:24:05,642] Trial 1 finished with value: 0.40993439011922767 and parameters: {'hidden_layer_sizes': 693, 'alpha': 6.950240234744715e-05, 'learning_rate_init': 7.936637077162343e-05}. Best is trial 0 with value: 0.4336378184165344.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5182 | avg_f1=0.4099
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 0.9866666666666667, 1: 0.013333333333333334}

[I 2025-06-21 23:24:06,069] Trial 2 finished with value: 0.32992522462994867 and parameters: {'hidden_layer_sizes': 588, 'alpha': 0.005812329399730552, 'learning_rate_init': 0.05530680368891807}. Best is trial 0 with value: 0.4336378184165344.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4967 | avg_f1=0.3299
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:06,513] Trial 3 finished with value: 0.4450513617552171 and parameters: {'hidden_layer_sizes': 331, 'alpha': 2.0857960583134598e-05, 'learning_rate_init': 3.676583542812448e-05}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4856 | avg_f1=0.4451
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:24:06,782] Trial 4 finished with value: 0.31706840912265494 and parameters: {'hidden_layer_sizes': 153, 'alpha': 0.004996810566597084, 'learning_rate_init': 1.9576695646189548e-05}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4678 | avg_f1=0.3171
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:07,431] Trial 5 finished with value: 0.33669656880143317 and parameters: {'hidden_layer_sizes': 632, 'alpha': 0.008017026236204008, 'learning_rate_init': 3.1908049684086245e-05}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4784 | avg_f1=0.3367
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 0.84, 1: 0.16}

[I 2025-06-21 23:24:08,130] Trial 6 finished with value: 0.3502836951467455 and parameters: {'hidden_layer_sizes': 786, 'alpha': 1.2332655774109436e-06, 'learning_rate_init': 3.535278298188375e-05}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4767 | avg_f1=0.3503
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:08,508] Trial 7 finished with value: 0.37164738475612413 and parameters: {'hidden_layer_sizes': 249, 'alpha': 0.006646187165988801, 'learning_rate_init': 0.011834420280779532}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4844 | avg_f1=0.3716
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:09,600] Trial 8 finished with value: 0.42307886060107885 and parameters: {'hidden_layer_sizes': 781, 'alpha': 2.1937949052068477e-06, 'learning_rate_init': 0.0012257706083078593}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4856 | avg_f1=0.4231
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:10,092] Trial 9 finished with value: 0.31706840912265494 and parameters: {'hidden_layer_sizes': 704, 'alpha': 6.165323021306464e-05, 'learning_rate_init': 1.2196034388142314e-05}. Best is trial 3 with value: 0.4450513617552171.

VALIDATION |  XRPUSDT_1d | avg_acc=0.4678 | avg_f1=0.3171
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para XRPUSDT_1d: {'hidden_layer_sizes': 331, 'alpha': 2.0857960583134598e-05, 'learning_rate_init': 3.676583542812448e-05}

[I 2025-06-21 23:24:11,170] A new study created in memory with name: no-name-2705f733-34f9-47d6-bc92-daa2aba8cbba

FINAL TEST | XRPUSDT_1d | acc=0.5301 | f1=0.5204
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {0: 0.6366120218579235, 1: 0.3633879781420765}

[I 2025-06-21 23:24:11,677] Trial 0 finished with value: 0.4084663307129202 and parameters: {'hidden_layer_sizes': 519, 'alpha': 0.028307931106857854, 'learning_rate_init': 0.0001280308368697097}. Best is trial 0 with value: 0.4084663307129202.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4976 | avg_f1=0.4085
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.8133333333333334, 0: 0.18666666666666668}

[I 2025-06-21 23:24:12,404] Trial 1 finished with value: 0.4469708702056834 and parameters: {'hidden_layer_sizes': 419, 'alpha': 2.695167048530188e-06, 'learning_rate_init': 6.543814148805816e-05}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5102 | avg_f1=0.4470
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.64, 0: 0.36}

[I 2025-06-21 23:24:12,799] Trial 2 finished with value: 0.3709028691222086 and parameters: {'hidden_layer_sizes': 201, 'alpha': 1.608711206236309e-05, 'learning_rate_init': 4.905121615293107e-05}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4527 | avg_f1=0.3709
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.6133333333333333, 1: 0.38666666666666666}

[I 2025-06-21 23:24:13,765] Trial 3 finished with value: 0.3773567392179931 and parameters: {'hidden_layer_sizes': 993, 'alpha': 1.4203831962413297e-06, 'learning_rate_init': 0.0005474122319037339}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5080 | avg_f1=0.3774
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.9066666666666666, 0: 0.09333333333333334}

[I 2025-06-21 23:24:14,019] Trial 4 finished with value: 0.3307895974319852 and parameters: {'hidden_layer_sizes': 77, 'alpha': 0.0163799840149024, 'learning_rate_init': 0.00035262113932844164}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5024 | avg_f1=0.3308
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:14,447] Trial 5 finished with value: 0.35882090993320953 and parameters: {'hidden_layer_sizes': 324, 'alpha': 0.0001454302190176073, 'learning_rate_init': 0.0005072118440083469}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4529 | avg_f1=0.3588
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.64, 0: 0.36}

[I 2025-06-21 23:24:15,066] Trial 6 finished with value: 0.35436376376104783 and parameters: {'hidden_layer_sizes': 795, 'alpha': 0.028131033583123872, 'learning_rate_init': 0.0003110324072879018}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5044 | avg_f1=0.3544
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.9466666666666667, 0: 0.05333333333333334}

[I 2025-06-21 23:24:15,399] Trial 7 finished with value: 0.3307895974319852 and parameters: {'hidden_layer_sizes': 266, 'alpha': 5.6597468070027216e-05, 'learning_rate_init': 0.05055270066623748}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5024 | avg_f1=0.3308
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:16,066] Trial 8 finished with value: 0.3784724736638516 and parameters: {'hidden_layer_sizes': 655, 'alpha': 0.005479658584499696, 'learning_rate_init': 0.0018890954250365903}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5069 | avg_f1=0.3785
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.8133333333333334, 0: 0.18666666666666668}

[I 2025-06-21 23:24:16,903] Trial 9 finished with value: 0.33445806251970156 and parameters: {'hidden_layer_sizes': 1014, 'alpha': 2.1432262306585602e-06, 'learning_rate_init': 0.005925182357884495}. Best is trial 1 with value: 0.4469708702056834.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4529 | avg_f1=0.3345
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.5333333333333333, 0: 0.4666666666666667}
Mejores parámetros para BNBUSDT_1d: {'hidden_layer_sizes': 419, 'alpha': 2.695167048530188e-06, 'learning_rate_init': 6.543814148805816e-05}

[I 2025-06-21 23:24:17,457] A new study created in memory with name: no-name-d0354388-47bc-478a-8e1a-76ef355f4ab8

FINAL TEST | BNBUSDT_1d | acc=0.5355 | f1=0.3488
    Desbalanceo reales      : {1: 0.5382513661202186, 0: 0.46174863387978143}
    Desbalanceo predicciones: {1: 0.9972677595628415, 0: 0.00273224043715847}

[I 2025-06-21 23:24:18,090] Trial 0 finished with value: 0.39278491326607473 and parameters: {'hidden_layer_sizes': 596, 'alpha': 0.03319851732138267, 'learning_rate_init': 0.007976605075587133}. Best is trial 0 with value: 0.39278491326607473.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5358 | avg_f1=0.3928
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.7866666666666666, 0: 0.21333333333333335}

[I 2025-06-21 23:24:18,517] Trial 1 finished with value: 0.40283269731399524 and parameters: {'hidden_layer_sizes': 202, 'alpha': 0.0003672501682445726, 'learning_rate_init': 8.125758531573719e-05}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.5411 | avg_f1=0.4028
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.6933333333333334, 1: 0.30666666666666664}

[I 2025-06-21 23:24:20,068] Trial 2 finished with value: 0.33987746077044517 and parameters: {'hidden_layer_sizes': 924, 'alpha': 1.1128261935125537e-05, 'learning_rate_init': 0.0014641952499579666}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.3833 | avg_f1=0.3399
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.8, 1: 0.2}

[I 2025-06-21 23:24:20,336] Trial 3 finished with value: 0.2662552725552222 and parameters: {'hidden_layer_sizes': 36, 'alpha': 4.049487330475286e-06, 'learning_rate_init': 0.09289229701691948}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.3771 | avg_f1=0.2663
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:20,700] Trial 4 finished with value: 0.32069749008959325 and parameters: {'hidden_layer_sizes': 65, 'alpha': 0.0006424937845537317, 'learning_rate_init': 0.0002835831184493068}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4053 | avg_f1=0.3207
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.84, 1: 0.16}

[I 2025-06-21 23:24:21,112] Trial 5 finished with value: 0.3388765797062664 and parameters: {'hidden_layer_sizes': 237, 'alpha': 0.0007023348346245662, 'learning_rate_init': 0.004954744081108628}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4791 | avg_f1=0.3389
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.92, 0: 0.08}

[I 2025-06-21 23:24:21,852] Trial 6 finished with value: 0.34427344557637185 and parameters: {'hidden_layer_sizes': 613, 'alpha': 0.000338921922963066, 'learning_rate_init': 0.0005938944135266027}. Best is trial 1 with value: 0.40283269731399524.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4547 | avg_f1=0.3443
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}

[I 2025-06-21 23:24:22,407] Trial 7 finished with value: 0.4076583177181744 and parameters: {'hidden_layer_sizes': 469, 'alpha': 4.283346357587249e-05, 'learning_rate_init': 1.0257359458276104e-05}. Best is trial 7 with value: 0.4076583177181744.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4744 | avg_f1=0.4077
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.7333333333333333, 0: 0.26666666666666666}

[I 2025-06-21 23:24:22,650] Trial 8 finished with value: 0.36381028880266025 and parameters: {'hidden_layer_sizes': 33, 'alpha': 0.003517154812579409, 'learning_rate_init': 0.00035588336136564594}. Best is trial 7 with value: 0.4076583177181744.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4542 | avg_f1=0.3638
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.6933333333333334, 0: 0.30666666666666664}
VALIDATION |  SOLUSDT_1d | avg_acc=0.4949 | avg_f1=0.3191

[I 2025-06-21 23:24:22,834] Trial 9 finished with value: 0.3191189133433415 and parameters: {'hidden_layer_sizes': 45, 'alpha': 1.1286709454060761e-06, 'learning_rate_init': 1.8120258747521184e-05}. Best is trial 7 with value: 0.4076583177181744.

    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 1.0}
Mejores parámetros para SOLUSDT_1d: {'hidden_layer_sizes': 469, 'alpha': 4.283346357587249e-05, 'learning_rate_init': 1.0257359458276104e-05}

[I 2025-06-21 23:24:23,829] A new study created in memory with name: no-name-a81af718-853f-4353-9498-111abb17d5fc

FINAL TEST | SOLUSDT_1d | acc=0.4372 | f1=0.4194
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {1: 0.6612021857923497, 0: 0.33879781420765026}

[I 2025-06-21 23:24:24,668] Trial 0 finished with value: 0.3527049622058186 and parameters: {'hidden_layer_sizes': 771, 'alpha': 0.00015203533595257147, 'learning_rate_init': 0.023412624199547764}. Best is trial 0 with value: 0.3527049622058186.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4322 | avg_f1=0.3527
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:25,110] Trial 1 finished with value: 0.4332407517112113 and parameters: {'hidden_layer_sizes': 516, 'alpha': 2.5266916794387685e-05, 'learning_rate_init': 7.73743653103505e-05}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5004 | avg_f1=0.4332
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.8266666666666667, 1: 0.17333333333333334}

[I 2025-06-21 23:24:25,427] Trial 2 finished with value: 0.36239877269720033 and parameters: {'hidden_layer_sizes': 142, 'alpha': 0.0005843913200497574, 'learning_rate_init': 0.0005896917216916218}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4222 | avg_f1=0.3624
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:25,869] Trial 3 finished with value: 0.331692555421369 and parameters: {'hidden_layer_sizes': 614, 'alpha': 0.000581019845460789, 'learning_rate_init': 2.0828386712220986e-05}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5189 | avg_f1=0.3317
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:26,405] Trial 4 finished with value: 0.35076168392269313 and parameters: {'hidden_layer_sizes': 316, 'alpha': 7.405558292649114e-06, 'learning_rate_init': 0.0006259769758129757}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4204 | avg_f1=0.3508
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.5866666666666667, 1: 0.41333333333333333}

[I 2025-06-21 23:24:26,879] Trial 5 finished with value: 0.3727988435911623 and parameters: {'hidden_layer_sizes': 470, 'alpha': 0.0013169789037394243, 'learning_rate_init': 0.0017659296726424366}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4078 | avg_f1=0.3728
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:27,718] Trial 6 finished with value: 0.4112553703267072 and parameters: {'hidden_layer_sizes': 685, 'alpha': 6.017938074782319e-06, 'learning_rate_init': 1.2064356562608093e-05}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5180 | avg_f1=0.4113
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.64, 0: 0.36}

[I 2025-06-21 23:24:28,399] Trial 7 finished with value: 0.3778975491181068 and parameters: {'hidden_layer_sizes': 562, 'alpha': 0.00022901587904499776, 'learning_rate_init': 0.0003632952531698046}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4618 | avg_f1=0.3779
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.52, 1: 0.48}

[I 2025-06-21 23:24:29,272] Trial 8 finished with value: 0.34518327756122763 and parameters: {'hidden_layer_sizes': 789, 'alpha': 9.954181857427736e-06, 'learning_rate_init': 0.0006662253512915903}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4953 | avg_f1=0.3452
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.84, 0: 0.16}

[I 2025-06-21 23:24:30,271] Trial 9 finished with value: 0.3799966092166415 and parameters: {'hidden_layer_sizes': 687, 'alpha': 0.030350015731515478, 'learning_rate_init': 0.0007814496994329734}. Best is trial 1 with value: 0.4332407517112113.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5404 | avg_f1=0.3800
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.8133333333333334, 0: 0.18666666666666668}
Mejores parámetros para ADAUSDT_1d: {'hidden_layer_sizes': 516, 'alpha': 2.5266916794387685e-05, 'learning_rate_init': 7.73743653103505e-05}

[I 2025-06-21 23:24:31,535] A new study created in memory with name: no-name-3a2cac89-2d9f-482d-b8f8-40b78785cfc3

FINAL TEST | ADAUSDT_1d | acc=0.5546 | f1=0.4717
    Desbalanceo reales      : {0: 0.5409836065573771, 1: 0.45901639344262296}
    Desbalanceo predicciones: {0: 0.855191256830601, 1: 0.1448087431693989}

[I 2025-06-21 23:24:32,342] Trial 0 finished with value: 0.42295717926405196 and parameters: {'hidden_layer_sizes': 677, 'alpha': 0.0009031036499283632, 'learning_rate_init': 0.0007968933178303263}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5620 | avg_f1=0.4230
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.9733333333333334, 0: 0.02666666666666667}

[I 2025-06-21 23:24:32,659] Trial 1 finished with value: 0.36274103551038717 and parameters: {'hidden_layer_sizes': 256, 'alpha': 0.018635279850681315, 'learning_rate_init': 1.757157903578656e-05}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5753 | avg_f1=0.3627
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:33,277] Trial 2 finished with value: 0.3838704413821533 and parameters: {'hidden_layer_sizes': 783, 'alpha': 2.237694687987622e-06, 'learning_rate_init': 0.006980020076704506}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5698 | avg_f1=0.3839
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:33,767] Trial 3 finished with value: 0.36274103551038717 and parameters: {'hidden_layer_sizes': 723, 'alpha': 3.531355813904102e-06, 'learning_rate_init': 0.08940875323030102}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5753 | avg_f1=0.3627
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:34,194] Trial 4 finished with value: 0.36274103551038717 and parameters: {'hidden_layer_sizes': 618, 'alpha': 9.715496368724361e-05, 'learning_rate_init': 1.1137811614972937e-05}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5753 | avg_f1=0.3627
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:34,970] Trial 5 finished with value: 0.37543011114063923 and parameters: {'hidden_layer_sizes': 927, 'alpha': 0.0009238705364842277, 'learning_rate_init': 0.002852324986886067}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5742 | avg_f1=0.3754
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:35,352] Trial 6 finished with value: 0.384324745917627 and parameters: {'hidden_layer_sizes': 464, 'alpha': 0.0004460003723253954, 'learning_rate_init': 0.03254258639505908}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5631 | avg_f1=0.3843
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:35,779] Trial 7 finished with value: 0.37748006666473927 and parameters: {'hidden_layer_sizes': 516, 'alpha': 0.036999871194584734, 'learning_rate_init': 0.003202940513236511}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5380 | avg_f1=0.3775
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:24:36,221] Trial 8 finished with value: 0.3650434671213294 and parameters: {'hidden_layer_sizes': 583, 'alpha': 1.229240222192382e-06, 'learning_rate_init': 0.014762146368693439}. Best is trial 0 with value: 0.42295717926405196.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5753 | avg_f1=0.3650
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:36,554] Trial 9 finished with value: 0.42487112426455154 and parameters: {'hidden_layer_sizes': 54, 'alpha': 1.1987993240341913e-05, 'learning_rate_init': 0.00021746160220204562}. Best is trial 9 with value: 0.42487112426455154.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5698 | avg_f1=0.4249
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 1.0}
Mejores parámetros para TRXUSDT_1d: {'hidden_layer_sizes': 54, 'alpha': 1.1987993240341913e-05, 'learning_rate_init': 0.00021746160220204562}

C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:780: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-06-21 23:24:37,312] A new study created in memory with name: no-name-500b2282-50f6-4283-a165-857c0b6bfbe7

FINAL TEST | TRXUSDT_1d | acc=0.5765 | f1=0.5385
    Desbalanceo reales      : {1: 0.6010928961748634, 0: 0.3989071038251366}
    Desbalanceo predicciones: {1: 0.6857923497267759, 0: 0.31420765027322406}

[I 2025-06-21 23:24:37,550] Trial 0 finished with value: 0.33014675854749387 and parameters: {'hidden_layer_sizes': 70, 'alpha': 9.468036527956773e-06, 'learning_rate_init': 1.936751309833368e-05}. Best is trial 0 with value: 0.33014675854749387.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5002 | avg_f1=0.3301
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 1.0}

[I 2025-06-21 23:24:38,295] Trial 1 finished with value: 0.29553515809771874 and parameters: {'hidden_layer_sizes': 872, 'alpha': 1.3725749591450856e-06, 'learning_rate_init': 0.006554491294954784}. Best is trial 0 with value: 0.33014675854749387.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4149 | avg_f1=0.2955
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9333333333333333, 1: 0.06666666666666667}

[I 2025-06-21 23:24:38,660] Trial 2 finished with value: 0.3635378861633834 and parameters: {'hidden_layer_sizes': 152, 'alpha': 0.00010106102004977555, 'learning_rate_init': 0.004679048765621434}. Best is trial 2 with value: 0.3635378861633834.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4244 | avg_f1=0.3635
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:24:38,898] Trial 3 finished with value: 0.32933913221058614 and parameters: {'hidden_layer_sizes': 77, 'alpha': 8.286112246137511e-06, 'learning_rate_init': 1.8652229583649448e-05}. Best is trial 2 with value: 0.3635378861633834.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4998 | avg_f1=0.3293
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:39,598] Trial 4 finished with value: 0.33973024133085106 and parameters: {'hidden_layer_sizes': 847, 'alpha': 0.0010083274738008285, 'learning_rate_init': 0.0040694149369692265}. Best is trial 2 with value: 0.3635378861633834.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4522 | avg_f1=0.3397
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.6133333333333333, 1: 0.38666666666666666}

[I 2025-06-21 23:24:40,167] Trial 5 finished with value: 0.37958653605460124 and parameters: {'hidden_layer_sizes': 407, 'alpha': 3.388862677638985e-05, 'learning_rate_init': 8.165023227240798e-05}. Best is trial 5 with value: 0.37958653605460124.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4520 | avg_f1=0.3796
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}

[I 2025-06-21 23:24:40,689] Trial 6 finished with value: 0.3159367366524358 and parameters: {'hidden_layer_sizes': 502, 'alpha': 0.00039728498738625314, 'learning_rate_init': 0.0034037521817486477}. Best is trial 5 with value: 0.37958653605460124.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4133 | avg_f1=0.3159
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.88, 1: 0.12}

[I 2025-06-21 23:24:41,450] Trial 7 finished with value: 0.3899561025792317 and parameters: {'hidden_layer_sizes': 995, 'alpha': 0.0001237120715044712, 'learning_rate_init': 2.800085492585873e-05}. Best is trial 7 with value: 0.3899561025792317.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4911 | avg_f1=0.3900
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {1: 0.88, 0: 0.12}

[I 2025-06-21 23:24:41,761] Trial 8 finished with value: 0.3336058239479159 and parameters: {'hidden_layer_sizes': 103, 'alpha': 3.527508207826338e-06, 'learning_rate_init': 0.0024657978381007277}. Best is trial 7 with value: 0.3899561025792317.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4051 | avg_f1=0.3336
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7866666666666666, 1: 0.21333333333333335}

[I 2025-06-21 23:24:42,573] Trial 9 finished with value: 0.35288981410304937 and parameters: {'hidden_layer_sizes': 1012, 'alpha': 0.035406625528358465, 'learning_rate_init': 0.0009408907522380787}. Best is trial 7 with value: 0.3899561025792317.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4682 | avg_f1=0.3529
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}
Mejores parámetros para LINKUSDT_1d: {'hidden_layer_sizes': 995, 'alpha': 0.0001237120715044712, 'learning_rate_init': 2.800085492585873e-05}

[I 2025-06-21 23:24:43,904] A new study created in memory with name: no-name-13f644ef-36e6-4e17-b98c-7aa9c484b8cb

FINAL TEST | LINKUSDT_1d | acc=0.4754 | f1=0.3476
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {1: 0.9480874316939891, 0: 0.05191256830601093}

[I 2025-06-21 23:24:44,299] Trial 0 finished with value: 0.3306207824668089 and parameters: {'hidden_layer_sizes': 128, 'alpha': 0.007461969714282743, 'learning_rate_init': 0.031172757608280255}. Best is trial 0 with value: 0.3306207824668089.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4264 | avg_f1=0.3306
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.9733333333333334, 1: 0.02666666666666667}

[I 2025-06-21 23:24:44,584] Trial 1 finished with value: 0.30242714891809114 and parameters: {'hidden_layer_sizes': 47, 'alpha': 0.0816971188206203, 'learning_rate_init': 0.0041026741619074325}. Best is trial 0 with value: 0.3306207824668089.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.3976 | avg_f1=0.3024
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:45,663] Trial 2 finished with value: 0.3538511363205939 and parameters: {'hidden_layer_sizes': 916, 'alpha': 1.9662422402843268e-06, 'learning_rate_init': 0.005671786680049125}. Best is trial 2 with value: 0.3538511363205939.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4564 | avg_f1=0.3539
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.8133333333333334, 1: 0.18666666666666668}

[I 2025-06-21 23:24:46,073] Trial 3 finished with value: 0.2688372988642298 and parameters: {'hidden_layer_sizes': 365, 'alpha': 0.00017514289667688366, 'learning_rate_init': 0.043346345277080894}. Best is trial 2 with value: 0.3538511363205939.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.3531 | avg_f1=0.2688
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:46,674] Trial 4 finished with value: 0.29653143656952524 and parameters: {'hidden_layer_sizes': 607, 'alpha': 0.022217787225825302, 'learning_rate_init': 0.02975767246104622}. Best is trial 2 with value: 0.3538511363205939.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.3576 | avg_f1=0.2965
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:47,686] Trial 5 finished with value: 0.31377368861805544 and parameters: {'hidden_layer_sizes': 989, 'alpha': 2.9472305107702175e-06, 'learning_rate_init': 0.0002375292779815847}. Best is trial 2 with value: 0.3538511363205939.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.3947 | avg_f1=0.3138
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:24:48,271] Trial 6 finished with value: 0.26836169040243046 and parameters: {'hidden_layer_sizes': 677, 'alpha': 2.751009970088464e-05, 'learning_rate_init': 3.943258926318518e-05}. Best is trial 2 with value: 0.3538511363205939.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.3453 | avg_f1=0.2684
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:24:48,826] Trial 7 finished with value: 0.3794346968558866 and parameters: {'hidden_layer_sizes': 514, 'alpha': 0.0006198854653800853, 'learning_rate_init': 0.00012253945250898803}. Best is trial 7 with value: 0.3794346968558866.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4833 | avg_f1=0.3794
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {1: 0.84, 0: 0.16}

[I 2025-06-21 23:24:49,866] Trial 8 finished with value: 0.3879677381474901 and parameters: {'hidden_layer_sizes': 827, 'alpha': 0.00357483317135911, 'learning_rate_init': 0.01024133874676655}. Best is trial 8 with value: 0.3879677381474901.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4667 | avg_f1=0.3880
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.5733333333333334, 1: 0.4266666666666667}

[I 2025-06-21 23:24:50,600] Trial 9 finished with value: 0.3581438182388418 and parameters: {'hidden_layer_sizes': 760, 'alpha': 3.733633261370406e-05, 'learning_rate_init': 0.0013716246013098577}. Best is trial 8 with value: 0.3879677381474901.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4709 | avg_f1=0.3581
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {1: 0.5733333333333334, 0: 0.4266666666666667}
Mejores parámetros para AVAXUSDT_1d: {'hidden_layer_sizes': 827, 'alpha': 0.00357483317135911, 'learning_rate_init': 0.01024133874676655}

[I 2025-06-21 23:24:51,078] A new study created in memory with name: no-name-48ad1f2e-33ea-4694-a2f3-2ea595ba0a6c

FINAL TEST | AVAXUSDT_1d | acc=0.5328 | f1=0.3725
    Desbalanceo reales      : {0: 0.5245901639344263, 1: 0.47540983606557374}
    Desbalanceo predicciones: {0: 0.9808743169398907, 1: 0.01912568306010929}


=== Entrenando modelo: RandomForestClassifier ===

[I 2025-06-21 23:24:52,639] Trial 0 finished with value: 0.4845488449122855 and parameters: {'n_estimators': 168, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.4845488449122855.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5040 | avg_f1=0.4845
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:24:59,610] Trial 1 finished with value: 0.4490449180686647 and parameters: {'n_estimators': 608, 'max_depth': 28, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': False}. Best is trial 0 with value: 0.4845488449122855.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4818 | avg_f1=0.4490
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5333333333333333, 0: 0.4666666666666667}

[I 2025-06-21 23:25:03,948] Trial 2 finished with value: 0.5041842760386175 and parameters: {'n_estimators': 902, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 2 with value: 0.5041842760386175.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5271 | avg_f1=0.5042
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:25:08,534] Trial 3 finished with value: 0.4950423835708084 and parameters: {'n_estimators': 794, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.5041842760386175.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5167 | avg_f1=0.4950
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5066666666666667, 0: 0.49333333333333335}

[I 2025-06-21 23:25:12,311] Trial 4 finished with value: 0.4937967465202263 and parameters: {'n_estimators': 401, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 2 with value: 0.5041842760386175.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5156 | avg_f1=0.4938
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5333333333333333, 0: 0.4666666666666667}

[I 2025-06-21 23:25:17,104] Trial 5 finished with value: 0.49772654339599043 and parameters: {'n_estimators': 837, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.5041842760386175.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5204 | avg_f1=0.4977
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:25:18,079] Trial 6 finished with value: 0.5004011980730356 and parameters: {'n_estimators': 138, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.5041842760386175.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5211 | avg_f1=0.5004
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5066666666666667, 0: 0.49333333333333335}

[I 2025-06-21 23:25:19,580] Trial 7 finished with value: 0.5087850969547908 and parameters: {'n_estimators': 272, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False}. Best is trial 7 with value: 0.5087850969547908.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5311 | avg_f1=0.5088
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5333333333333333, 0: 0.4666666666666667}

[I 2025-06-21 23:25:21,643] Trial 8 finished with value: 0.5104415095647655 and parameters: {'n_estimators': 411, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 8 with value: 0.5104415095647655.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5262 | avg_f1=0.5104
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:25:26,184] Trial 9 finished with value: 0.507497113930291 and parameters: {'n_estimators': 910, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 8 with value: 0.5104415095647655.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5320 | avg_f1=0.5075
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}
Mejores parámetros para BTCUSDT_1d: {'n_estimators': 411, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}

[I 2025-06-21 23:25:27,723] A new study created in memory with name: no-name-43b820d4-71f0-46f4-90a6-0e9767e23210

FINAL TEST | BTCUSDT_1d | acc=0.4918 | f1=0.4725
    Desbalanceo reales      : {1: 0.5628415300546448, 0: 0.4371584699453552}
    Desbalanceo predicciones: {0: 0.7540983606557377, 1: 0.2459016393442623}
    Pesos promedio entrenamiento: {0: 1.0551470588235294, 1: 0.9503311258278145}

[I 2025-06-21 23:25:29,885] Trial 0 finished with value: 0.41759815484231194 and parameters: {'n_estimators': 364, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.41759815484231194.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4691 | avg_f1=0.4176
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7333333333333333, 1: 0.26666666666666666}

[I 2025-06-21 23:25:35,235] Trial 1 finished with value: 0.42219519972991026 and parameters: {'n_estimators': 934, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.42219519972991026.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4762 | avg_f1=0.4222
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-21 23:25:36,488] Trial 2 finished with value: 0.40705624704843685 and parameters: {'n_estimators': 239, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.42219519972991026.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4613 | avg_f1=0.4071
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7866666666666666, 1: 0.21333333333333335}

[I 2025-06-21 23:25:38,420] Trial 3 finished with value: 0.42041879731612913 and parameters: {'n_estimators': 315, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.42219519972991026.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4724 | avg_f1=0.4204
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:25:39,944] Trial 4 finished with value: 0.4147252708761552 and parameters: {'n_estimators': 288, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.42219519972991026.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4647 | avg_f1=0.4147
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7333333333333333, 1: 0.26666666666666666}

[I 2025-06-21 23:25:44,120] Trial 5 finished with value: 0.42766403587671037 and parameters: {'n_estimators': 841, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.42766403587671037.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4789 | avg_f1=0.4277
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:25:47,995] Trial 6 finished with value: 0.41601612069194777 and parameters: {'n_estimators': 682, 'max_depth': 27, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 0.42766403587671037.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4658 | avg_f1=0.4160
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:25:51,157] Trial 7 finished with value: 0.424836565437531 and parameters: {'n_estimators': 384, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 5 with value: 0.42766403587671037.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4740 | avg_f1=0.4248
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7733333333333333, 1: 0.22666666666666666}

[I 2025-06-21 23:25:55,094] Trial 8 finished with value: 0.41510105149021503 and parameters: {'n_estimators': 694, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 0.42766403587671037.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4673 | avg_f1=0.4151
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-21 23:25:58,381] Trial 9 finished with value: 0.4156349679119968 and parameters: {'n_estimators': 655, 'max_depth': 26, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.42766403587671037.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4662 | avg_f1=0.4156
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7733333333333333, 1: 0.22666666666666666}
Mejores parámetros para ETHUSDT_1d: {'n_estimators': 841, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}

[I 2025-06-21 23:26:02,772] A new study created in memory with name: no-name-ec0bb6b9-4b58-4713-8df7-02e96aaee3c0

FINAL TEST | ETHUSDT_1d | acc=0.4891 | f1=0.4891
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {0: 0.5163934426229508, 1: 0.48360655737704916}
    Pesos promedio entrenamiento: {0: 1.0708955223880596, 1: 0.9379084967320261}

[I 2025-06-21 23:26:07,129] Trial 0 finished with value: 0.47299190967238386 and parameters: {'n_estimators': 756, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.47299190967238386.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5216 | avg_f1=0.4730
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7866666666666666, 0: 0.21333333333333335}

[I 2025-06-21 23:26:11,078] Trial 1 finished with value: 0.5096550076824047 and parameters: {'n_estimators': 491, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.5096550076824047.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5467 | avg_f1=0.5097
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.6133333333333333, 0: 0.38666666666666666}

[I 2025-06-21 23:26:15,354] Trial 2 finished with value: 0.48626090495717256 and parameters: {'n_estimators': 859, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.5096550076824047.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5402 | avg_f1=0.4863
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8666666666666667, 0: 0.13333333333333333}

[I 2025-06-21 23:26:18,168] Trial 3 finished with value: 0.48990409032912385 and parameters: {'n_estimators': 554, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.5096550076824047.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5416 | avg_f1=0.4899
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}

[I 2025-06-21 23:26:23,121] Trial 4 finished with value: 0.489658193430223 and parameters: {'n_estimators': 983, 'max_depth': 23, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.5096550076824047.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5424 | avg_f1=0.4897
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8666666666666667, 0: 0.13333333333333333}

[I 2025-06-21 23:26:24,107] Trial 5 finished with value: 0.5190576087895502 and parameters: {'n_estimators': 155, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 0.5190576087895502.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5604 | avg_f1=0.5191
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}

[I 2025-06-21 23:26:26,360] Trial 6 finished with value: 0.4886142576931764 and parameters: {'n_estimators': 440, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 0.5190576087895502.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5404 | avg_f1=0.4886
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}

[I 2025-06-21 23:26:30,450] Trial 7 finished with value: 0.4899708620054531 and parameters: {'n_estimators': 802, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 0.5190576087895502.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5413 | avg_f1=0.4900
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8666666666666667, 0: 0.13333333333333333}

[I 2025-06-21 23:26:31,145] Trial 8 finished with value: 0.5000665736189267 and parameters: {'n_estimators': 109, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 0.5190576087895502.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5464 | avg_f1=0.5001
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7866666666666666, 0: 0.21333333333333335}

[I 2025-06-21 23:26:32,253] Trial 9 finished with value: 0.47370268636061075 and parameters: {'n_estimators': 165, 'max_depth': 23, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 5 with value: 0.5190576087895502.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5264 | avg_f1=0.4737
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}
Mejores parámetros para XRPUSDT_1d: {'n_estimators': 155, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}

[I 2025-06-21 23:26:33,186] A new study created in memory with name: no-name-f3993da8-857e-4a05-be13-3e9758a5b5af

FINAL TEST | XRPUSDT_1d | acc=0.5137 | f1=0.5133
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {0: 0.5218579234972678, 1: 0.4781420765027322}
    Pesos promedio entrenamiento: {0: 0.9487603305785124, 1: 1.0570902394106814}

[I 2025-06-21 23:26:34,729] Trial 0 finished with value: 0.43348625446445216 and parameters: {'n_estimators': 282, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4811 | avg_f1=0.4335
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8, 1: 0.2}

[I 2025-06-21 23:26:39,186] Trial 1 finished with value: 0.389398647718617 and parameters: {'n_estimators': 559, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4496 | avg_f1=0.3894
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9466666666666667, 1: 0.05333333333333334}

[I 2025-06-21 23:26:40,114] Trial 2 finished with value: 0.417298864423314 and parameters: {'n_estimators': 148, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4704 | avg_f1=0.4173
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.72, 1: 0.28}

[I 2025-06-21 23:26:44,930] Trial 3 finished with value: 0.40461596461782 and parameters: {'n_estimators': 846, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4642 | avg_f1=0.4046
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9333333333333333, 1: 0.06666666666666667}

[I 2025-06-21 23:26:47,308] Trial 4 finished with value: 0.42581406574877184 and parameters: {'n_estimators': 397, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4793 | avg_f1=0.4258
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7866666666666666, 1: 0.21333333333333335}

[I 2025-06-21 23:26:48,979] Trial 5 finished with value: 0.4049496097360857 and parameters: {'n_estimators': 260, 'max_depth': 29, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4662 | avg_f1=0.4049
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.88, 1: 0.12}

[I 2025-06-21 23:26:51,661] Trial 6 finished with value: 0.4254552235551186 and parameters: {'n_estimators': 532, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.43348625446445216.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4756 | avg_f1=0.4255
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8266666666666667, 1: 0.17333333333333334}

[I 2025-06-21 23:26:55,361] Trial 7 finished with value: 0.4569060608326703 and parameters: {'n_estimators': 281, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 7 with value: 0.4569060608326703.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4847 | avg_f1=0.4569
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:26:58,594] Trial 8 finished with value: 0.4253928328772302 and parameters: {'n_estimators': 660, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 7 with value: 0.4569060608326703.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4758 | avg_f1=0.4254
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8533333333333334, 1: 0.14666666666666667}

[I 2025-06-21 23:27:00,062] Trial 9 finished with value: 0.430035801436893 and parameters: {'n_estimators': 262, 'max_depth': 22, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 7 with value: 0.4569060608326703.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4793 | avg_f1=0.4300
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8133333333333334, 1: 0.18666666666666668}
Mejores parámetros para BNBUSDT_1d: {'n_estimators': 281, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}

[I 2025-06-21 23:27:08,921] A new study created in memory with name: no-name-d9b3bc26-2865-4add-99db-5676897d5a73

FINAL TEST | BNBUSDT_1d | acc=0.4809 | f1=0.4702
    Desbalanceo reales      : {1: 0.5382513661202186, 0: 0.46174863387978143}
    Desbalanceo predicciones: {0: 0.680327868852459, 1: 0.319672131147541}
    Pesos promedio entrenamiento: {0: 1.0493601462522852, 1: 0.9550748752079867}

[I 2025-06-21 23:27:15,205] Trial 0 finished with value: 0.4125230478290655 and parameters: {'n_estimators': 815, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.4125230478290655.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4676 | avg_f1=0.4125
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5733333333333334, 1: 0.4266666666666667}

[I 2025-06-21 23:27:16,943] Trial 1 finished with value: 0.42545909375881763 and parameters: {'n_estimators': 248, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.42545909375881763.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4876 | avg_f1=0.4255
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:27:20,697] Trial 2 finished with value: 0.42236898038926285 and parameters: {'n_estimators': 398, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.42545909375881763.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4656 | avg_f1=0.4224
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5733333333333334, 1: 0.4266666666666667}

[I 2025-06-21 23:27:21,989] Trial 3 finished with value: 0.4096902392091197 and parameters: {'n_estimators': 220, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 1 with value: 0.42545909375881763.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4480 | avg_f1=0.4097
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:27:23,000] Trial 4 finished with value: 0.41045987742231127 and parameters: {'n_estimators': 142, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.42545909375881763.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4564 | avg_f1=0.4105
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.6133333333333333, 1: 0.38666666666666666}

[I 2025-06-21 23:27:27,922] Trial 5 finished with value: 0.4357651947083812 and parameters: {'n_estimators': 416, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}. Best is trial 5 with value: 0.4357651947083812.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4820 | avg_f1=0.4358
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:27:30,956] Trial 6 finished with value: 0.44202922854872195 and parameters: {'n_estimators': 226, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.44202922854872195.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4751 | avg_f1=0.4420
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.52, 1: 0.48}

[I 2025-06-21 23:27:35,851] Trial 7 finished with value: 0.43648326512251 and parameters: {'n_estimators': 400, 'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.44202922854872195.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4827 | avg_f1=0.4365
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.5333333333333333, 0: 0.4666666666666667}

[I 2025-06-21 23:27:38,376] Trial 8 finished with value: 0.4008250945548055 and parameters: {'n_estimators': 487, 'max_depth': 26, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.44202922854872195.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4449 | avg_f1=0.4008
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5333333333333333, 1: 0.4666666666666667}

[I 2025-06-21 23:27:40,953] Trial 9 finished with value: 0.4048902302744568 and parameters: {'n_estimators': 491, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.44202922854872195.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4484 | avg_f1=0.4049
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {1: 0.5066666666666667, 0: 0.49333333333333335}
Mejores parámetros para SOLUSDT_1d: {'n_estimators': 226, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}

[I 2025-06-21 23:27:49,142] A new study created in memory with name: no-name-cce11d09-fee4-4921-9a0d-7dabe157da5e

FINAL TEST | SOLUSDT_1d | acc=0.4727 | f1=0.4724
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {1: 0.5109289617486339, 0: 0.4890710382513661}
    Pesos promedio entrenamiento: {0: 1.0323741007194245, 1: 0.9695945945945946}

[I 2025-06-21 23:27:52,722] Trial 0 finished with value: 0.45397938575080354 and parameters: {'n_estimators': 627, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.45397938575080354.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5347 | avg_f1=0.4540
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.84, 0: 0.16}

[I 2025-06-21 23:27:57,573] Trial 1 finished with value: 0.4790600639695925 and parameters: {'n_estimators': 841, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.4790600639695925.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5498 | avg_f1=0.4791
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.8133333333333334, 0: 0.18666666666666668}

[I 2025-06-21 23:28:01,340] Trial 2 finished with value: 0.4774386066700031 and parameters: {'n_estimators': 472, 'max_depth': 26, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.4790600639695925.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5436 | avg_f1=0.4774
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.76, 0: 0.24}

[I 2025-06-21 23:28:03,878] Trial 3 finished with value: 0.4712208313975263 and parameters: {'n_estimators': 421, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 1 with value: 0.4790600639695925.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5411 | avg_f1=0.4712
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.7866666666666666, 0: 0.21333333333333335}

[I 2025-06-21 23:28:07,442] Trial 4 finished with value: 0.48365761918776184 and parameters: {'n_estimators': 706, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 4 with value: 0.48365761918776184.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5438 | avg_f1=0.4837
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.68, 0: 0.32}

[I 2025-06-21 23:28:09,354] Trial 5 finished with value: 0.4755149089681804 and parameters: {'n_estimators': 190, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 4 with value: 0.48365761918776184.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5231 | avg_f1=0.4755
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.68, 0: 0.32}

[I 2025-06-21 23:28:10,916] Trial 6 finished with value: 0.47450577463014965 and parameters: {'n_estimators': 125, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.48365761918776184.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5013 | avg_f1=0.4745
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.5866666666666667, 1: 0.41333333333333333}

[I 2025-06-21 23:28:18,189] Trial 7 finished with value: 0.4747280830982231 and parameters: {'n_estimators': 678, 'max_depth': 27, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.48365761918776184.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5051 | avg_f1=0.4747
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.5466666666666666, 1: 0.4533333333333333}

[I 2025-06-21 23:28:20,012] Trial 8 finished with value: 0.458645739765905 and parameters: {'n_estimators': 184, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 4 with value: 0.48365761918776184.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5247 | avg_f1=0.4586
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.6933333333333334, 0: 0.30666666666666664}

[I 2025-06-21 23:28:21,095] Trial 9 finished with value: 0.5053747675988974 and parameters: {'n_estimators': 159, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 9 with value: 0.5053747675988974.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5631 | avg_f1=0.5054
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.7466666666666667, 0: 0.25333333333333335}
Mejores parámetros para ADAUSDT_1d: {'n_estimators': 159, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}

[I 2025-06-21 23:28:21,669] A new study created in memory with name: no-name-13b37df1-5deb-47fb-85d0-31e349c66b90

FINAL TEST | ADAUSDT_1d | acc=0.5492 | f1=0.5272
    Desbalanceo reales      : {0: 0.5409836065573771, 1: 0.45901639344262296}
    Desbalanceo predicciones: {0: 0.674863387978142, 1: 0.3251366120218579}
    Pesos promedio entrenamiento: {0: 0.9695945945945946, 1: 1.0323741007194245}

[I 2025-06-21 23:28:28,722] Trial 0 finished with value: 0.47646268564907307 and parameters: {'n_estimators': 771, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.47646268564907307.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5084 | avg_f1=0.4765
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.56, 1: 0.44}

[I 2025-06-21 23:28:30,657] Trial 1 finished with value: 0.47165995489111295 and parameters: {'n_estimators': 197, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.47646268564907307.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4993 | avg_f1=0.4717
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-21 23:28:39,816] Trial 2 finished with value: 0.4877102115720023 and parameters: {'n_estimators': 764, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}. Best is trial 2 with value: 0.4877102115720023.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5089 | avg_f1=0.4877
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.5466666666666666, 0: 0.4533333333333333}

[I 2025-06-21 23:28:43,587] Trial 3 finished with value: 0.4657665927184153 and parameters: {'n_estimators': 642, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 2 with value: 0.4877102115720023.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5022 | avg_f1=0.4658
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.52, 1: 0.48}

[I 2025-06-21 23:28:47,728] Trial 4 finished with value: 0.48677789709774333 and parameters: {'n_estimators': 733, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 2 with value: 0.4877102115720023.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5344 | avg_f1=0.4868
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.7733333333333333, 0: 0.22666666666666666}

[I 2025-06-21 23:28:51,237] Trial 5 finished with value: 0.45815299101578066 and parameters: {'n_estimators': 692, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 2 with value: 0.4877102115720023.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4871 | avg_f1=0.4582
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-21 23:28:57,577] Trial 6 finished with value: 0.458112373342051 and parameters: {'n_estimators': 748, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True}. Best is trial 2 with value: 0.4877102115720023.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4869 | avg_f1=0.4581
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-21 23:29:03,382] Trial 7 finished with value: 0.5189376982291314 and parameters: {'n_estimators': 388, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 7 with value: 0.5189376982291314.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5420 | avg_f1=0.5189
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.5733333333333334, 0: 0.4266666666666667}

[I 2025-06-21 23:29:05,429] Trial 8 finished with value: 0.48003873053327756 and parameters: {'n_estimators': 334, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 7 with value: 0.5189376982291314.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5160 | avg_f1=0.4800
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.56, 1: 0.44}

[I 2025-06-21 23:29:14,563] Trial 9 finished with value: 0.4804247274096961 and parameters: {'n_estimators': 854, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}. Best is trial 7 with value: 0.5189376982291314.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5067 | avg_f1=0.4804
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.6, 0: 0.4}
Mejores parámetros para TRXUSDT_1d: {'n_estimators': 388, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}

[I 2025-06-21 23:29:30,349] A new study created in memory with name: no-name-1424bec7-9897-4350-9478-d4f9b5b77ebf

FINAL TEST | TRXUSDT_1d | acc=0.4590 | f1=0.4558
    Desbalanceo reales      : {1: 0.6010928961748634, 0: 0.3989071038251366}
    Desbalanceo predicciones: {0: 0.5245901639344263, 1: 0.47540983606557374}
    Pesos promedio entrenamiento: {0: 1.148, 1: 0.8858024691358025}

[I 2025-06-21 23:29:34,932] Trial 0 finished with value: 0.4662369212756148 and parameters: {'n_estimators': 791, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4662369212756148.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5044 | avg_f1=0.4662
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.96, 1: 0.04}

[I 2025-06-21 23:29:36,605] Trial 1 finished with value: 0.4697878973536726 and parameters: {'n_estimators': 336, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.4697878973536726.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5098 | avg_f1=0.4698
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:29:46,445] Trial 2 finished with value: 0.43698441812936195 and parameters: {'n_estimators': 939, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False}. Best is trial 1 with value: 0.4697878973536726.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4682 | avg_f1=0.4370
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9333333333333333, 1: 0.06666666666666667}

[I 2025-06-21 23:29:49,124] Trial 3 finished with value: 0.4483188105668983 and parameters: {'n_estimators': 317, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True}. Best is trial 1 with value: 0.4697878973536726.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4947 | avg_f1=0.4483
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9866666666666667, 1: 0.013333333333333334}

[I 2025-06-21 23:29:50,694] Trial 4 finished with value: 0.47549388351061184 and parameters: {'n_estimators': 290, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 4 with value: 0.47549388351061184.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5151 | avg_f1=0.4755
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9733333333333334, 1: 0.02666666666666667}

[I 2025-06-21 23:29:57,804] Trial 5 finished with value: 0.4603474352388205 and parameters: {'n_estimators': 867, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': True}. Best is trial 4 with value: 0.47549388351061184.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5029 | avg_f1=0.4603
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9733333333333334, 1: 0.02666666666666667}

[I 2025-06-21 23:30:03,438] Trial 6 finished with value: 0.45242057673787023 and parameters: {'n_estimators': 535, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.47549388351061184.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4744 | avg_f1=0.4524
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-21 23:30:06,798] Trial 7 finished with value: 0.47949417224552554 and parameters: {'n_estimators': 667, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 7 with value: 0.47949417224552554.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5196 | avg_f1=0.4795
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9733333333333334, 1: 0.02666666666666667}

[I 2025-06-21 23:30:11,524] Trial 8 finished with value: 0.4648111912380443 and parameters: {'n_estimators': 847, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 7 with value: 0.47949417224552554.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5064 | avg_f1=0.4648
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 1.0}

[I 2025-06-21 23:30:13,366] Trial 9 finished with value: 0.4885301601141199 and parameters: {'n_estimators': 347, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 9 with value: 0.4885301601141199.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5253 | avg_f1=0.4885
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9333333333333333, 1: 0.06666666666666667}
Mejores parámetros para LINKUSDT_1d: {'n_estimators': 347, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}

[I 2025-06-21 23:30:15,427] A new study created in memory with name: no-name-4cffca88-2fd3-4fe9-a1c4-69809e47c8a2

FINAL TEST | LINKUSDT_1d | acc=0.5191 | f1=0.4733
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {0: 0.7896174863387978, 1: 0.2103825136612022}
    Pesos promedio entrenamiento: {0: 1.0342342342342343, 1: 0.9679595278246206}

[I 2025-06-21 23:30:21,135] Trial 0 finished with value: 0.4945205944278744 and parameters: {'n_estimators': 902, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5318 | avg_f1=0.4945
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}

[I 2025-06-21 23:30:25,684] Trial 1 finished with value: 0.45753666180821223 and parameters: {'n_estimators': 775, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4636 | avg_f1=0.4575
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.7333333333333333, 1: 0.26666666666666666}

[I 2025-06-21 23:30:28,536] Trial 2 finished with value: 0.47904042053102136 and parameters: {'n_estimators': 599, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5020 | avg_f1=0.4790
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:30:31,686] Trial 3 finished with value: 0.4530074495122455 and parameters: {'n_estimators': 620, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4613 | avg_f1=0.4530
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-21 23:30:35,945] Trial 4 finished with value: 0.46724709798431496 and parameters: {'n_estimators': 739, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4747 | avg_f1=0.4672
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-21 23:30:40,055] Trial 5 finished with value: 0.461236457167606 and parameters: {'n_estimators': 711, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4691 | avg_f1=0.4612
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-21 23:30:43,714] Trial 6 finished with value: 0.45575057156854193 and parameters: {'n_estimators': 625, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4640 | avg_f1=0.4558
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6666666666666666, 1: 0.3333333333333333}

[I 2025-06-21 23:30:46,434] Trial 7 finished with value: 0.4605815878834491 and parameters: {'n_estimators': 455, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 0 with value: 0.4945205944278744.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4711 | avg_f1=0.4606
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6266666666666667, 1: 0.37333333333333335}

[I 2025-06-21 23:30:53,023] Trial 8 finished with value: 0.5063052373118777 and parameters: {'n_estimators': 746, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 8 with value: 0.5063052373118777.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5173 | avg_f1=0.5063
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.64, 1: 0.36}

[I 2025-06-21 23:30:56,775] Trial 9 finished with value: 0.4582082837113982 and parameters: {'n_estimators': 636, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 8 with value: 0.5063052373118777.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4653 | avg_f1=0.4582
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6933333333333334, 1: 0.30666666666666664}
Mejores parámetros para AVAXUSDT_1d: {'n_estimators': 746, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}

[I 2025-06-21 23:31:11,275] A new study created in memory with name: no-name-73808ebc-287b-41d1-bafd-4c9307cc1bca

FINAL TEST | AVAXUSDT_1d | acc=0.5656 | f1=0.5514
    Desbalanceo reales      : {0: 0.5245901639344263, 1: 0.47540983606557374}
    Desbalanceo predicciones: {0: 0.6530054644808743, 1: 0.3469945355191257}
    Pesos promedio entrenamiento: {0: 0.9845626072041166, 1: 1.015929203539823}


=== Entrenando modelo: GradientBoostingClassifier ===

[I 2025-06-21 23:32:00,769] Trial 0 finished with value: 0.5068061480479933 and parameters: {'n_estimators': 414, 'learning_rate': 0.07649356779350008, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 13}. Best is trial 0 with value: 0.5068061480479933.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5287 | avg_f1=0.5068
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}

[I 2025-06-21 23:32:36,550] Trial 1 finished with value: 0.46517593108048694 and parameters: {'n_estimators': 384, 'learning_rate': 0.0022757134004584368, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5068061480479933.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4898 | avg_f1=0.4652
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}

[I 2025-06-21 23:32:47,270] Trial 2 finished with value: 0.47959252619337844 and parameters: {'n_estimators': 238, 'learning_rate': 0.001609319696331303, 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5068061480479933.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4911 | avg_f1=0.4796
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {0: 0.5466666666666666, 1: 0.4533333333333333}

[I 2025-06-21 23:33:16,564] Trial 3 finished with value: 0.5149264086709298 and parameters: {'n_estimators': 401, 'learning_rate': 0.0436488258711144, 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 18}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5407 | avg_f1=0.5149
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}

[I 2025-06-21 23:33:43,431] Trial 4 finished with value: 0.512426605562275 and parameters: {'n_estimators': 427, 'learning_rate': 0.0048730046779176354, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 17}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5282 | avg_f1=0.5124
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {0: 0.5066666666666667, 1: 0.49333333333333335}

[I 2025-06-21 23:34:00,635] Trial 5 finished with value: 0.5132114309568359 and parameters: {'n_estimators': 262, 'learning_rate': 0.04400817164286169, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 19}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5376 | avg_f1=0.5132
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.6266666666666667, 0: 0.37333333333333335}

[I 2025-06-21 23:34:22,124] Trial 6 finished with value: 0.4908703037997924 and parameters: {'n_estimators': 250, 'learning_rate': 0.009827393455717051, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5098 | avg_f1=0.4909
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:34:56,149] Trial 7 finished with value: 0.5097847039779946 and parameters: {'n_estimators': 334, 'learning_rate': 0.031231465022994204, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5322 | avg_f1=0.5098
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.6, 0: 0.4}

[I 2025-06-21 23:35:34,046] Trial 8 finished with value: 0.4648110959894689 and parameters: {'n_estimators': 408, 'learning_rate': 0.0011491489642941805, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.5149264086709298.

VALIDATION |  BTCUSDT_1d | avg_acc=0.4936 | avg_f1=0.4648
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.52, 0: 0.48}

[I 2025-06-21 23:36:20,157] Trial 9 finished with value: 0.5186173195397996 and parameters: {'n_estimators': 463, 'learning_rate': 0.012308429457453677, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 12}. Best is trial 9 with value: 0.5186173195397996.

VALIDATION |  BTCUSDT_1d | avg_acc=0.5436 | avg_f1=0.5186
    Desbalanceo reales (val)      : {1: 0.7733333333333333, 0: 0.22666666666666666}
    Desbalanceo predicciones (val): {1: 0.5733333333333334, 0: 0.4266666666666667}
Mejores parámetros para BTCUSDT_1d: {'n_estimators': 463, 'learning_rate': 0.012308429457453677, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 12}

[I 2025-06-21 23:36:36,928] A new study created in memory with name: no-name-f3dc7c42-90c1-4172-b934-4097a6f4ab14

FINAL TEST | BTCUSDT_1d | acc=0.4863 | f1=0.4766
    Desbalanceo reales      : {1: 0.5628415300546448, 0: 0.4371584699453552}
    Desbalanceo predicciones: {0: 0.6994535519125683, 1: 0.3005464480874317}
    Pesos promedio entrenamiento: {0: 1.0551470588235294, 1: 0.9503311258278145}

[I 2025-06-21 23:36:47,514] Trial 0 finished with value: 0.4387231847484605 and parameters: {'n_estimators': 95, 'learning_rate': 0.0999182849676695, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.4387231847484605.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4816 | avg_f1=0.4387
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7866666666666666, 1: 0.21333333333333335}

[I 2025-06-21 23:37:10,199] Trial 1 finished with value: 0.4468723536778584 and parameters: {'n_estimators': 413, 'learning_rate': 0.06524990060831859, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.4468723536778584.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4867 | avg_f1=0.4469
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:37:36,000] Trial 2 finished with value: 0.4307784103814584 and parameters: {'n_estimators': 490, 'learning_rate': 0.0012705813668253568, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 11}. Best is trial 1 with value: 0.4468723536778584.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4773 | avg_f1=0.4308
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.8266666666666667, 1: 0.17333333333333334}

[I 2025-06-21 23:37:49,736] Trial 3 finished with value: 0.42697735979021656 and parameters: {'n_estimators': 398, 'learning_rate': 0.0018217924486907604, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.4468723536778584.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4667 | avg_f1=0.4270
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.88, 1: 0.12}

[I 2025-06-21 23:38:02,690] Trial 4 finished with value: 0.4197985630225226 and parameters: {'n_estimators': 214, 'learning_rate': 0.045108138665379154, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 15}. Best is trial 1 with value: 0.4468723536778584.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4689 | avg_f1=0.4198
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7733333333333333, 1: 0.22666666666666666}

[I 2025-06-21 23:38:21,683] Trial 5 finished with value: 0.46729654604465337 and parameters: {'n_estimators': 343, 'learning_rate': 0.1509656963320892, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.46729654604465337.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4964 | avg_f1=0.4673
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:38:38,877] Trial 6 finished with value: 0.45888363893772893 and parameters: {'n_estimators': 436, 'learning_rate': 0.27945477884861064, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.46729654604465337.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4916 | avg_f1=0.4589
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-21 23:39:11,994] Trial 7 finished with value: 0.44968264000075964 and parameters: {'n_estimators': 359, 'learning_rate': 0.09133449364062662, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 15}. Best is trial 5 with value: 0.46729654604465337.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4898 | avg_f1=0.4497
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7333333333333333, 1: 0.26666666666666666}

[I 2025-06-21 23:39:37,369] Trial 8 finished with value: 0.45037013637160284 and parameters: {'n_estimators': 274, 'learning_rate': 0.02106090614220594, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 14}. Best is trial 5 with value: 0.46729654604465337.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4931 | avg_f1=0.4504
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:40:02,095] Trial 9 finished with value: 0.43791889831127734 and parameters: {'n_estimators': 366, 'learning_rate': 0.001364084020392188, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 17}. Best is trial 5 with value: 0.46729654604465337.

VALIDATION |  ETHUSDT_1d | avg_acc=0.4787 | avg_f1=0.4379
    Desbalanceo reales (val)      : {1: 0.72, 0: 0.28}
    Desbalanceo predicciones (val): {0: 0.72, 1: 0.28}
Mejores parámetros para ETHUSDT_1d: {'n_estimators': 343, 'learning_rate': 0.1509656963320892, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 2}

[I 2025-06-21 23:40:08,388] A new study created in memory with name: no-name-ad9aad91-5888-4fba-92d3-6f48f9f65585

FINAL TEST | ETHUSDT_1d | acc=0.4809 | f1=0.4808
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {0: 0.5027322404371585, 1: 0.4972677595628415}
    Pesos promedio entrenamiento: {0: 1.0708955223880596, 1: 0.9379084967320261}

[I 2025-06-21 23:40:29,234] Trial 0 finished with value: 0.5126368677558365 and parameters: {'n_estimators': 328, 'learning_rate': 0.0023958843668756558, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 19}. Best is trial 0 with value: 0.5126368677558365.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5489 | avg_f1=0.5126
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}

[I 2025-06-21 23:41:15,747] Trial 1 finished with value: 0.5002328138121745 and parameters: {'n_estimators': 496, 'learning_rate': 0.009169893035701563, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 17}. Best is trial 0 with value: 0.5126368677558365.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5413 | avg_f1=0.5002
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7733333333333333, 0: 0.22666666666666666}

[I 2025-06-21 23:41:24,752] Trial 2 finished with value: 0.5373132934048079 and parameters: {'n_estimators': 134, 'learning_rate': 0.0018145786878487017, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 16}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5593 | avg_f1=0.5373
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.64, 0: 0.36}

[I 2025-06-21 23:42:17,516] Trial 3 finished with value: 0.4832739660796325 and parameters: {'n_estimators': 471, 'learning_rate': 0.10425866982887244, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5320 | avg_f1=0.4833
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.84, 0: 0.16}

[I 2025-06-21 23:42:40,651] Trial 4 finished with value: 0.501557099564823 and parameters: {'n_estimators': 248, 'learning_rate': 0.01401367663565072, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 14}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5416 | avg_f1=0.5016
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7733333333333333, 0: 0.22666666666666666}

[I 2025-06-21 23:42:58,898] Trial 5 finished with value: 0.5043622272997597 and parameters: {'n_estimators': 229, 'learning_rate': 0.13092408608858078, 'max_depth': 9, 'min_samples_split': 17, 'min_samples_leaf': 15}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5467 | avg_f1=0.5044
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8666666666666667, 0: 0.13333333333333333}

[I 2025-06-21 23:43:31,407] Trial 6 finished with value: 0.5034264812317876 and parameters: {'n_estimators': 495, 'learning_rate': 0.0016231827612638774, 'max_depth': 12, 'min_samples_split': 19, 'min_samples_leaf': 18}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5409 | avg_f1=0.5034
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.68, 0: 0.32}

[I 2025-06-21 23:43:40,343] Trial 7 finished with value: 0.4968512949481224 and parameters: {'n_estimators': 113, 'learning_rate': 0.028546781914383205, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 20}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5402 | avg_f1=0.4969
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7466666666666667, 0: 0.25333333333333335}

[I 2025-06-21 23:44:26,096] Trial 8 finished with value: 0.4874801072433237 and parameters: {'n_estimators': 430, 'learning_rate': 0.07499030762931833, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 11}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5327 | avg_f1=0.4875
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.8266666666666667, 0: 0.17333333333333334}

[I 2025-06-21 23:44:52,114] Trial 9 finished with value: 0.5287843617985402 and parameters: {'n_estimators': 324, 'learning_rate': 0.001436345397309369, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.5373132934048079.

VALIDATION |  XRPUSDT_1d | avg_acc=0.5593 | avg_f1=0.5288
    Desbalanceo reales (val)      : {1: 0.6, 0: 0.4}
    Desbalanceo predicciones (val): {1: 0.7066666666666667, 0: 0.29333333333333333}
Mejores parámetros para XRPUSDT_1d: {'n_estimators': 134, 'learning_rate': 0.0018145786878487017, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 16}

[I 2025-06-21 23:44:55,276] A new study created in memory with name: no-name-b35f2e1e-f201-4359-a27e-26a2561902e4

FINAL TEST | XRPUSDT_1d | acc=0.5492 | f1=0.5486
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {1: 0.5409836065573771, 0: 0.45901639344262296}
    Pesos promedio entrenamiento: {0: 0.9487603305785124, 1: 1.0570902394106814}

[I 2025-06-21 23:45:23,984] Trial 0 finished with value: 0.4560881839737675 and parameters: {'n_estimators': 356, 'learning_rate': 0.00912468353706711, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 11}. Best is trial 0 with value: 0.4560881839737675.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5004 | avg_f1=0.4561
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8133333333333334, 1: 0.18666666666666668}

[I 2025-06-21 23:45:34,889] Trial 1 finished with value: 0.45276902462596125 and parameters: {'n_estimators': 183, 'learning_rate': 0.0010155722356832773, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.4560881839737675.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4887 | avg_f1=0.4528
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.76, 1: 0.24}

[I 2025-06-21 23:45:45,738] Trial 2 finished with value: 0.45279203314578503 and parameters: {'n_estimators': 254, 'learning_rate': 0.034426510209058556, 'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 18}. Best is trial 0 with value: 0.4560881839737675.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4909 | avg_f1=0.4528
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8, 1: 0.2}

[I 2025-06-21 23:46:14,387] Trial 3 finished with value: 0.4602562968331908 and parameters: {'n_estimators': 400, 'learning_rate': 0.0016909849004729878, 'max_depth': 14, 'min_samples_split': 12, 'min_samples_leaf': 13}. Best is trial 3 with value: 0.4602562968331908.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5044 | avg_f1=0.4603
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-21 23:46:56,706] Trial 4 finished with value: 0.4666885372652267 and parameters: {'n_estimators': 494, 'learning_rate': 0.0578103223651733, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.5071 | avg_f1=0.4667
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-21 23:47:08,598] Trial 5 finished with value: 0.4645692896949377 and parameters: {'n_estimators': 348, 'learning_rate': 0.001927475614238462, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 12}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4991 | avg_f1=0.4646
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8266666666666667, 1: 0.17333333333333334}

[I 2025-06-21 23:47:23,318] Trial 6 finished with value: 0.4445443329302021 and parameters: {'n_estimators': 439, 'learning_rate': 0.09992512187196834, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 17}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4876 | avg_f1=0.4445
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.72, 1: 0.28}

[I 2025-06-21 23:47:46,164] Trial 7 finished with value: 0.444244636328725 and parameters: {'n_estimators': 421, 'learning_rate': 0.23038737967341524, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4922 | avg_f1=0.4442
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7333333333333333, 1: 0.26666666666666666}

[I 2025-06-21 23:47:55,151] Trial 8 finished with value: 0.44331805943068947 and parameters: {'n_estimators': 265, 'learning_rate': 0.09608757881340917, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 16}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4864 | avg_f1=0.4433
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7733333333333333, 1: 0.22666666666666666}

[I 2025-06-21 23:48:15,420] Trial 9 finished with value: 0.42334403556590106 and parameters: {'n_estimators': 244, 'learning_rate': 0.2768951018075584, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.4666885372652267.

VALIDATION |  BNBUSDT_1d | avg_acc=0.4756 | avg_f1=0.4233
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.7733333333333333, 1: 0.22666666666666666}
Mejores parámetros para BNBUSDT_1d: {'n_estimators': 494, 'learning_rate': 0.0578103223651733, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}

[I 2025-06-21 23:48:29,527] A new study created in memory with name: no-name-a2f74d22-7f5e-441c-b224-a818cc2ed675

FINAL TEST | BNBUSDT_1d | acc=0.4617 | f1=0.4562
    Desbalanceo reales      : {1: 0.5382513661202186, 0: 0.46174863387978143}
    Desbalanceo predicciones: {0: 0.639344262295082, 1: 0.36065573770491804}
    Pesos promedio entrenamiento: {0: 1.0493601462522852, 1: 0.9550748752079867}

[I 2025-06-21 23:48:44,824] Trial 0 finished with value: 0.43806502202367426 and parameters: {'n_estimators': 304, 'learning_rate': 0.002179468887262364, 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.43806502202367426.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4636 | avg_f1=0.4381
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.6266666666666667, 1: 0.37333333333333335}

[I 2025-06-21 23:49:05,467] Trial 1 finished with value: 0.4034079819786734 and parameters: {'n_estimators': 323, 'learning_rate': 0.0013600517831643393, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 11}. Best is trial 0 with value: 0.43806502202367426.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4489 | avg_f1=0.4034
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-21 23:49:43,911] Trial 2 finished with value: 0.4399241002628436 and parameters: {'n_estimators': 486, 'learning_rate': 0.0027467229451518024, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 7}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4689 | avg_f1=0.4399
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5466666666666666, 1: 0.4533333333333333}

[I 2025-06-21 23:49:57,520] Trial 3 finished with value: 0.4158446972510358 and parameters: {'n_estimators': 138, 'learning_rate': 0.2814364357250063, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 15}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4604 | avg_f1=0.4158
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5866666666666667, 1: 0.41333333333333333}

[I 2025-06-21 23:50:16,477] Trial 4 finished with value: 0.43457661830896155 and parameters: {'n_estimators': 162, 'learning_rate': 0.0909953659643911, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 5}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4724 | avg_f1=0.4346
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.56, 1: 0.44}

[I 2025-06-21 23:50:34,292] Trial 5 finished with value: 0.439456098449016 and parameters: {'n_estimators': 285, 'learning_rate': 0.0020770980531451483, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 16}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4869 | avg_f1=0.4395
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5866666666666667, 1: 0.41333333333333333}

[I 2025-06-21 23:50:38,381] Trial 6 finished with value: 0.4294955368180502 and parameters: {'n_estimators': 53, 'learning_rate': 0.15186946570697699, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4582 | avg_f1=0.4295
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.56, 1: 0.44}

[I 2025-06-21 23:51:01,998] Trial 7 finished with value: 0.4188584368622771 and parameters: {'n_estimators': 268, 'learning_rate': 0.004759071098615557, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4609 | avg_f1=0.4189
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.52, 1: 0.48}

[I 2025-06-21 23:51:18,294] Trial 8 finished with value: 0.4020284490034373 and parameters: {'n_estimators': 230, 'learning_rate': 0.0027016943349368475, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 9}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4458 | avg_f1=0.4020
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-21 23:51:26,503] Trial 9 finished with value: 0.42106837021963733 and parameters: {'n_estimators': 185, 'learning_rate': 0.02683276651777216, 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 12}. Best is trial 2 with value: 0.4399241002628436.

VALIDATION |  SOLUSDT_1d | avg_acc=0.4604 | avg_f1=0.4211
    Desbalanceo reales (val)      : {1: 0.8533333333333334, 0: 0.14666666666666667}
    Desbalanceo predicciones (val): {0: 0.5866666666666667, 1: 0.41333333333333333}
Mejores parámetros para SOLUSDT_1d: {'n_estimators': 486, 'learning_rate': 0.0027467229451518024, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 7}

[I 2025-06-21 23:51:40,156] A new study created in memory with name: no-name-3dd7d3ed-a1cf-4597-bce0-582307ea3c49

FINAL TEST | SOLUSDT_1d | acc=0.4317 | f1=0.4288
    Desbalanceo reales      : {1: 0.5136612021857924, 0: 0.48633879781420764}
    Desbalanceo predicciones: {0: 0.5846994535519126, 1: 0.41530054644808745}
    Pesos promedio entrenamiento: {0: 1.0323741007194245, 1: 0.9695945945945946}

[I 2025-06-21 23:52:05,906] Trial 0 finished with value: 0.44103199072053584 and parameters: {'n_estimators': 492, 'learning_rate': 0.05755191317575009, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.44103199072053584.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4740 | avg_f1=0.4410
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-21 23:52:17,581] Trial 1 finished with value: 0.43015424546023545 and parameters: {'n_estimators': 134, 'learning_rate': 0.1895836015212978, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.44103199072053584.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4596 | avg_f1=0.4302
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-21 23:52:31,102] Trial 2 finished with value: 0.47382669517056736 and parameters: {'n_estimators': 212, 'learning_rate': 0.001099638835503745, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 14}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5278 | avg_f1=0.4738
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.6533333333333333, 0: 0.3466666666666667}

[I 2025-06-21 23:52:53,181] Trial 3 finished with value: 0.4456421239158031 and parameters: {'n_estimators': 354, 'learning_rate': 0.035614853652008484, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4787 | avg_f1=0.4456
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.5333333333333333, 1: 0.4666666666666667}

[I 2025-06-21 23:52:59,796] Trial 4 finished with value: 0.44681937540104333 and parameters: {'n_estimators': 106, 'learning_rate': 0.007329867947897929, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 18}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4984 | avg_f1=0.4468
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.5733333333333334, 0: 0.4266666666666667}

[I 2025-06-21 23:53:29,611] Trial 5 finished with value: 0.43269829086288797 and parameters: {'n_estimators': 340, 'learning_rate': 0.01763852582603365, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 12}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4767 | avg_f1=0.4327
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}

[I 2025-06-21 23:53:52,171] Trial 6 finished with value: 0.44280107471374064 and parameters: {'n_estimators': 432, 'learning_rate': 0.16730976339272463, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 15}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4767 | avg_f1=0.4428
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {0: 0.6133333333333333, 1: 0.38666666666666666}

[I 2025-06-21 23:54:09,501] Trial 7 finished with value: 0.43621630111351556 and parameters: {'n_estimators': 201, 'learning_rate': 0.016013720789020636, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 18}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4811 | avg_f1=0.4362
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}

[I 2025-06-21 23:54:27,464] Trial 8 finished with value: 0.43138124385251214 and parameters: {'n_estimators': 235, 'learning_rate': 0.010422173724822776, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.47382669517056736.

VALIDATION |  ADAUSDT_1d | avg_acc=0.4740 | avg_f1=0.4314
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.5066666666666667, 0: 0.49333333333333335}

[I 2025-06-21 23:54:33,076] Trial 9 finished with value: 0.47520594104465524 and parameters: {'n_estimators': 90, 'learning_rate': 0.0011937572788299647, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 15}. Best is trial 9 with value: 0.47520594104465524.

VALIDATION |  ADAUSDT_1d | avg_acc=0.5264 | avg_f1=0.4752
    Desbalanceo reales (val)      : {1: 0.8, 0: 0.2}
    Desbalanceo predicciones (val): {1: 0.5866666666666667, 0: 0.41333333333333333}
Mejores parámetros para ADAUSDT_1d: {'n_estimators': 90, 'learning_rate': 0.0011937572788299647, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 15}

[I 2025-06-21 23:54:35,392] A new study created in memory with name: no-name-f62b5d7f-72a4-4d5a-a9a1-82faa13a1b91

FINAL TEST | ADAUSDT_1d | acc=0.5656 | f1=0.5443
    Desbalanceo reales      : {0: 0.5409836065573771, 1: 0.45901639344262296}
    Desbalanceo predicciones: {0: 0.674863387978142, 1: 0.3251366120218579}
    Pesos promedio entrenamiento: {0: 0.9695945945945946, 1: 1.0323741007194245}

[I 2025-06-21 23:55:00,468] Trial 0 finished with value: 0.4852968384826841 and parameters: {'n_estimators': 233, 'learning_rate': 0.01337688164656049, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5093 | avg_f1=0.4853
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.64, 1: 0.36}

[I 2025-06-21 23:55:13,550] Trial 1 finished with value: 0.47951989566854636 and parameters: {'n_estimators': 167, 'learning_rate': 0.025507541937428473, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5038 | avg_f1=0.4795
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.64, 1: 0.36}

[I 2025-06-21 23:55:34,223] Trial 2 finished with value: 0.48302759762771075 and parameters: {'n_estimators': 476, 'learning_rate': 0.055331174115663004, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5104 | avg_f1=0.4830
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.5066666666666667, 0: 0.49333333333333335}

[I 2025-06-21 23:56:05,135] Trial 3 finished with value: 0.47737759761927095 and parameters: {'n_estimators': 395, 'learning_rate': 0.20891383661412347, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5040 | avg_f1=0.4774
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.5466666666666666, 0: 0.4533333333333333}

[I 2025-06-21 23:56:23,251] Trial 4 finished with value: 0.4800634515277908 and parameters: {'n_estimators': 223, 'learning_rate': 0.001265048220334825, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 14}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.5040 | avg_f1=0.4801
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-21 23:56:39,958] Trial 5 finished with value: 0.4391455432833741 and parameters: {'n_estimators': 162, 'learning_rate': 0.09392144900478235, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4667 | avg_f1=0.4391
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.5733333333333334, 1: 0.4266666666666667}

[I 2025-06-21 23:56:58,829] Trial 6 finished with value: 0.4545555290487064 and parameters: {'n_estimators': 251, 'learning_rate': 0.2538375453813642, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 16}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4793 | avg_f1=0.4546
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-21 23:57:09,858] Trial 7 finished with value: 0.45978599989919255 and parameters: {'n_estimators': 122, 'learning_rate': 0.046258704039252634, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 11}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4867 | avg_f1=0.4598
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.6533333333333333, 1: 0.3466666666666667}

[I 2025-06-21 23:57:22,963] Trial 8 finished with value: 0.4269400520581369 and parameters: {'n_estimators': 380, 'learning_rate': 0.013872761982992901, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 11}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4580 | avg_f1=0.4269
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {0: 0.5466666666666666, 1: 0.4533333333333333}

[I 2025-06-21 23:57:35,507] Trial 9 finished with value: 0.4718364151171003 and parameters: {'n_estimators': 188, 'learning_rate': 0.03145276381763321, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.4852968384826841.

VALIDATION |  TRXUSDT_1d | avg_acc=0.4991 | avg_f1=0.4718
    Desbalanceo reales (val)      : {1: 0.6933333333333334, 0: 0.30666666666666664}
    Desbalanceo predicciones (val): {1: 0.56, 0: 0.44}
Mejores parámetros para TRXUSDT_1d: {'n_estimators': 233, 'learning_rate': 0.01337688164656049, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 10}

[I 2025-06-21 23:57:44,468] A new study created in memory with name: no-name-8205f4fb-3583-4ae4-a197-11817e83c50c

FINAL TEST | TRXUSDT_1d | acc=0.4836 | f1=0.4584
    Desbalanceo reales      : {1: 0.6010928961748634, 0: 0.3989071038251366}
    Desbalanceo predicciones: {1: 0.6147540983606558, 0: 0.38524590163934425}
    Pesos promedio entrenamiento: {0: 1.148, 1: 0.8858024691358025}

[I 2025-06-21 23:58:11,058] Trial 0 finished with value: 0.4530508018428832 and parameters: {'n_estimators': 234, 'learning_rate': 0.22588176963829143, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 13}. Best is trial 0 with value: 0.4530508018428832.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4944 | avg_f1=0.4531
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8933333333333333, 1: 0.10666666666666667}

[I 2025-06-21 23:58:15,406] Trial 1 finished with value: 0.4456753505278469 and parameters: {'n_estimators': 127, 'learning_rate': 0.2707089916272007, 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 18}. Best is trial 0 with value: 0.4530508018428832.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4924 | avg_f1=0.4457
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.92, 1: 0.08}

[I 2025-06-21 23:58:27,417] Trial 2 finished with value: 0.4520366387663146 and parameters: {'n_estimators': 208, 'learning_rate': 0.004306617466860633, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 13}. Best is trial 0 with value: 0.4530508018428832.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4942 | avg_f1=0.4520
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9733333333333334, 1: 0.02666666666666667}

[I 2025-06-21 23:59:09,155] Trial 3 finished with value: 0.4677226228051299 and parameters: {'n_estimators': 500, 'learning_rate': 0.001971080818773312, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.4677226228051299.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4978 | avg_f1=0.4677
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8, 1: 0.2}

[I 2025-06-21 23:59:14,984] Trial 4 finished with value: 0.4774586375174608 and parameters: {'n_estimators': 91, 'learning_rate': 0.01296521856015128, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 18}. Best is trial 4 with value: 0.4774586375174608.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5164 | avg_f1=0.4775
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9066666666666666, 1: 0.09333333333333334}

[I 2025-06-21 23:59:38,670] Trial 5 finished with value: 0.44850273886931563 and parameters: {'n_estimators': 289, 'learning_rate': 0.0015961786085460267, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.4774586375174608.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4853 | avg_f1=0.4485
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8933333333333333, 1: 0.10666666666666667}

[I 2025-06-21 23:59:44,947] Trial 6 finished with value: 0.48404784979343035 and parameters: {'n_estimators': 75, 'learning_rate': 0.021899442770276348, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.48404784979343035.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5204 | avg_f1=0.4840
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9466666666666667, 1: 0.05333333333333334}

[I 2025-06-22 00:00:02,548] Trial 7 finished with value: 0.461139874326873 and parameters: {'n_estimators': 269, 'learning_rate': 0.0720944427390449, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.48404784979343035.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4998 | avg_f1=0.4611
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8, 1: 0.2}

[I 2025-06-22 00:00:26,705] Trial 8 finished with value: 0.45703099914000134 and parameters: {'n_estimators': 280, 'learning_rate': 0.20585263202841608, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 17}. Best is trial 6 with value: 0.48404784979343035.

VALIDATION |  LINKUSDT_1d | avg_acc=0.4991 | avg_f1=0.4570
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.8666666666666667, 1: 0.13333333333333333}

[I 2025-06-22 00:00:32,011] Trial 9 finished with value: 0.4731491380107632 and parameters: {'n_estimators': 60, 'learning_rate': 0.05978364312049581, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.48404784979343035.

VALIDATION |  LINKUSDT_1d | avg_acc=0.5087 | avg_f1=0.4731
    Desbalanceo reales (val)      : {1: 0.7066666666666667, 0: 0.29333333333333333}
    Desbalanceo predicciones (val): {0: 0.9066666666666666, 1: 0.09333333333333334}
Mejores parámetros para LINKUSDT_1d: {'n_estimators': 75, 'learning_rate': 0.021899442770276348, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 7}

[I 2025-06-22 00:00:34,295] A new study created in memory with name: no-name-64d8d487-97da-44e4-bfb6-dbf01dc27bc9

FINAL TEST | LINKUSDT_1d | acc=0.4891 | f1=0.4487
    Desbalanceo reales      : {0: 0.505464480874317, 1: 0.49453551912568305}
    Desbalanceo predicciones: {0: 0.7650273224043715, 1: 0.23497267759562843}
    Pesos promedio entrenamiento: {0: 1.0342342342342343, 1: 0.9679595278246206}

[I 2025-06-22 00:01:15,407] Trial 0 finished with value: 0.4846730499301123 and parameters: {'n_estimators': 399, 'learning_rate': 0.015082856089022607, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.4846730499301123.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4940 | avg_f1=0.4847
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.68, 1: 0.32}

[I 2025-06-22 00:01:41,353] Trial 1 finished with value: 0.4817881910257483 and parameters: {'n_estimators': 286, 'learning_rate': 0.0018585768471017885, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.4846730499301123.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4918 | avg_f1=0.4818
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.7066666666666667, 1: 0.29333333333333333}

[I 2025-06-22 00:02:21,722] Trial 2 finished with value: 0.47578434829739996 and parameters: {'n_estimators': 434, 'learning_rate': 0.0022827776755973265, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.4846730499301123.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4904 | avg_f1=0.4758
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6, 1: 0.4}

[I 2025-06-22 00:03:01,943] Trial 3 finished with value: 0.49092239431145723 and parameters: {'n_estimators': 451, 'learning_rate': 0.0014350293783878126, 'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.49092239431145723.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5029 | avg_f1=0.4909
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6533333333333333, 1: 0.3466666666666667}

[I 2025-06-22 00:03:22,304] Trial 4 finished with value: 0.47451008684590257 and parameters: {'n_estimators': 226, 'learning_rate': 0.01441216851315347, 'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 16}. Best is trial 3 with value: 0.49092239431145723.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4818 | avg_f1=0.4745
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.8666666666666667, 1: 0.13333333333333333}

[I 2025-06-22 00:03:54,019] Trial 5 finished with value: 0.4792336772114988 and parameters: {'n_estimators': 461, 'learning_rate': 0.25663602276460457, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 18}. Best is trial 3 with value: 0.49092239431145723.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4878 | avg_f1=0.4792
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.9333333333333333, 1: 0.06666666666666667}

[I 2025-06-22 00:04:28,915] Trial 6 finished with value: 0.500545197516524 and parameters: {'n_estimators': 488, 'learning_rate': 0.0010337954197787967, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 14}. Best is trial 6 with value: 0.500545197516524.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.5087 | avg_f1=0.5005
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.7466666666666667, 1: 0.25333333333333335}

[I 2025-06-22 00:05:11,801] Trial 7 finished with value: 0.48493797232712144 and parameters: {'n_estimators': 467, 'learning_rate': 0.054014468176782925, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.500545197516524.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4933 | avg_f1=0.4849
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.6933333333333334, 1: 0.30666666666666664}

[I 2025-06-22 00:05:34,080] Trial 8 finished with value: 0.4635331405244557 and parameters: {'n_estimators': 387, 'learning_rate': 0.009869311592856256, 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 20}. Best is trial 6 with value: 0.500545197516524.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4702 | avg_f1=0.4635
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.8533333333333334, 1: 0.14666666666666667}

[I 2025-06-22 00:05:40,481] Trial 9 finished with value: 0.47176357419757053 and parameters: {'n_estimators': 62, 'learning_rate': 0.1764368317823784, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 17}. Best is trial 6 with value: 0.500545197516524.

VALIDATION |  AVAXUSDT_1d | avg_acc=0.4796 | avg_f1=0.4718
    Desbalanceo reales (val)      : {1: 0.84, 0: 0.16}
    Desbalanceo predicciones (val): {0: 0.9466666666666667, 1: 0.05333333333333334}
Mejores parámetros para AVAXUSDT_1d: {'n_estimators': 488, 'learning_rate': 0.0010337954197787967, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 14}

FINAL TEST | AVAXUSDT_1d | acc=0.5464 | f1=0.5271
    Desbalanceo reales      : {0: 0.5245901639344263, 1: 0.47540983606557374}
    Desbalanceo predicciones: {0: 0.6775956284153005, 1: 0.3224043715846995}
    Pesos promedio entrenamiento: {0: 0.9845626072041166, 1: 1.015929203539823}


=== Mejores hiperparámetros por modelo ===
MLPClassifier: {'BTCUSDT_1d': {'hidden_layer_sizes': 788, 'alpha': 1.0434457704508487e-05, 'learning_rate_init': 4.541446876658177e-05}, 'ETHUSDT_1d': {'hidden_layer_sizes': 498, 'alpha': 0.061769432132595385, 'learning_rate_init': 0.00012694296322331695}, 'XRPUSDT_1d': {'hidden_layer_sizes': 331, 'alpha': 2.0857960583134598e-05, 'learning_rate_init': 3.676583542812448e-05}, 'BNBUSDT_1d': {'hidden_layer_sizes': 419, 'alpha': 2.695167048530188e-06, 'learning_rate_init': 6.543814148805816e-05}, 'SOLUSDT_1d': {'hidden_layer_sizes': 469, 'alpha': 4.283346357587249e-05, 'learning_rate_init': 1.0257359458276104e-05}, 'ADAUSDT_1d': {'hidden_layer_sizes': 516, 'alpha': 2.5266916794387685e-05, 'learning_rate_init': 7.73743653103505e-05}, 'TRXUSDT_1d': {'hidden_layer_sizes': 54, 'alpha': 1.1987993240341913e-05, 'learning_rate_init': 0.00021746160220204562}, 'LINKUSDT_1d': {'hidden_layer_sizes': 995, 'alpha': 0.0001237120715044712, 'learning_rate_init': 2.800085492585873e-05}, 'AVAXUSDT_1d': {'hidden_layer_sizes': 827, 'alpha': 0.00357483317135911, 'learning_rate_init': 0.01024133874676655}}
RandomForestClassifier: {'BTCUSDT_1d': {'n_estimators': 411, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}, 'ETHUSDT_1d': {'n_estimators': 841, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}, 'XRPUSDT_1d': {'n_estimators': 155, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}, 'BNBUSDT_1d': {'n_estimators': 281, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}, 'SOLUSDT_1d': {'n_estimators': 226, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}, 'ADAUSDT_1d': {'n_estimators': 159, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}, 'TRXUSDT_1d': {'n_estimators': 388, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}, 'LINKUSDT_1d': {'n_estimators': 347, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}, 'AVAXUSDT_1d': {'n_estimators': 746, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}}
GradientBoostingClassifier: {'BTCUSDT_1d': {'n_estimators': 463, 'learning_rate': 0.012308429457453677, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 12}, 'ETHUSDT_1d': {'n_estimators': 343, 'learning_rate': 0.1509656963320892, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 2}, 'XRPUSDT_1d': {'n_estimators': 134, 'learning_rate': 0.0018145786878487017, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 16}, 'BNBUSDT_1d': {'n_estimators': 494, 'learning_rate': 0.0578103223651733, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}, 'SOLUSDT_1d': {'n_estimators': 486, 'learning_rate': 0.0027467229451518024, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 7}, 'ADAUSDT_1d': {'n_estimators': 90, 'learning_rate': 0.0011937572788299647, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 15}, 'TRXUSDT_1d': {'n_estimators': 233, 'learning_rate': 0.01337688164656049, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 10}, 'LINKUSDT_1d': {'n_estimators': 75, 'learning_rate': 0.021899442770276348, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 7}, 'AVAXUSDT_1d': {'n_estimators': 488, 'learning_rate': 0.0010337954197787967, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 14}}